// Generated by tools/import-official-data.py for development fallback only.
// Production catalog and assignment options are served by the backend API.

export type OfficialCatalogRow = {
  code: string;
  name: string;
  responsible: string;
  contributors: string;
  activity: string;
};

export const officialIndicatorPlantelScopes: Record<string, number[]> = {
  "1.0.0.0.2": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    37
  ],
  "1.1.2.0.3": [
    3
  ],
  "1.1.2.5.3": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    37
  ],
  "2.1.4.1.2": [
    17
  ]
};

export const officialCatalogRows: OfficialCatalogRow[] = [
  {
    "code": "1.0.0.0.2",
    "name": "Porcentaje de titulación por cohorte del NMS",
    "responsible": "Responsable 01",
    "contributors": "Responsable 10",
    "activity": "1.0.0.0.2 Titulación por cohorte.xlsx"
  },
  {
    "code": "1.1.2.0.1",
    "name": "Porcentaje retención escolar de educación media superior",
    "responsible": "Responsable 07",
    "contributors": "Responsable 10",
    "activity": "Indicador 1.1.2.0.1..xlsx"
  },
  {
    "code": "1.1.2.0.1",
    "name": "PORCENTAJE DE RETENCIÓN ESCOLAR DE EMS",
    "responsible": "Responsable 05",
    "contributors": "Responsable 10",
    "activity": "1.1.2.0.1. porcentaje de retención escolar de EMS.xlsx"
  },
  {
    "code": "1.1.2.0.3",
    "name": "Tasa de abandono escolar de educación media superior",
    "responsible": "Responsable 07",
    "contributors": "Responsable 10",
    "activity": "Indicador 1.1.2.0.3..xlsx"
  },
  {
    "code": "1.1.2.0.3",
    "name": "TASA DE ABANDONO ESCOLAR DE EDUCACIÓN MEDIA SUPERIOR",
    "responsible": "Responsable 05",
    "contributors": "Responsable 10",
    "activity": "1.1.2.0.3.Estrategias para combatir el abandono escolar.xlsx"
  },
  {
    "code": "1.1.2.1.4",
    "name": "Porcentaje de estudiantes de educación media superior y superior atendidos en los servicios de salud integral",
    "responsible": "Responsable 04",
    "contributors": "Responsable 10",
    "activity": "PROMOCIÓN DE LA SALUD"
  },
  {
    "code": "1.1.2.2.1",
    "name": "REPORTE DE ATENCIÓN A ESTUDIANTES EN NIVELACIÓN ACADÉMICA PARA EL PERIODO ORDINARIO",
    "responsible": "Responsable 08",
    "contributors": "Responsable 10",
    "activity": "NIVELACION ACADEMICA_ agosto 2025_ENERO2026 (1).xlsx"
  },
  {
    "code": "1.1.2.2.10",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de sostenibilidad y medio ambiente para la acción climática",
    "responsible": "Responsable 09",
    "contributors": "Responsable 10",
    "activity": "1.1.2.2.10.xlsx"
  },
  {
    "code": "1.1.2.2.11",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de igualdad de género",
    "responsible": "Responsable 03",
    "contributors": "Responsable 10",
    "activity": "1.1.2.2.11 Seguimiento capacitación en materia de género planteles.xlsx"
  },
  {
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de NMS y NS participantes en las actividades de desarrollo y formación integral",
    "responsible": "Responsable 03",
    "contributors": "Responsable 10",
    "activity": "1.1.2.3.1 Programa Adopta una Prepa .xlsx"
  },
  {
    "code": "1.1.2.3.1",
    "name": "PORCENTAJE DE ESTUDIANTES DE MEDIA SUPERIOR QUE PARTICIPAN EN ACTIVIDADES DE FORMACIÓN INTEGRAL",
    "responsible": "Responsable 05",
    "contributors": "Responsable 10",
    "activity": "1.1.2.3.1.Convocatorias externas .xlsx"
  },
  {
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral",
    "responsible": "Responsable 04",
    "contributors": "Responsable 10",
    "activity": "VIAJES DE ESTUDIO"
  },
  {
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral",
    "responsible": "Responsable 09",
    "contributors": "Responsable 10",
    "activity": "1.1.2.3.1.xlsx"
  },
  {
    "code": "1.1.2.3.1",
    "name": "PORCENTAJE DE ESTUDIANTES DE MEDIA SUPERIOR QUE PARTICIPAN EN ACTIVIDADES DE FORMACIÓN INTEGRAL",
    "responsible": "Responsable 05",
    "contributors": "Responsable 10",
    "activity": "1.1.2.3.1. Modelo de las Naciones Unidas.xlsx"
  },
  {
    "code": "1.1.2.5.10",
    "name": "Porcentaje de docentes de educación media superior y superior certificados en el dominio de una Lengua Extranjera",
    "responsible": "Responsable 06",
    "contributors": "Responsable 10",
    "activity": "1.1.2.5.10 - Porcentaje de docentes de educación media superior y superior certificados en el dominio de una Lengua Extranjera.xlsx"
  },
  {
    "code": "1.1.2.5.3",
    "name": "Porcentaje de PTC de educación media superior beneficiados en el programa de ESDEPED",
    "responsible": "Responsable 01",
    "contributors": "Responsable 10",
    "activity": "1.1.2.5.3 Seguimiento de PTC.xlsx"
  },
  {
    "code": "2.1.4.1.2",
    "name": "Número de estudiantes que colaboran en proyectos de investigación liderados por profesorado de tiempo completo",
    "responsible": "Responsable 03",
    "contributors": "Responsable 10",
    "activity": "2.1.4.1.2 Seguimiento a proyectos de investigación en planteles.xlsx"
  },
  {
    "code": "3.1.0.0.1",
    "name": "Número de programas y proyectos de extensión y vinculación dirigidas al sector social y productivo",
    "responsible": "Responsable 09",
    "contributors": "Responsable 10",
    "activity": "3.1.0.0.1.xlsx"
  },
  {
    "code": "3.1.1.3.6",
    "name": "Número de participantes en actividades de sostenibilidad y medio ambiente convocadas por el SIGA",
    "responsible": "Responsable 09",
    "contributors": "Responsable 10",
    "activity": "3.1.1.3.6.xlsx"
  },
  {
    "code": "4.1.1.0.1",
    "name": "Número de Sistemas de Información Institucionales que interoperan",
    "responsible": "Responsable 02",
    "contributors": "Responsable 10",
    "activity": "4.1.1.0.1. Numero de Sistemas de Informacion Institucionales que interoperan.xlsx"
  },
  {
    "code": "4.1.1.1.1",
    "name": "Número de sistemas implementados y mejorados para fortalecer la gestión de procesos institucionales",
    "responsible": "Responsable 02",
    "contributors": "Responsable 10",
    "activity": "4.1.1.1.1. - Número de sistemas implementados y mejorados para fortalecer la gestión de procesos institucionales..xlsx"
  },
  {
    "code": "4.1.2.2.1",
    "name": "Porcentaje de UO que realizan acciones de actualización, mantenimiento preventivo y/o correctivo a la infraestructura tecnológica",
    "responsible": "Responsable 02",
    "contributors": "Responsable 10",
    "activity": "41221 - Porcentaje de UO que realizan acciones de actualización, mantenimiento preventivo o correctivo de la insfraestructura tecnologica.xlsx"
  }
];
