// Generated by tools/import-official-data.py from indicadores-20260622T210134Z-3-001.zip.
// Source binaries and row-level private data are intentionally not committed.

export type OfficialCatalogRow = {
  sourceRow: number;
  code: string;
  sourceCode: string;
  officialCode?: string | null;
  name: string;
  responsible: string;
  contributors: string;
  activity: string;
  classification: "operational" | "template" | "template_variant" | "pending_mapping";
  visible: boolean;
  classificationReason: string[];
  dedupeKey: string;
  isDuplicate: boolean;
  duplicateOfSourceRow: number | null;
  dataQuality: string[];
};

export const officialCatalogStats = {
  "sourceRows": 28,
  "uniqueRows": 28,
  "duplicateRows": 0,
  "uniqueSourceCodes": 28,
  "uniqueIndicators": 14,
  "operationalRows": 20,
  "templateRows": 1,
  "templateVariantRows": 3,
  "pendingMappingRows": 4,
  "uniqueResponsibles": 8,
  "uniqueContributors": 1,
  "uniqueActivities": 20,
  "blankActivities": 0,
  "workbookOnlyIndicators": 0
} as const;

export const officialIndicatorPlantelScopes: Record<string, number[]> = {
  "1.0.0.0.2": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    37
  ],
  "1.1.2.0.3": [
    3
  ],
  "1.1.2.5.3": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    37
  ],
  "2.1.4.1.2": [
    17
  ]
};

export const officialCatalogRows: OfficialCatalogRow[] = [
  {
    "sourceRow": 2,
    "code": "1.0.0.0.2",
    "sourceCode": "1.0.0.0.2",
    "officialCode": "1.0.0.0.2",
    "name": "Porcentaje de titulación por cohorte del NMS",
    "responsible": "Responsable 01",
    "contributors": "Responsable 11",
    "activity": "1.0.0.0.2 Titulación por cohorte.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "28520ef8dfc2c601",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 3,
    "code": "1.0.0.0.2-FMT-7639E719",
    "sourceCode": "1.0.0.0.2-FMT-7639E719",
    "officialCode": "1.0.0.0.2",
    "name": "Porcentaje de titulación por cohorte del NMS",
    "responsible": "Responsable 01",
    "contributors": "Responsable 11",
    "activity": "Titulación por cohorte.xlsx",
    "classification": "template_variant",
    "visible": false,
    "classificationReason": [
      "variant_source_code",
      "format_source"
    ],
    "dedupeKey": "ef8d4648d1a687f0",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 4,
    "code": "1.1.1.1.1",
    "sourceCode": "1.1.1.1.1",
    "officialCode": "1.1.1.1.1",
    "name": "Porcentaje de programas educativos de educación media superior nuevos, actualizados y reestructurados alineados al modelo educativo, incorporando formalmente el enfoque de sostenib",
    "responsible": "Responsable 01",
    "contributors": "Responsable 11",
    "activity": "Formato con OPCIONES de llenado de academias por plantel.xlsx",
    "classification": "template",
    "visible": false,
    "classificationReason": [
      "format_source"
    ],
    "dedupeKey": "7ca263e16298dcd3",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 5,
    "code": "1.1.1.1.1-FMT-489662BE",
    "sourceCode": "1.1.1.1.1-FMT-489662BE",
    "officialCode": "1.1.1.1.1",
    "name": "Porcentaje de programas educativos de educación media superior nuevos, actualizados y reestructurados alineados al modelo educativo, incorporando formalmente el enfoque de sostenib",
    "responsible": "Responsable 01",
    "contributors": "Responsable 11",
    "activity": "1.1.1.1.1 Formato conformación de academias por plantel.xlsx",
    "classification": "template_variant",
    "visible": false,
    "classificationReason": [
      "variant_source_code",
      "format_source"
    ],
    "dedupeKey": "632348b91837a35f",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 6,
    "code": "1.1.2.0.1",
    "sourceCode": "1.1.2.0.1",
    "officialCode": "1.1.2.0.1",
    "name": "Porcentaje retención escolar de educación media superior",
    "responsible": "Responsable 07",
    "contributors": "Responsable 11",
    "activity": "Indicador 1.1.2.0.1..xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "001f4b7ba0f71a11",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 7,
    "code": "1.1.2.0.1",
    "sourceCode": "1.1.2.0.1-FMT-4EB45B2E",
    "officialCode": "1.1.2.0.1",
    "name": "PORCENTAJE DE RETENCIÓN ESCOLAR DE EMS",
    "responsible": "Responsable 05",
    "contributors": "Responsable 11",
    "activity": "1.1.2.0.1. porcentaje de retención escolar de EMS.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [
      "variant_source_code",
      "merged_to_official_code"
    ],
    "dedupeKey": "3492b2221b094c51",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 8,
    "code": "1.1.2.0.3",
    "sourceCode": "1.1.2.0.3",
    "officialCode": "1.1.2.0.3",
    "name": "TASA DE ABANDONO ESCOLAR DE EDUCACIÓN MEDIA SUPERIOR",
    "responsible": "Responsable 05",
    "contributors": "Responsable 11",
    "activity": "1.1.2.0.3.Estrategias para combatir el abandono escolar.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "f8be59987b512348",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 9,
    "code": "1.1.2.0.3",
    "sourceCode": "1.1.2.0.3-FMT-EDABD54D",
    "officialCode": "1.1.2.0.3",
    "name": "Tasa de abadono escolar de educación media superior",
    "responsible": "Responsable 07",
    "contributors": "Responsable 11",
    "activity": "Indicador 1.1.2.0.3..xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [
      "variant_source_code",
      "merged_to_official_code"
    ],
    "dedupeKey": "5b3f524c8b039516",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 10,
    "code": "1.1.2.1.4",
    "sourceCode": "1.1.2.1.4",
    "officialCode": "1.1.2.1.4",
    "name": "Porcentaje de estudiantes de educación media superior y superior atendidos en los servicios de salud integral",
    "responsible": "Responsable 04",
    "contributors": "Responsable 11",
    "activity": "PROMOCIÓN DE LA SALUD",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "34bba557a6dc75f1",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 11,
    "code": "1.1.2.2.10",
    "sourceCode": "1.1.2.2.10",
    "officialCode": "1.1.2.2.10",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de sostenibilidad y medio ambiente para la acción climática",
    "responsible": "Responsable 10",
    "contributors": "Responsable 11",
    "activity": "1.1.2.2.10.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "6297e0e68afbe45d",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 12,
    "code": "1.1.2.2.11",
    "sourceCode": "1.1.2.2.11",
    "officialCode": "1.1.2.2.11",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de igualdad de género",
    "responsible": "Responsable 03",
    "contributors": "Responsable 11",
    "activity": "1.1.2.2.11 Seguimiento capacitación en materia de género planteles.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "79228afcf44daf12",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 13,
    "code": "1.1.2.3.1",
    "sourceCode": "1.1.2.3.1",
    "officialCode": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de NMS y NS participantes en las actividades de desarrollo y formación integral",
    "responsible": "Responsable 03",
    "contributors": "Responsable 11",
    "activity": "1.1.2.3.1 Programa Adopta una Prepa .xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "6da63f4e46e451b7",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 14,
    "code": "1.1.2.3.1",
    "sourceCode": "1.1.2.3.1-FMT-2A7229AD",
    "officialCode": "1.1.2.3.1",
    "name": "PORCENTAJE DE ESTUDIANTES DE MEDIA SUPERIOR QUE PARTICIPAN EN ACTIVIDADES DE FORMACIÓN INTEGRAL",
    "responsible": "Responsable 05",
    "contributors": "Responsable 11",
    "activity": "1.1.2.3.1.Convocatorias externas .xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [
      "variant_source_code",
      "merged_to_official_code"
    ],
    "dedupeKey": "98e42af130c14ad0",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 15,
    "code": "1.1.2.3.1",
    "sourceCode": "1.1.2.3.1-FMT-6434504C",
    "officialCode": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral",
    "responsible": "Responsable 04",
    "contributors": "Responsable 11",
    "activity": "VIAJES DE ESTUDIO",
    "classification": "operational",
    "visible": true,
    "classificationReason": [
      "variant_source_code",
      "merged_to_official_code"
    ],
    "dedupeKey": "b3e9fe6077f6e334",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 16,
    "code": "1.1.2.3.1",
    "sourceCode": "1.1.2.3.1-FMT-AB95A3B8",
    "officialCode": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral",
    "responsible": "Responsable 10",
    "contributors": "Responsable 11",
    "activity": "1.1.2.3.1.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [
      "variant_source_code",
      "merged_to_official_code"
    ],
    "dedupeKey": "39cf91ad2401853e",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 17,
    "code": "1.1.2.3.1",
    "sourceCode": "1.1.2.3.1-FMT-FBF5B718",
    "officialCode": "1.1.2.3.1",
    "name": "PORCENTAJE DE ESTUDIANTES DE MEDIA SUPERIOR QUE PARTICIPAN EN ACTIVIDADES DE FORMACIÓN INTEGRAL",
    "responsible": "Responsable 05",
    "contributors": "Responsable 11",
    "activity": "1.1.2.3.1. Modelo de las Naciones Unidas.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [
      "variant_source_code",
      "merged_to_official_code"
    ],
    "dedupeKey": "cb39dafb1f9b5c12",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 18,
    "code": "1.1.2.5.10",
    "sourceCode": "1.1.2.5.10",
    "officialCode": "1.1.2.5.10",
    "name": "Porcentaje de docentes de educación media superior y superior certificados en el dominio de una Lengua Extranjera",
    "responsible": "Responsable 06",
    "contributors": "Responsable 11",
    "activity": "1.1.2.5.10 - Porcentaje de docentes de educación media superior y superior certificados en el dominio de una Lengua Extranjera.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "a60da5bdb87b0899",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 19,
    "code": "1.1.2.5.3",
    "sourceCode": "1.1.2.5.3",
    "officialCode": "1.1.2.5.3",
    "name": "Porcentaje de PTC de educación media superior beneficiados en el programa de ESDEPED",
    "responsible": "Responsable 01",
    "contributors": "Responsable 11",
    "activity": "1.1.2.5.3 Seguimiento de PTC.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "ce9dc01fea9b4a53",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "canonical_operational_template",
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 20,
    "code": "1.1.2.5.3-FMT-F28103DD",
    "sourceCode": "1.1.2.5.3-FMT-F28103DD",
    "officialCode": "1.1.2.5.3",
    "name": "Porcentaje de PTC de educación media superior beneficiados en el programa de ESDEPED",
    "responsible": "Responsable 01",
    "contributors": "Responsable 11",
    "activity": "Opción de llenado Seguimiento de PTC.xlsx",
    "classification": "template_variant",
    "visible": false,
    "classificationReason": [
      "variant_source_code",
      "format_source"
    ],
    "dedupeKey": "b4427938444276b8",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "canonical_format_hidden",
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 21,
    "code": "2.1.4.1.2",
    "sourceCode": "2.1.4.1.2",
    "officialCode": "2.1.4.1.2",
    "name": "Número de estudiantes que colaboran en proyectos de investigación liderados por profesorado de tiempo completo",
    "responsible": "Responsable 03",
    "contributors": "Responsable 11",
    "activity": "2.1.4.1.2 Seguimiento a proyectos de investigación en planteles.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "e3f2e1d9d912c107",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 22,
    "code": "3.1.0.0.1",
    "sourceCode": "3.1.0.0.1",
    "officialCode": "3.1.0.0.1",
    "name": "Número de programas y proyectos de extensión y vinculación dirigidas al sector social y productivo",
    "responsible": "Responsable 10",
    "contributors": "Responsable 11",
    "activity": "3.1.0.0.1.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "7eb2284c98d74ce9",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 23,
    "code": "3.1.1.3.6",
    "sourceCode": "3.1.1.3.6",
    "officialCode": "3.1.1.3.6",
    "name": "Número de participantes en actividades de sostenibilidad y medio ambiente convocadas por el SIGA",
    "responsible": "Responsable 10",
    "contributors": "Responsable 11",
    "activity": "3.1.1.3.6.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "b6067952b350a8c9",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 24,
    "code": "4.1.1.0.1",
    "sourceCode": "4.1.1.0.1",
    "officialCode": "4.1.1.0.1",
    "name": "Número de Sistemas de Información Institucionales que interoperan",
    "responsible": "Responsable 02",
    "contributors": "Responsable 11",
    "activity": "4.1.1.0.1. Numero de Sistemas de Informacion Institucionales que interoperan.xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "3f2084b45468dec8",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 25,
    "code": "4.1.1.1.1",
    "sourceCode": "4.1.1.1.1",
    "officialCode": "4.1.1.1.1",
    "name": "Número de sistemas implementados y mejorados para fortalecer la gestión de procesos institucionales",
    "responsible": "Responsable 02",
    "contributors": "Responsable 11",
    "activity": "4.1.1.1.1. - Número de sistemas implementados y mejorados para fortalecer la gestión de procesos institucionales..xlsx",
    "classification": "operational",
    "visible": true,
    "classificationReason": [],
    "dedupeKey": "852e1d3591f842e4",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 26,
    "code": "FMT-01-43FE55CA-formacion-docente-2026",
    "sourceCode": "FMT-01-43FE55CA-formacion-docente-2026",
    "officialCode": null,
    "name": "Formación_docente_2026",
    "responsible": "Responsable 09",
    "contributors": "Responsable 11",
    "activity": "Formación_docente_2026.xlsx",
    "classification": "pending_mapping",
    "visible": false,
    "classificationReason": [
      "synthetic_code",
      "no_official_code"
    ],
    "dedupeKey": "32b5496e3123e427",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "pending_indicator_code",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 27,
    "code": "FMT-01-D30B3A90-formacion-apoyo-academic",
    "sourceCode": "FMT-01-D30B3A90-formacion-apoyo-academic",
    "officialCode": null,
    "name": "Formación_apoyo académico_2026",
    "responsible": "Responsable 09",
    "contributors": "Responsable 11",
    "activity": "Formación_apoyo académico_2026.xlsx",
    "classification": "pending_mapping",
    "visible": false,
    "classificationReason": [
      "synthetic_code",
      "no_official_code"
    ],
    "dedupeKey": "736f89c9d9ee3466",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "pending_indicator_code",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 28,
    "code": "FMT-01-E81E8473-41221-porcentaje-de-uo-q",
    "sourceCode": "FMT-01-E81E8473-41221-porcentaje-de-uo-q",
    "officialCode": null,
    "name": "41221 - Porcentaje de UO que realizan acciones de actualización, mantenimiento preventivo o correctivo de la insfraestructura tecnologica",
    "responsible": "Responsable 02",
    "contributors": "Responsable 11",
    "activity": "41221 - Porcentaje de UO que realizan acciones de actualización, mantenimiento preventivo o correctivo de la insfraestructura tecnologica.xlsx",
    "classification": "pending_mapping",
    "visible": false,
    "classificationReason": [
      "synthetic_code",
      "no_official_code"
    ],
    "dedupeKey": "14ea03f1842b9d5d",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "pending_indicator_code",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 29,
    "code": "FMT-01-F2A88F7E-nivelacion-academica-ago",
    "sourceCode": "FMT-01-F2A88F7E-nivelacion-academica-ago",
    "officialCode": null,
    "name": "NIVELACION ACADEMICA_ agosto 2025_ENERO2026 (1)",
    "responsible": "Responsable 08",
    "contributors": "Responsable 11",
    "activity": "NIVELACION ACADEMICA_ agosto 2025_ENERO2026 (1).xlsx",
    "classification": "pending_mapping",
    "visible": false,
    "classificationReason": [
      "synthetic_code",
      "no_official_code"
    ],
    "dedupeKey": "246cc0f0c53cedc2",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "pending_indicator_code",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  }
];
