// Generated by tools/import-official-data.py from official Drive exports.
// Source binaries and personal identifiers are intentionally not committed.

export type OfficialEvidenceGroup = {
  category: string;
  fileCount: number;
  totalBytes: number;
  byExtension: Record<string, number>;
  sampleFileTypes: string[];
};

export type OfficialCalculationConfig =
  | { type: "sum"; sourceKeys: string[] }
  | {
      type: "percentage";
      numeratorKey: string;
      denominatorKey: string;
      decimals?: number;
    }
  | {
      type: "formula";
      expression: string;
      decimals?: number;
    };

export type OfficialWorkbookSheetSummary = {
  name: string;
  nonEmptyRows: number;
  columnsObserved: number;
  sampleHeaders: string[];
  headerRows: string[][];
  numericCells: number;
  textCells: number;
  formulaCells: number;
  table?: {
    headerRow: number;
    headerRows?: Array<Array<{
      label: string;
      colspan?: number;
      rowspan?: number;
    }>>;
    columns: Array<{
      key: string;
      label: string;
      type: "readonly" | "number" | "text" | "calculated";
      calculation?: OfficialCalculationConfig;
      private?: boolean;
    }>;
    initialRows: Array<Record<string, unknown>>;
  } | null;
  codeDescriptions: string[];
  activityDescriptions: string[];
};

export type OfficialWorkbookSummary = {
  id: string;
  sourceLabel: string;
  sourcePathHash: string;
  category: string;
  sizeBytes: number;
  detectedIndicatorCodes: string[];
  detectedReferenceCodes: string[];
  detectedPlanteles: string[];
  formulaCells: number;
  sheets: OfficialWorkbookSheetSummary[];
  privacy: string;
};

export type OfficialTemplateCandidate = {
  indicatorCode: string;
  officialCode?: string | null;
  sourcePath: string;
  planteles: string[];
  classification: string;
  confidence: string;
  headerRows: string[][];
};

export type OfficialWorkbookTemplate = {
  indicatorCode: string;
  officialCode?: string | null;
  indicatorName: string;
  sourceLabel: string;
  activityLabel?: string;
  sourcePath: string;
  sheetName: string;
  groups: Array<{ label: string; colspan: number }>;
  headerRows?: Array<Array<{
    label: string;
    colspan?: number;
    rowspan?: number;
  }>>;
  columns: Array<{
    key: string;
    label: string;
    type: "readonly" | "number" | "text" | "calculated";
    calculation?: OfficialCalculationConfig;
  }>;
  initialRows: Array<Record<string, unknown>>;
  showTotals: boolean;
  allowAddRows: boolean;
  addRowLabel: string;
  emptyRow: Record<string, unknown>;
  footerNote: string;
  quality: string[];
};

export type OfficialDataSummary = {
  sourcePackage: string;
  plantel: string;
  generatedAt: string;
  topLevelFiles: number;
  nestedFiles: number;
  nestedTotalBytes: number;
  workbookCount: number;
  worksheetCount: number;
  worksheetNonEmptyRows: number;
  privacy: string;
};

export const officialDataSummary: OfficialDataSummary = {
  "sourcePackage": "Development fallback",
  "plantel": "Indicadores oficiales",
  "generatedAt": "2026-06-30",
  "topLevelFiles": 0,
  "nestedFiles": 0,
  "nestedTotalBytes": 0,
  "workbookCount": 0,
  "worksheetCount": 0,
  "worksheetNonEmptyRows": 0,
  "privacy": "Frontend fallback contains aggregate structure only; full source labels and row-level personal data are backend-private."
};

export const officialEvidenceGroups: OfficialEvidenceGroup[] = [];

export const officialTemplateCandidates: OfficialTemplateCandidate[] = [];

export const officialWorkbookTemplates: Record<string, OfficialWorkbookTemplate> = {
  "1.0.0.0.2": {
    "indicatorCode": "1.0.0.0.2",
    "officialCode": "1.0.0.0.2",
    "indicatorName": "Porcentaje de titulación por cohorte del NMS",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "Plantel",
          "rowspan": 2
        },
        {
          "label": "Programa Educativo",
          "rowspan": 2
        },
        {
          "label": "Egresados titulados en el año 2025",
          "colspan": 3
        },
        {
          "label": "Matrícula de primer ingreso de la misma cohorte (agosto 2022) de Opciones Técnicas",
          "colspan": 3
        },
        {
          "label": "% de titulación por cohorte",
          "rowspan": 2
        }
      ],
      [
        {
          "label": "Mujeres"
        },
        {
          "label": "Hombres"
        },
        {
          "label": "Total"
        },
        {
          "label": "Mujeres"
        },
        {
          "label": "Hombres"
        },
        {
          "label": "Total"
        }
      ]
    ],
    "columns": [
      {
        "key": "plantel",
        "label": "Plantel",
        "type": "readonly"
      },
      {
        "key": "programa_educativo",
        "label": "Programa Educativo",
        "type": "readonly"
      },
      {
        "key": "egresados_titulados_en_el_ano_2025_mujeres",
        "label": "Egresados Titulados En El Año 2025 Mujeres",
        "type": "number"
      },
      {
        "key": "egresados_titulados_en_el_ano_2025_hombres",
        "label": "Egresados Titulados En El Año 2025 Hombres",
        "type": "number"
      },
      {
        "key": "egresados_titulados_en_el_ano_2025_total",
        "label": "Egresados Titulados En El Año 2025 Total",
        "type": "calculated",
        "calculation": {
          "type": "sum",
          "sourceKeys": [
            "egresados_titulados_en_el_ano_2025_mujeres",
            "egresados_titulados_en_el_ano_2025_hombres"
          ]
        }
      },
      {
        "key": "matricula_de_primer_ingreso_de_la_misma_cohorte_",
        "label": "Matrícula De Primer Ingreso De La Misma Cohorte Mujeres",
        "type": "number"
      },
      {
        "key": "matricula_de_primer_ingreso_de_la_misma_cohorte__2",
        "label": "Matrícula De Primer Ingreso De La Misma Cohorte Hombres",
        "type": "number"
      },
      {
        "key": "matricula_de_primer_ingreso_de_la_misma_cohorte__3",
        "label": "Matrícula De Primer Ingreso De La Misma Cohorte Total",
        "type": "calculated",
        "calculation": {
          "type": "sum",
          "sourceKeys": [
            "matricula_de_primer_ingreso_de_la_misma_cohorte_",
            "matricula_de_primer_ingreso_de_la_misma_cohorte__2"
          ]
        }
      },
      {
        "key": "de_titulacion_por_cohorte",
        "label": "% de titulación por cohorte",
        "type": "calculated",
        "calculation": {
          "type": "percentage",
          "numeratorKey": "egresados_titulados_en_el_ano_2025_total",
          "denominatorKey": "matricula_de_primer_ingreso_de_la_misma_cohorte__3",
          "decimals": 2
        }
      }
    ],
    "initialRows": [
      {
        "plantel": "",
        "programa_educativo": "",
        "egresados_titulados_en_el_ano_2025_mujeres": "",
        "egresados_titulados_en_el_ano_2025_hombres": "",
        "egresados_titulados_en_el_ano_2025_total": "",
        "matricula_de_primer_ingreso_de_la_misma_cohorte_": "",
        "matricula_de_primer_ingreso_de_la_misma_cohorte__2": "",
        "matricula_de_primer_ingreso_de_la_misma_cohorte__3": "",
        "de_titulacion_por_cohorte": ""
      }
    ],
    "showTotals": true,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "plantel": "",
      "programa_educativo": "",
      "egresados_titulados_en_el_ano_2025_mujeres": "",
      "egresados_titulados_en_el_ano_2025_hombres": "",
      "matricula_de_primer_ingreso_de_la_misma_cohorte_": "",
      "matricula_de_primer_ingreso_de_la_misma_cohorte__2": ""
    },
    "footerNote": "",
    "quality": []
  },
  "1.1.2.0.1": {
    "indicatorCode": "1.1.2.0.1",
    "officialCode": "1.1.2.0.1",
    "indicatorName": "PORCENTAJE DE RETENCIÓN ESCOLAR DE EMS",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "Semestre",
          "rowspan": 2
        },
        {
          "label": "Ago 2025-Ene 2026",
          "colspan": 3
        },
        {
          "label": "Semestre",
          "rowspan": 2
        },
        {
          "label": "Feb 2026-Ago 2026",
          "colspan": 3
        },
        {
          "label": "Semestre",
          "rowspan": 2
        },
        {
          "label": "Ago 2026-Ene 2027",
          "colspan": 3
        }
      ],
      [
        {
          "label": "Hombres"
        },
        {
          "label": "Mujeres"
        },
        {
          "label": "Total"
        },
        {
          "label": "Hombres"
        },
        {
          "label": "Mujeres"
        },
        {
          "label": "Total"
        },
        {
          "label": "Hombres"
        },
        {
          "label": "Mujeres"
        },
        {
          "label": "Total"
        }
      ]
    ],
    "columns": [
      {
        "key": "semestre",
        "label": "Semestre",
        "type": "readonly"
      },
      {
        "key": "ago_2025_ene_2026_hombres",
        "label": "Hombres",
        "type": "number"
      },
      {
        "key": "ago_2025_ene_2026_mujeres",
        "label": "Mujeres",
        "type": "number"
      },
      {
        "key": "ago_2025_ene_2026_total",
        "label": "Total",
        "type": "number"
      },
      {
        "key": "semestre_2",
        "label": "Semestre",
        "type": "readonly"
      },
      {
        "key": "feb_2026_ago_2026_hombres",
        "label": "Hombres",
        "type": "number"
      },
      {
        "key": "feb_2026_ago_2026_mujeres",
        "label": "Mujeres",
        "type": "number"
      },
      {
        "key": "feb_2026_ago_2026_total",
        "label": "Total",
        "type": "number"
      },
      {
        "key": "semestre_3",
        "label": "Semestre",
        "type": "readonly"
      },
      {
        "key": "ago_2026_ene_2027_hombres",
        "label": "Hombres",
        "type": "number"
      },
      {
        "key": "ago_2026_ene_2027_mujeres",
        "label": "Mujeres",
        "type": "number"
      },
      {
        "key": "ago_2026_ene_2027_total",
        "label": "Total",
        "type": "number"
      }
    ],
    "initialRows": [
      {
        "semestre": "Primero",
        "ago_2025_ene_2026_hombres": "",
        "ago_2025_ene_2026_mujeres": "",
        "ago_2025_ene_2026_total": "",
        "semestre_2": "Segundo",
        "feb_2026_ago_2026_hombres": "",
        "feb_2026_ago_2026_mujeres": "",
        "feb_2026_ago_2026_total": "",
        "semestre_3": "Primero",
        "ago_2026_ene_2027_hombres": "",
        "ago_2026_ene_2027_mujeres": "",
        "ago_2026_ene_2027_total": ""
      },
      {
        "semestre": "Tercero",
        "ago_2025_ene_2026_hombres": "",
        "ago_2025_ene_2026_mujeres": "",
        "ago_2025_ene_2026_total": "",
        "semestre_2": "Cuarto",
        "feb_2026_ago_2026_hombres": "",
        "feb_2026_ago_2026_mujeres": "",
        "feb_2026_ago_2026_total": "",
        "semestre_3": "Tercero",
        "ago_2026_ene_2027_hombres": "",
        "ago_2026_ene_2027_mujeres": "",
        "ago_2026_ene_2027_total": ""
      },
      {
        "semestre": "Quinto",
        "ago_2025_ene_2026_hombres": "",
        "ago_2025_ene_2026_mujeres": "",
        "ago_2025_ene_2026_total": "",
        "semestre_2": "Sexto",
        "feb_2026_ago_2026_hombres": "",
        "feb_2026_ago_2026_mujeres": "",
        "feb_2026_ago_2026_total": "",
        "semestre_3": "Quinto",
        "ago_2026_ene_2027_hombres": "",
        "ago_2026_ene_2027_mujeres": "",
        "ago_2026_ene_2027_total": ""
      }
    ],
    "showTotals": true,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "semestre": "",
      "ago_2025_ene_2026_hombres": "",
      "ago_2025_ene_2026_mujeres": "",
      "ago_2025_ene_2026_total": "",
      "semestre_2": "",
      "feb_2026_ago_2026_hombres": "",
      "feb_2026_ago_2026_mujeres": "",
      "feb_2026_ago_2026_total": "",
      "semestre_3": "",
      "ago_2026_ene_2027_hombres": "",
      "ago_2026_ene_2027_mujeres": "",
      "ago_2026_ene_2027_total": ""
    },
    "footerNote": "",
    "quality": []
  },
  "1.1.2.0.3": {
    "indicatorCode": "1.1.2.0.3",
    "officialCode": "1.1.2.0.3",
    "indicatorName": "TASA DE ABANDONO ESCOLAR DE EDUCACIÓN MEDIA SUPERIOR",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "Escuela"
        },
        {
          "label": "Semestre"
        },
        {
          "label": "Programa Educativo"
        },
        {
          "label": "Matr."
        },
        {
          "label": "Tasa de Reprobación",
          "colspan": 2
        },
        {
          "label": "Tasa de Aprobación",
          "colspan": 2
        },
        {
          "label": "Tasa de Deserción",
          "colspan": 2
        },
        {
          "label": "Semestre"
        },
        {
          "label": "Tasa de Reprobación",
          "colspan": 2
        },
        {
          "label": "Tasa de Aprobación",
          "colspan": 2
        },
        {
          "label": "Tasa de Deserción",
          "colspan": 2
        }
      ]
    ],
    "columns": [
      {
        "key": "escuela",
        "label": "Escuela",
        "type": "text"
      },
      {
        "key": "semestre",
        "label": "Semestre",
        "type": "readonly"
      },
      {
        "key": "programa_educativo",
        "label": "Programa Educativo",
        "type": "readonly"
      },
      {
        "key": "matr",
        "label": "Matr.",
        "type": "text"
      },
      {
        "key": "tasa_de_reprobacion",
        "label": "Tasa De Reprobacion",
        "type": "text"
      },
      {
        "key": "tasa_de_reprobacion_2",
        "label": "Tasa De Reprobacion",
        "type": "text"
      },
      {
        "key": "tasa_de_aprobacion",
        "label": "Tasa De Aprobacion",
        "type": "text"
      },
      {
        "key": "tasa_de_aprobacion_2",
        "label": "Tasa De Aprobacion",
        "type": "text"
      },
      {
        "key": "tasa_de_desercion",
        "label": "Tasa De Desercion",
        "type": "text"
      },
      {
        "key": "tasa_de_desercion_2",
        "label": "Tasa De Desercion",
        "type": "text"
      },
      {
        "key": "semestre_2",
        "label": "Semestre",
        "type": "readonly"
      },
      {
        "key": "tasa_de_reprobacion_3",
        "label": "Tasa De Reprobacion",
        "type": "text"
      },
      {
        "key": "tasa_de_reprobacion_4",
        "label": "Tasa De Reprobacion",
        "type": "text"
      },
      {
        "key": "tasa_de_aprobacion_3",
        "label": "Tasa De Aprobacion",
        "type": "text"
      },
      {
        "key": "tasa_de_aprobacion_4",
        "label": "Tasa De Aprobacion",
        "type": "text"
      },
      {
        "key": "tasa_de_desercion_3",
        "label": "Tasa De Desercion",
        "type": "text"
      },
      {
        "key": "tasa_de_desercion_4",
        "label": "Tasa De Desercion",
        "type": "text"
      }
    ],
    "initialRows": [
      {
        "escuela": "",
        "semestre": "",
        "programa_educativo": "",
        "matr": "",
        "tasa_de_reprobacion": "No",
        "tasa_de_reprobacion_2": "%",
        "tasa_de_aprobacion": "No",
        "tasa_de_aprobacion_2": "%",
        "tasa_de_desercion": "No",
        "tasa_de_desercion_2": "%",
        "semestre_2": "",
        "tasa_de_reprobacion_3": "No",
        "tasa_de_reprobacion_4": "%",
        "tasa_de_aprobacion_3": "No",
        "tasa_de_aprobacion_4": "%",
        "tasa_de_desercion_3": "No",
        "tasa_de_desercion_4": "%"
      },
      {
        "escuela": "Bachillerato 1",
        "semestre": "Segundo",
        "programa_educativo": "Bachillerato general",
        "matr": "",
        "tasa_de_reprobacion": "",
        "tasa_de_reprobacion_2": "",
        "tasa_de_aprobacion": "",
        "tasa_de_aprobacion_2": "",
        "tasa_de_desercion": "",
        "tasa_de_desercion_2": "",
        "semestre_2": "Primero",
        "tasa_de_reprobacion_3": "",
        "tasa_de_reprobacion_4": "",
        "tasa_de_aprobacion_3": "",
        "tasa_de_aprobacion_4": "",
        "tasa_de_desercion_3": "",
        "tasa_de_desercion_4": ""
      },
      {
        "escuela": "Bachillerato 1",
        "semestre": "Cuarto",
        "programa_educativo": "Bachillerato general",
        "matr": "",
        "tasa_de_reprobacion": "",
        "tasa_de_reprobacion_2": "",
        "tasa_de_aprobacion": "",
        "tasa_de_aprobacion_2": "",
        "tasa_de_desercion": "",
        "tasa_de_desercion_2": "",
        "semestre_2": "Tercero",
        "tasa_de_reprobacion_3": "",
        "tasa_de_reprobacion_4": "",
        "tasa_de_aprobacion_3": "",
        "tasa_de_aprobacion_4": "",
        "tasa_de_desercion_3": "",
        "tasa_de_desercion_4": ""
      },
      {
        "escuela": "Bachillerato 1",
        "semestre": "Sexto",
        "programa_educativo": "Bachillerato general",
        "matr": "",
        "tasa_de_reprobacion": "",
        "tasa_de_reprobacion_2": "",
        "tasa_de_aprobacion": "",
        "tasa_de_aprobacion_2": "",
        "tasa_de_desercion": "",
        "tasa_de_desercion_2": "",
        "semestre_2": "Quinto",
        "tasa_de_reprobacion_3": "",
        "tasa_de_reprobacion_4": "",
        "tasa_de_aprobacion_3": "",
        "tasa_de_aprobacion_4": "",
        "tasa_de_desercion_3": "",
        "tasa_de_desercion_4": ""
      }
    ],
    "showTotals": false,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "escuela": "",
      "semestre": "",
      "programa_educativo": "",
      "matr": "",
      "tasa_de_reprobacion": "",
      "tasa_de_reprobacion_2": "",
      "tasa_de_aprobacion": "",
      "tasa_de_aprobacion_2": "",
      "tasa_de_desercion": "",
      "tasa_de_desercion_2": "",
      "semestre_2": "",
      "tasa_de_reprobacion_3": "",
      "tasa_de_reprobacion_4": "",
      "tasa_de_aprobacion_3": "",
      "tasa_de_aprobacion_4": "",
      "tasa_de_desercion_3": "",
      "tasa_de_desercion_4": ""
    },
    "footerNote": "",
    "quality": []
  },
  "1.1.2.1.4": {
    "indicatorCode": "1.1.2.1.4",
    "officialCode": "1.1.2.1.4",
    "indicatorName": "Porcentaje de estudiantes de educación media superior y superior atendidos en los servicios de salud integral",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "Plantel",
          "rowspan": 2
        },
        {
          "label": "Nota: anotar solo la actividad desarrollada. Unidades de salud integral",
          "colspan": 3
        },
        {
          "label": "Febrero– Agosto 2026",
          "colspan": 3
        },
        {
          "label": "Agosto- Enero 2027",
          "colspan": 3
        }
      ],
      [
        {
          "label": "SERVICIOS MEDICOS"
        },
        {
          "label": "DGDI"
        },
        {
          "label": "CUAP"
        },
        {
          "label": "M"
        },
        {
          "label": "H"
        },
        {
          "label": "T"
        },
        {
          "label": "M"
        },
        {
          "label": "H"
        },
        {
          "label": "T"
        }
      ]
    ],
    "columns": [
      {
        "key": "plantel",
        "label": "Plantel",
        "type": "readonly"
      },
      {
        "key": "nota_anotar_solo_la_actividad_desarrollada_unida",
        "label": "SERVICIOS MEDICOS",
        "type": "text"
      },
      {
        "key": "nota_anotar_solo_la_actividad_desarrollada_unida_2",
        "label": "DGDI",
        "type": "text"
      },
      {
        "key": "nota_anotar_solo_la_actividad_desarrollada_unida_3",
        "label": "CUAP",
        "type": "text"
      },
      {
        "key": "febrero_agosto_2026_m",
        "label": "M",
        "type": "number"
      },
      {
        "key": "febrero_agosto_2026_h",
        "label": "H",
        "type": "number"
      },
      {
        "key": "febrero_agosto_2026_t",
        "label": "T",
        "type": "number"
      },
      {
        "key": "agosto_enero_2027_m",
        "label": "M",
        "type": "number"
      },
      {
        "key": "agosto_enero_2027_h",
        "label": "H",
        "type": "number"
      },
      {
        "key": "agosto_enero_2027_t",
        "label": "T",
        "type": "number"
      }
    ],
    "initialRows": [
      {
        "plantel": "",
        "nota_anotar_solo_la_actividad_desarrollada_unida": "",
        "nota_anotar_solo_la_actividad_desarrollada_unida_2": "",
        "nota_anotar_solo_la_actividad_desarrollada_unida_3": "",
        "febrero_agosto_2026_m": "",
        "febrero_agosto_2026_h": "",
        "febrero_agosto_2026_t": "",
        "agosto_enero_2027_m": "",
        "agosto_enero_2027_h": "",
        "agosto_enero_2027_t": ""
      }
    ],
    "showTotals": true,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "plantel": "",
      "nota_anotar_solo_la_actividad_desarrollada_unida": "",
      "nota_anotar_solo_la_actividad_desarrollada_unida_2": "",
      "nota_anotar_solo_la_actividad_desarrollada_unida_3": "",
      "febrero_agosto_2026_m": "",
      "febrero_agosto_2026_h": "",
      "febrero_agosto_2026_t": "",
      "agosto_enero_2027_m": "",
      "agosto_enero_2027_h": "",
      "agosto_enero_2027_t": ""
    },
    "footerNote": "",
    "quality": []
  },
  "1.1.2.2.1": {
    "indicatorCode": "1.1.2.2.1",
    "officialCode": "1.1.2.2.1",
    "indicatorName": "REPORTE DE ATENCIÓN A ESTUDIANTES EN NIVELACIÓN ACADÉMICA PARA EL PERIODO ORDINARIO",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "PLANTEL",
          "rowspan": 2
        },
        {
          "label": "GRADO",
          "rowspan": 2
        },
        {
          "label": "MATRICULA",
          "colspan": 3
        },
        {
          "label": "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
          "colspan": 8
        },
        {
          "label": "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
          "rowspan": 2
        },
        {
          "label": "No.ASIGNATURAS QUE DIERON NIVELACIÓN ACADÉMICA",
          "rowspan": 2
        },
        {
          "label": "CANTIDAD ESTUDIANTES QUE ASISTIERON",
          "colspan": 3
        },
        {
          "label": "% ATENCIÓN",
          "rowspan": 2
        }
      ],
      [
        {
          "label": "H"
        },
        {
          "label": "M"
        },
        {
          "label": "T"
        },
        {
          "label": "A"
        },
        {
          "label": "B"
        },
        {
          "label": "C"
        },
        {
          "label": "D"
        },
        {
          "label": "E"
        },
        {
          "label": "F"
        },
        {
          "label": "G"
        },
        {
          "label": "H"
        },
        {
          "label": "H"
        },
        {
          "label": "M"
        },
        {
          "label": "T"
        }
      ]
    ],
    "columns": [
      {
        "key": "plantel",
        "label": "PLANTEL",
        "type": "readonly"
      },
      {
        "key": "grado",
        "label": "GRADO",
        "type": "text"
      },
      {
        "key": "matricula_h",
        "label": "H",
        "type": "number"
      },
      {
        "key": "matricula_m",
        "label": "M",
        "type": "number"
      },
      {
        "key": "matricula_t",
        "label": "T",
        "type": "number"
      },
      {
        "key": "no_estudiantes_en_ordinario_por_grupo_se_contabi",
        "label": "A",
        "type": "number"
      },
      {
        "key": "no_estudiantes_en_ordinario_por_grupo_se_contabi_2",
        "label": "B",
        "type": "number"
      },
      {
        "key": "no_estudiantes_en_ordinario_por_grupo_se_contabi_3",
        "label": "C",
        "type": "number"
      },
      {
        "key": "no_estudiantes_en_ordinario_por_grupo_se_contabi_4",
        "label": "D",
        "type": "number"
      },
      {
        "key": "no_estudiantes_en_ordinario_por_grupo_se_contabi_5",
        "label": "E",
        "type": "number"
      },
      {
        "key": "no_estudiantes_en_ordinario_por_grupo_se_contabi_6",
        "label": "F",
        "type": "number"
      },
      {
        "key": "no_estudiantes_en_ordinario_por_grupo_se_contabi_7",
        "label": "G",
        "type": "number"
      },
      {
        "key": "no_estudiantes_en_ordinario_por_grupo_se_contabi_8",
        "label": "H",
        "type": "number"
      },
      {
        "key": "no_asignaturas_con_alumnos_en_ordinario",
        "label": "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
        "type": "number"
      },
      {
        "key": "no_asignaturas_que_dieron_nivelacion_academica",
        "label": "No.ASIGNATURAS QUE DIERON NIVELACIÓN ACADÉMICA",
        "type": "text"
      },
      {
        "key": "cantidad_estudiantes_que_asistieron_h",
        "label": "H",
        "type": "number"
      },
      {
        "key": "cantidad_estudiantes_que_asistieron_m",
        "label": "M",
        "type": "number"
      },
      {
        "key": "cantidad_estudiantes_que_asistieron_t",
        "label": "T",
        "type": "number"
      },
      {
        "key": "atencion",
        "label": "% ATENCIÓN",
        "type": "calculated",
        "calculation": {
          "type": "percentage",
          "numeratorKey": "cantidad_estudiantes_que_asistieron_t",
          "denominatorKey": "matricula_t",
          "decimals": 2
        }
      }
    ],
    "initialRows": [
      {
        "plantel": "",
        "grado": "1°",
        "matricula_h": 0.0,
        "matricula_m": 0.0,
        "matricula_t": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_2": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_3": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_4": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_5": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_6": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_7": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_8": "",
        "no_asignaturas_con_alumnos_en_ordinario": "",
        "no_asignaturas_que_dieron_nivelacion_academica": "",
        "cantidad_estudiantes_que_asistieron_h": 0.0,
        "cantidad_estudiantes_que_asistieron_m": 0.0,
        "cantidad_estudiantes_que_asistieron_t": "",
        "atencion": ""
      },
      {
        "plantel": "",
        "grado": "3°",
        "matricula_h": 0.0,
        "matricula_m": 0.0,
        "matricula_t": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_2": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_3": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_4": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_5": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_6": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_7": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_8": "",
        "no_asignaturas_con_alumnos_en_ordinario": "",
        "no_asignaturas_que_dieron_nivelacion_academica": "",
        "cantidad_estudiantes_que_asistieron_h": 0.0,
        "cantidad_estudiantes_que_asistieron_m": 0.0,
        "cantidad_estudiantes_que_asistieron_t": "",
        "atencion": ""
      },
      {
        "plantel": "",
        "grado": "5°",
        "matricula_h": 0.0,
        "matricula_m": 0.0,
        "matricula_t": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_2": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_3": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_4": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_5": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_6": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_7": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_8": "",
        "no_asignaturas_con_alumnos_en_ordinario": "",
        "no_asignaturas_que_dieron_nivelacion_academica": "",
        "cantidad_estudiantes_que_asistieron_h": 0.0,
        "cantidad_estudiantes_que_asistieron_m": 0.0,
        "cantidad_estudiantes_que_asistieron_t": "",
        "atencion": ""
      },
      {
        "plantel": "SEMIESCOLARIZADO",
        "grado": "",
        "matricula_h": "",
        "matricula_m": "",
        "matricula_t": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_2": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_3": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_4": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_5": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_6": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_7": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_8": "",
        "no_asignaturas_con_alumnos_en_ordinario": "",
        "no_asignaturas_que_dieron_nivelacion_academica": "",
        "cantidad_estudiantes_que_asistieron_h": "",
        "cantidad_estudiantes_que_asistieron_m": "",
        "cantidad_estudiantes_que_asistieron_t": "",
        "atencion": ""
      },
      {
        "plantel": "PLANTEL",
        "grado": "GRADO",
        "matricula_h": "",
        "matricula_m": "",
        "matricula_t": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_2": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_3": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_4": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_5": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_6": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_7": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_8": "",
        "no_asignaturas_con_alumnos_en_ordinario": "",
        "no_asignaturas_que_dieron_nivelacion_academica": "No.ASIGNATURAS QUE DIERON NIVELACIÓN ACADÉMICA",
        "cantidad_estudiantes_que_asistieron_h": "",
        "cantidad_estudiantes_que_asistieron_m": "",
        "cantidad_estudiantes_que_asistieron_t": "",
        "atencion": ""
      },
      {
        "plantel": "",
        "grado": "1°",
        "matricula_h": 0.0,
        "matricula_m": 0.0,
        "matricula_t": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_2": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_3": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_4": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_5": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_6": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_7": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_8": "",
        "no_asignaturas_con_alumnos_en_ordinario": "",
        "no_asignaturas_que_dieron_nivelacion_academica": "",
        "cantidad_estudiantes_que_asistieron_h": 0.0,
        "cantidad_estudiantes_que_asistieron_m": 0.0,
        "cantidad_estudiantes_que_asistieron_t": "",
        "atencion": ""
      },
      {
        "plantel": "",
        "grado": "3°",
        "matricula_h": 0.0,
        "matricula_m": 0.0,
        "matricula_t": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_2": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_3": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_4": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_5": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_6": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_7": "",
        "no_estudiantes_en_ordinario_por_grupo_se_contabi_8": "",
        "no_asignaturas_con_alumnos_en_ordinario": "",
        "no_asignaturas_que_dieron_nivelacion_academica": "",
        "cantidad_estudiantes_que_asistieron_h": 0.0,
        "cantidad_estudiantes_que_asistieron_m": 0.0,
        "cantidad_estudiantes_que_asistieron_t": "",
        "atencion": ""
      }
    ],
    "showTotals": true,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "plantel": "",
      "grado": "",
      "matricula_h": "",
      "matricula_m": "",
      "matricula_t": "",
      "no_estudiantes_en_ordinario_por_grupo_se_contabi": "",
      "no_estudiantes_en_ordinario_por_grupo_se_contabi_2": "",
      "no_estudiantes_en_ordinario_por_grupo_se_contabi_3": "",
      "no_estudiantes_en_ordinario_por_grupo_se_contabi_4": "",
      "no_estudiantes_en_ordinario_por_grupo_se_contabi_5": "",
      "no_estudiantes_en_ordinario_por_grupo_se_contabi_6": "",
      "no_estudiantes_en_ordinario_por_grupo_se_contabi_7": "",
      "no_estudiantes_en_ordinario_por_grupo_se_contabi_8": "",
      "no_asignaturas_con_alumnos_en_ordinario": "",
      "no_asignaturas_que_dieron_nivelacion_academica": "",
      "cantidad_estudiantes_que_asistieron_h": "",
      "cantidad_estudiantes_que_asistieron_m": "",
      "cantidad_estudiantes_que_asistieron_t": ""
    },
    "footerNote": "",
    "quality": []
  },
  "1.1.2.2.10": {
    "indicatorCode": "1.1.2.2.10",
    "officialCode": "1.1.2.2.10",
    "indicatorName": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de sostenibilidad y medio ambiente para la acción climática",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "Plantel",
          "rowspan": 2
        },
        {
          "label": "Nombre de la actividad",
          "rowspan": 2
        },
        {
          "label": "Descripción de la actividad",
          "rowspan": 2
        },
        {
          "label": "TOTAL ESTUDIANTES",
          "colspan": 2
        },
        {
          "label": "TOTAL DOCENTES",
          "colspan": 2
        },
        {
          "label": "TOTAL PERSONAL ADMINISTRATIVO",
          "colspan": 2
        },
        {
          "label": "TOTAL DE PARTICIPANTES",
          "rowspan": 2
        }
      ],
      [
        {
          "label": "MUJERES"
        },
        {
          "label": "HOMBRES"
        },
        {
          "label": "MUJERES"
        },
        {
          "label": "HOMBRES"
        },
        {
          "label": "MUJERES"
        },
        {
          "label": "HOMBRES"
        }
      ]
    ],
    "columns": [
      {
        "key": "plantel",
        "label": "Plantel",
        "type": "readonly"
      },
      {
        "key": "nombre_de_la_actividad",
        "label": "Nombre de la actividad",
        "type": "text"
      },
      {
        "key": "descripcion_de_la_actividad",
        "label": "Descripción de la actividad",
        "type": "text"
      },
      {
        "key": "total_estudiantes_mujeres",
        "label": "Total Estudiantes Mujeres",
        "type": "number"
      },
      {
        "key": "total_estudiantes_hombres",
        "label": "Total Estudiantes Hombres",
        "type": "number"
      },
      {
        "key": "total_docentes_mujeres",
        "label": "Total Docentes Mujeres",
        "type": "number"
      },
      {
        "key": "total_docentes_hombres",
        "label": "Total Docentes Hombres",
        "type": "number"
      },
      {
        "key": "total_personal_administrativo_mujeres",
        "label": "Total Personal Administrativo Mujeres",
        "type": "number"
      },
      {
        "key": "total_personal_administrativo_hombres",
        "label": "Total Personal Administrativo Hombres",
        "type": "number"
      },
      {
        "key": "total_de_participantes",
        "label": "TOTAL DE PARTICIPANTES",
        "type": "number"
      }
    ],
    "initialRows": [
      {
        "plantel": "Bachillerato",
        "nombre_de_la_actividad": "",
        "descripcion_de_la_actividad": "",
        "total_estudiantes_mujeres": "",
        "total_estudiantes_hombres": "",
        "total_docentes_mujeres": "",
        "total_docentes_hombres": "",
        "total_personal_administrativo_mujeres": "",
        "total_personal_administrativo_hombres": "",
        "total_de_participantes": ""
      }
    ],
    "showTotals": true,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "plantel": "",
      "nombre_de_la_actividad": "",
      "descripcion_de_la_actividad": "",
      "total_estudiantes_mujeres": "",
      "total_estudiantes_hombres": "",
      "total_docentes_mujeres": "",
      "total_docentes_hombres": "",
      "total_personal_administrativo_mujeres": "",
      "total_personal_administrativo_hombres": "",
      "total_de_participantes": ""
    },
    "footerNote": "",
    "quality": []
  },
  "1.1.2.2.11": {
    "indicatorCode": "1.1.2.2.11",
    "officialCode": "1.1.2.2.11",
    "indicatorName": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de igualdad de género",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "Plantel",
          "rowspan": 2
        },
        {
          "label": "Nombre de la capacitación y /o actividades formativas",
          "rowspan": 2
        },
        {
          "label": "TOTAL ESTUDIANTES",
          "colspan": 2
        },
        {
          "label": "TOTAL DOCENTES",
          "colspan": 2
        },
        {
          "label": "TOTAL PERSONAL ADMINISTRATIVO",
          "colspan": 2
        },
        {
          "label": "TEMAS QUE SE ABORDARON",
          "rowspan": 2
        }
      ],
      [
        {
          "label": "MUJERES"
        },
        {
          "label": "HOMBRES"
        },
        {
          "label": "MUJERES"
        },
        {
          "label": "HOMBRES"
        },
        {
          "label": "MUJERES"
        },
        {
          "label": "HOMBRES"
        }
      ]
    ],
    "columns": [
      {
        "key": "plantel",
        "label": "Plantel",
        "type": "readonly"
      },
      {
        "key": "nombre_de_la_capacitacion_y_o_actividades_format",
        "label": "Nombre de la capacitación y /o actividades formativas",
        "type": "text"
      },
      {
        "key": "total_estudiantes_mujeres",
        "label": "Total Estudiantes Mujeres",
        "type": "number"
      },
      {
        "key": "total_estudiantes_hombres",
        "label": "Total Estudiantes Hombres",
        "type": "number"
      },
      {
        "key": "total_docentes_mujeres",
        "label": "Total Docentes Mujeres",
        "type": "number"
      },
      {
        "key": "total_docentes_hombres",
        "label": "Total Docentes Hombres",
        "type": "number"
      },
      {
        "key": "total_personal_administrativo_mujeres",
        "label": "Total Personal Administrativo Mujeres",
        "type": "number"
      },
      {
        "key": "total_personal_administrativo_hombres",
        "label": "Total Personal Administrativo Hombres",
        "type": "number"
      },
      {
        "key": "temas_que_se_abordaron",
        "label": "TEMAS QUE SE ABORDARON",
        "type": "text"
      }
    ],
    "initialRows": [
      {
        "plantel": "Bachillerato",
        "nombre_de_la_capacitacion_y_o_actividades_format": "",
        "total_estudiantes_mujeres": "",
        "total_estudiantes_hombres": "",
        "total_docentes_mujeres": "",
        "total_docentes_hombres": "",
        "total_personal_administrativo_mujeres": "",
        "total_personal_administrativo_hombres": "",
        "temas_que_se_abordaron": ""
      }
    ],
    "showTotals": true,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "plantel": "",
      "nombre_de_la_capacitacion_y_o_actividades_format": "",
      "total_estudiantes_mujeres": "",
      "total_estudiantes_hombres": "",
      "total_docentes_mujeres": "",
      "total_docentes_hombres": "",
      "total_personal_administrativo_mujeres": "",
      "total_personal_administrativo_hombres": "",
      "temas_que_se_abordaron": ""
    },
    "footerNote": "",
    "quality": []
  },
  "1.1.2.3.1": {
    "indicatorCode": "1.1.2.3.1",
    "officialCode": "1.1.2.3.1",
    "indicatorName": "PORCENTAJE DE ESTUDIANTES DE MEDIA SUPERIOR QUE PARTICIPAN EN ACTIVIDADES DE FORMACIÓN INTEGRAL",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "Registro",
          "rowspan": 2
        },
        {
          "label": "Nombre de la charla",
          "rowspan": 2
        },
        {
          "label": "Ponente",
          "rowspan": 2
        },
        {
          "label": "Fecha de la actividad",
          "rowspan": 2
        },
        {
          "label": "Total estudiantes asistentes",
          "colspan": 2
        },
        {
          "label": "Total docentes asistentes",
          "colspan": 2
        }
      ],
      [
        {
          "label": "Mujeres"
        },
        {
          "label": "Hombres"
        },
        {
          "label": "Mujeres"
        },
        {
          "label": "Hombres"
        }
      ]
    ],
    "columns": [
      {
        "key": "registro",
        "label": "Registro",
        "type": "text"
      },
      {
        "key": "nombre_de_la_charla",
        "label": "Nombre de la charla",
        "type": "text"
      },
      {
        "key": "ponente",
        "label": "Ponente",
        "type": "text"
      },
      {
        "key": "fecha_de_la_actividad",
        "label": "Fecha de la actividad",
        "type": "text"
      },
      {
        "key": "total_estudiantes_asistentes_mujeres",
        "label": "Total Estudiantes Asistentes Mujeres",
        "type": "number"
      },
      {
        "key": "total_estudiantes_asistentes_hombres",
        "label": "Total Estudiantes Asistentes Hombres",
        "type": "number"
      },
      {
        "key": "total_docentes_asistentes_mujeres",
        "label": "Total Docentes Asistentes Mujeres",
        "type": "number"
      },
      {
        "key": "total_docentes_asistentes_hombres",
        "label": "Total Docentes Asistentes Hombres",
        "type": "number"
      }
    ],
    "initialRows": [
      {
        "registro": "",
        "nombre_de_la_charla": "",
        "ponente": "",
        "fecha_de_la_actividad": "",
        "total_estudiantes_asistentes_mujeres": "",
        "total_estudiantes_asistentes_hombres": "",
        "total_docentes_asistentes_mujeres": "",
        "total_docentes_asistentes_hombres": ""
      }
    ],
    "showTotals": true,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "registro": "",
      "nombre_de_la_charla": "",
      "ponente": "",
      "fecha_de_la_actividad": "",
      "total_estudiantes_asistentes_mujeres": "",
      "total_estudiantes_asistentes_hombres": "",
      "total_docentes_asistentes_mujeres": "",
      "total_docentes_asistentes_hombres": ""
    },
    "footerNote": "",
    "quality": []
  },
  "1.1.2.5.10": {
    "indicatorCode": "1.1.2.5.10",
    "officialCode": "1.1.2.5.10",
    "indicatorName": "Porcentaje de docentes de educación media superior y superior certificados en el dominio de una Lengua Extranjera",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [],
    "columns": [
      {
        "key": "agosto_2025_enero_2026",
        "label": "Agosto 2025-Enero 2026",
        "type": "text"
      },
      {
        "key": "agosto_2025_enero_2026_2",
        "label": "Agosto 2025-Enero 2026",
        "type": "text"
      },
      {
        "key": "total",
        "label": "Total",
        "type": "number"
      },
      {
        "key": "enero_2026_junio_2026",
        "label": "Enero 2026-Junio 2026",
        "type": "text"
      },
      {
        "key": "enero_2026_junio_2026_2",
        "label": "Enero 2026-Junio 2026",
        "type": "text"
      },
      {
        "key": "total_2",
        "label": "Total",
        "type": "number"
      },
      {
        "key": "agosto_2026_enero_2027",
        "label": "Agosto 2026- Enero 2027",
        "type": "text"
      },
      {
        "key": "agosto_2026_enero_2027_2",
        "label": "Agosto 2026- Enero 2027",
        "type": "text"
      },
      {
        "key": "total_3",
        "label": "Total",
        "type": "number"
      }
    ],
    "initialRows": [
      {
        "agosto_2025_enero_2026": "",
        "agosto_2025_enero_2026_2": "",
        "total": "",
        "enero_2026_junio_2026": "",
        "enero_2026_junio_2026_2": "",
        "total_2": "",
        "agosto_2026_enero_2027": "",
        "agosto_2026_enero_2027_2": "",
        "total_3": ""
      }
    ],
    "showTotals": true,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "agosto_2025_enero_2026": "",
      "agosto_2025_enero_2026_2": "",
      "total": "",
      "enero_2026_junio_2026": "",
      "enero_2026_junio_2026_2": "",
      "total_2": "",
      "agosto_2026_enero_2027": "",
      "agosto_2026_enero_2027_2": "",
      "total_3": ""
    },
    "footerNote": "",
    "quality": []
  },
  "1.1.2.5.3": {
    "indicatorCode": "1.1.2.5.3",
    "officialCode": "1.1.2.5.3",
    "indicatorName": "Porcentaje de PTC de educación media superior beneficiados en el programa de ESDEPED",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "PLANTEL"
        },
        {
          "label": "PTC"
        },
        {
          "label": "NOMBRE DEL DOCENTE"
        },
        {
          "label": "NIVEL"
        }
      ]
    ],
    "columns": [
      {
        "key": "plantel",
        "label": "PLANTEL",
        "type": "readonly"
      },
      {
        "key": "ptc",
        "label": "PTC",
        "type": "text"
      },
      {
        "key": "nombre_del_docente",
        "label": "NOMBRE DEL DOCENTE",
        "type": "text"
      },
      {
        "key": "nivel",
        "label": "NIVEL",
        "type": "text"
      }
    ],
    "initialRows": [
      {
        "plantel": "",
        "ptc": "",
        "nombre_del_docente": "",
        "nivel": ""
      }
    ],
    "showTotals": false,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "plantel": "",
      "ptc": "",
      "nombre_del_docente": "",
      "nivel": ""
    },
    "footerNote": "",
    "quality": []
  },
  "2.1.4.1.2": {
    "indicatorCode": "2.1.4.1.2",
    "officialCode": "2.1.4.1.2",
    "indicatorName": "Número de estudiantes que colaboran en proyectos de investigación liderados por profesorado de tiempo completo",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "PLANTEL",
          "rowspan": 2
        },
        {
          "label": "Nombre de /los proyectos de investigación",
          "rowspan": 2
        },
        {
          "label": "Número de estudiantes",
          "colspan": 2
        },
        {
          "label": "Observaciones (indicar el periodo del proyecto)",
          "rowspan": 2
        }
      ],
      [
        {
          "label": "Mujeres"
        },
        {
          "label": "Hombres"
        }
      ]
    ],
    "columns": [
      {
        "key": "plantel",
        "label": "PLANTEL",
        "type": "readonly"
      },
      {
        "key": "nombre_de_los_proyectos_de_investigacion",
        "label": "Nombre de /los proyectos de investigación",
        "type": "text"
      },
      {
        "key": "numero_de_estudiantes_mujeres",
        "label": "Mujeres",
        "type": "number"
      },
      {
        "key": "numero_de_estudiantes_hombres",
        "label": "Hombres",
        "type": "number"
      },
      {
        "key": "observaciones_indicar_el_periodo_del_proyecto",
        "label": "Observaciones (indicar el periodo del proyecto)",
        "type": "text"
      }
    ],
    "initialRows": [
      {
        "plantel": "Bachillerato 15",
        "nombre_de_los_proyectos_de_investigacion": "",
        "numero_de_estudiantes_mujeres": "",
        "numero_de_estudiantes_hombres": "",
        "observaciones_indicar_el_periodo_del_proyecto": ""
      }
    ],
    "showTotals": true,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "plantel": "",
      "nombre_de_los_proyectos_de_investigacion": "",
      "numero_de_estudiantes_mujeres": "",
      "numero_de_estudiantes_hombres": "",
      "observaciones_indicar_el_periodo_del_proyecto": ""
    },
    "footerNote": "",
    "quality": []
  },
  "3.1.0.0.1": {
    "indicatorCode": "3.1.0.0.1",
    "officialCode": "3.1.0.0.1",
    "indicatorName": "Número de programas y proyectos de extensión y vinculación dirigidas al sector social y productivo",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "Plantel",
          "rowspan": 2
        },
        {
          "label": "Nombre de la actividad",
          "rowspan": 2
        },
        {
          "label": "Descripción de la actividad",
          "rowspan": 2
        },
        {
          "label": "TOTAL ESTUDIANTES",
          "colspan": 2
        },
        {
          "label": "TOTAL DOCENTES",
          "colspan": 2
        },
        {
          "label": "TOTAL PERSONAL ADMINISTRATIVO",
          "colspan": 2
        },
        {
          "label": "TOTAL DE PARTICIPANTES",
          "rowspan": 2
        }
      ],
      [
        {
          "label": "MUJERES"
        },
        {
          "label": "HOMBRES"
        },
        {
          "label": "MUJERES"
        },
        {
          "label": "HOMBRES"
        },
        {
          "label": "MUJERES"
        },
        {
          "label": "HOMBRES"
        }
      ]
    ],
    "columns": [
      {
        "key": "plantel",
        "label": "Plantel",
        "type": "readonly"
      },
      {
        "key": "nombre_de_la_actividad",
        "label": "Nombre de la actividad",
        "type": "text"
      },
      {
        "key": "descripcion_de_la_actividad",
        "label": "Descripción de la actividad",
        "type": "text"
      },
      {
        "key": "total_estudiantes_mujeres",
        "label": "Total Estudiantes Mujeres",
        "type": "number"
      },
      {
        "key": "total_estudiantes_hombres",
        "label": "Total Estudiantes Hombres",
        "type": "number"
      },
      {
        "key": "total_docentes_mujeres",
        "label": "Total Docentes Mujeres",
        "type": "number"
      },
      {
        "key": "total_docentes_hombres",
        "label": "Total Docentes Hombres",
        "type": "number"
      },
      {
        "key": "total_personal_administrativo_mujeres",
        "label": "Total Personal Administrativo Mujeres",
        "type": "number"
      },
      {
        "key": "total_personal_administrativo_hombres",
        "label": "Total Personal Administrativo Hombres",
        "type": "number"
      },
      {
        "key": "total_de_participantes",
        "label": "TOTAL DE PARTICIPANTES",
        "type": "number"
      }
    ],
    "initialRows": [
      {
        "plantel": "Bachillerato",
        "nombre_de_la_actividad": "",
        "descripcion_de_la_actividad": "",
        "total_estudiantes_mujeres": "",
        "total_estudiantes_hombres": "",
        "total_docentes_mujeres": "",
        "total_docentes_hombres": "",
        "total_personal_administrativo_mujeres": "",
        "total_personal_administrativo_hombres": "",
        "total_de_participantes": ""
      }
    ],
    "showTotals": true,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "plantel": "",
      "nombre_de_la_actividad": "",
      "descripcion_de_la_actividad": "",
      "total_estudiantes_mujeres": "",
      "total_estudiantes_hombres": "",
      "total_docentes_mujeres": "",
      "total_docentes_hombres": "",
      "total_personal_administrativo_mujeres": "",
      "total_personal_administrativo_hombres": "",
      "total_de_participantes": ""
    },
    "footerNote": "",
    "quality": []
  },
  "3.1.1.3.6": {
    "indicatorCode": "3.1.1.3.6",
    "officialCode": "3.1.1.3.6",
    "indicatorName": "Número de participantes en actividades de sostenibilidad y medio ambiente convocadas por el SIGA",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "Plantel",
          "rowspan": 2
        },
        {
          "label": "Nombre de la actividad",
          "rowspan": 2
        },
        {
          "label": "Descripción de la actividad",
          "rowspan": 2
        },
        {
          "label": "TOTAL ESTUDIANTES",
          "colspan": 2
        },
        {
          "label": "TOTAL DOCENTES",
          "colspan": 2
        },
        {
          "label": "TOTAL PERSONAL ADMINISTRATIVO",
          "colspan": 2
        },
        {
          "label": "TOTAL DE PARTICIPANTES",
          "rowspan": 2
        }
      ],
      [
        {
          "label": "MUJERES"
        },
        {
          "label": "HOMBRES"
        },
        {
          "label": "MUJERES"
        },
        {
          "label": "HOMBRES"
        },
        {
          "label": "MUJERES"
        },
        {
          "label": "HOMBRES"
        }
      ]
    ],
    "columns": [
      {
        "key": "plantel",
        "label": "Plantel",
        "type": "readonly"
      },
      {
        "key": "nombre_de_la_actividad",
        "label": "Nombre de la actividad",
        "type": "text"
      },
      {
        "key": "descripcion_de_la_actividad",
        "label": "Descripción de la actividad",
        "type": "text"
      },
      {
        "key": "total_estudiantes_mujeres",
        "label": "Total Estudiantes Mujeres",
        "type": "number"
      },
      {
        "key": "total_estudiantes_hombres",
        "label": "Total Estudiantes Hombres",
        "type": "number"
      },
      {
        "key": "total_docentes_mujeres",
        "label": "Total Docentes Mujeres",
        "type": "number"
      },
      {
        "key": "total_docentes_hombres",
        "label": "Total Docentes Hombres",
        "type": "number"
      },
      {
        "key": "total_personal_administrativo_mujeres",
        "label": "Total Personal Administrativo Mujeres",
        "type": "number"
      },
      {
        "key": "total_personal_administrativo_hombres",
        "label": "Total Personal Administrativo Hombres",
        "type": "number"
      },
      {
        "key": "total_de_participantes",
        "label": "TOTAL DE PARTICIPANTES",
        "type": "number"
      }
    ],
    "initialRows": [
      {
        "plantel": "Bachillerato",
        "nombre_de_la_actividad": "",
        "descripcion_de_la_actividad": "",
        "total_estudiantes_mujeres": "",
        "total_estudiantes_hombres": "",
        "total_docentes_mujeres": "",
        "total_docentes_hombres": "",
        "total_personal_administrativo_mujeres": "",
        "total_personal_administrativo_hombres": "",
        "total_de_participantes": ""
      }
    ],
    "showTotals": true,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "plantel": "",
      "nombre_de_la_actividad": "",
      "descripcion_de_la_actividad": "",
      "total_estudiantes_mujeres": "",
      "total_estudiantes_hombres": "",
      "total_docentes_mujeres": "",
      "total_docentes_hombres": "",
      "total_personal_administrativo_mujeres": "",
      "total_personal_administrativo_hombres": "",
      "total_de_participantes": ""
    },
    "footerNote": "",
    "quality": []
  },
  "4.1.1.0.1": {
    "indicatorCode": "4.1.1.0.1",
    "officialCode": "4.1.1.0.1",
    "indicatorName": "Número de Sistemas de Información Institucionales que interoperan",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "Registro"
        },
        {
          "label": "Nombre del Software"
        },
        {
          "label": "Aspecto de la formación integral del estudiantado a la que da seguimiento"
        }
      ]
    ],
    "columns": [
      {
        "key": "registro",
        "label": "Registro",
        "type": "text"
      },
      {
        "key": "nombre_del_software",
        "label": "Nombre del Software",
        "type": "text"
      },
      {
        "key": "aspecto_de_la_formacion_integral_del_estudiantad",
        "label": "Aspecto de la formación integral del estudiantado a la que da seguimiento",
        "type": "text"
      }
    ],
    "initialRows": [
      {
        "registro": "",
        "nombre_del_software": "",
        "aspecto_de_la_formacion_integral_del_estudiantad": ""
      }
    ],
    "showTotals": false,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "registro": "",
      "nombre_del_software": "",
      "aspecto_de_la_formacion_integral_del_estudiantad": ""
    },
    "footerNote": "",
    "quality": []
  },
  "4.1.1.1.1": {
    "indicatorCode": "4.1.1.1.1",
    "officialCode": "4.1.1.1.1",
    "indicatorName": "Número de sistemas implementados y mejorados para fortalecer la gestión de procesos institucionales",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "Registro"
        },
        {
          "label": "Fecha"
        },
        {
          "label": "Versión"
        },
        {
          "label": "Respnsable"
        },
        {
          "label": "Descripción breve del cambio"
        },
        {
          "label": "Autorizo"
        },
        {
          "label": "Observaciones"
        }
      ]
    ],
    "columns": [
      {
        "key": "registro",
        "label": "Registro",
        "type": "text"
      },
      {
        "key": "fecha",
        "label": "Fecha",
        "type": "text"
      },
      {
        "key": "version",
        "label": "Versión",
        "type": "text"
      },
      {
        "key": "respnsable",
        "label": "Respnsable",
        "type": "text"
      },
      {
        "key": "descripcion_breve_del_cambio",
        "label": "Descripción breve del cambio",
        "type": "text"
      },
      {
        "key": "autorizo",
        "label": "Autorizo",
        "type": "text"
      },
      {
        "key": "observaciones",
        "label": "Observaciones",
        "type": "text"
      }
    ],
    "initialRows": [
      {
        "registro": "",
        "fecha": "",
        "version": "",
        "respnsable": "",
        "descripcion_breve_del_cambio": "",
        "autorizo": "",
        "observaciones": ""
      }
    ],
    "showTotals": false,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "registro": "",
      "fecha": "",
      "version": "",
      "respnsable": "",
      "descripcion_breve_del_cambio": "",
      "autorizo": "",
      "observaciones": ""
    },
    "footerNote": "",
    "quality": []
  },
  "4.1.2.2.1": {
    "indicatorCode": "4.1.2.2.1",
    "officialCode": "4.1.2.2.1",
    "indicatorName": "Porcentaje de UO que realizan acciones de actualización, mantenimiento preventivo y/o correctivo a la infraestructura tecnológica",
    "activityLabel": "",
    "sourceLabel": "Development fallback",
    "sourcePath": "",
    "sheetName": "",
    "groups": [],
    "headerRows": [
      [
        {
          "label": "Registro"
        },
        {
          "label": "Dependencia / Área"
        },
        {
          "label": "Responsable"
        },
        {
          "label": "Actividad"
        },
        {
          "label": "Descripción"
        },
        {
          "label": "Fecha"
        },
        {
          "label": "Estatus"
        },
        {
          "label": "Total de Equipos"
        },
        {
          "label": "Equipos Atendidos"
        },
        {
          "label": "% de equipos atendidos"
        },
        {
          "label": "Observaciones"
        }
      ]
    ],
    "columns": [
      {
        "key": "registro",
        "label": "Registro",
        "type": "text"
      },
      {
        "key": "dependencia_area",
        "label": "Dependencia / Área",
        "type": "text"
      },
      {
        "key": "responsable",
        "label": "Responsable",
        "type": "text"
      },
      {
        "key": "actividad",
        "label": "Actividad",
        "type": "text"
      },
      {
        "key": "descripcion",
        "label": "Descripción",
        "type": "text"
      },
      {
        "key": "fecha",
        "label": "Fecha",
        "type": "text"
      },
      {
        "key": "estatus",
        "label": "Estatus",
        "type": "text"
      },
      {
        "key": "total_de_equipos",
        "label": "Total de Equipos",
        "type": "number"
      },
      {
        "key": "equipos_atendidos",
        "label": "Equipos Atendidos",
        "type": "text"
      },
      {
        "key": "de_equipos_atendidos",
        "label": "% de equipos atendidos",
        "type": "text"
      },
      {
        "key": "observaciones",
        "label": "Observaciones",
        "type": "text"
      }
    ],
    "initialRows": [
      {
        "registro": "",
        "dependencia_area": "",
        "responsable": "",
        "actividad": "Actividad",
        "descripcion": "Descripción",
        "fecha": "",
        "estatus": "Estatus",
        "total_de_equipos": "",
        "equipos_atendidos": "",
        "de_equipos_atendidos": "",
        "observaciones": ""
      },
      {
        "registro": "",
        "dependencia_area": "",
        "responsable": "",
        "actividad": "Actualización de software",
        "descripcion": "Instalación de actualizaciones, parches y mejoras de seguridad",
        "fecha": "",
        "estatus": "Concluida",
        "total_de_equipos": "",
        "equipos_atendidos": "",
        "de_equipos_atendidos": "",
        "observaciones": ""
      },
      {
        "registro": "",
        "dependencia_area": "",
        "responsable": "",
        "actividad": "Mantenimiento preventivo",
        "descripcion": "Limpieza física, revisión y optimización de equipos",
        "fecha": "",
        "estatus": "Pendiente",
        "total_de_equipos": "",
        "equipos_atendidos": "",
        "de_equipos_atendidos": "",
        "observaciones": ""
      },
      {
        "registro": "",
        "dependencia_area": "",
        "responsable": "",
        "actividad": "Respaldo de información",
        "descripcion": "Ejecución y validación de respaldos institucionales",
        "fecha": "",
        "estatus": "",
        "total_de_equipos": "",
        "equipos_atendidos": "",
        "de_equipos_atendidos": "",
        "observaciones": ""
      },
      {
        "registro": "",
        "dependencia_area": "",
        "responsable": "",
        "actividad": "Optimización de red",
        "descripcion": "Validación y configuración de conectividad y rendimiento",
        "fecha": "",
        "estatus": "",
        "total_de_equipos": "",
        "equipos_atendidos": "",
        "de_equipos_atendidos": "",
        "observaciones": ""
      },
      {
        "registro": "",
        "dependencia_area": "",
        "responsable": "",
        "actividad": "Corrección de incidencias",
        "descripcion": "Atención y solución de fallas detectadas",
        "fecha": "",
        "estatus": "",
        "total_de_equipos": "",
        "equipos_atendidos": "",
        "de_equipos_atendidos": "",
        "observaciones": ""
      }
    ],
    "showTotals": true,
    "allowAddRows": true,
    "addRowLabel": "Agregar fila",
    "emptyRow": {
      "registro": "",
      "dependencia_area": "",
      "responsable": "",
      "actividad": "",
      "descripcion": "",
      "fecha": "",
      "estatus": "",
      "total_de_equipos": "",
      "equipos_atendidos": "",
      "de_equipos_atendidos": "",
      "observaciones": ""
    },
    "footerNote": "",
    "quality": []
  }
};

export const officialWorkbookSummaries: OfficialWorkbookSummary[] = [];
