// Generated by tools/import-official-data.py from Libro1.xlsx.
// Source binaries and row-level private data are intentionally not committed.

export type OfficialCatalogRow = {
  sourceRow: number;
  code: string;
  name: string;
  responsible: string;
  contributors: string;
  activity: string;
  dedupeKey: string;
  isDuplicate: boolean;
  duplicateOfSourceRow: number | null;
  dataQuality: string[];
};

export const officialCatalogStats = {
  "sourceRows": 106,
  "uniqueRows": 95,
  "duplicateRows": 11,
  "uniqueIndicators": 55,
  "uniqueResponsibles": 19,
  "uniqueContributors": 23,
  "uniqueActivities": 73,
  "blankActivities": 3,
  "workbookOnlyIndicators": 7
} as const;

export const officialIndicatorPlantelScopes: Record<string, number[]> = {
  "1.1.1.3.2": [
    1
  ],
  "1.1.1.3.3": [
    1
  ],
  "1.1.1.5.1": [
    1
  ],
  "1.1.1.5.2": [
    1
  ],
  "1.1.2.1.8": [
    1
  ],
  "1.1.3.0.3": [
    1
  ],
  "1.1.4.4.4": [
    1
  ]
};

export const officialCatalogRows: OfficialCatalogRow[] = [
  {
    "sourceRow": 2,
    "code": "1.1.0.0.1",
    "name": "Porcentaje de cobertura en educación media superior.",
    "responsible": "Liliana Yunuen Rojas Maciel",
    "contributors": "Liliana Yunuen Rojas Maciel",
    "activity": "Indicadores educativos",
    "dedupeKey": "1439f54b9437c27b",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 3,
    "code": "1.1.1.0.1",
    "name": "Porcentaje de aceptación en educación media superior.",
    "responsible": "Liliana Yunuen Rojas Maciel",
    "contributors": "Liliana Yunuen Rojas Maciel",
    "activity": "Indicadores educativos",
    "dedupeKey": "2ffb05b1f0776eda",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 4,
    "code": "1.1.0.0.1",
    "name": "Porcentaje de cobertura en educación media superior.",
    "responsible": "Liliana Yunuen Rojas Maciel",
    "contributors": "Liliana Yunuen Rojas Maciel",
    "activity": "Reconocimento de estudios",
    "dedupeKey": "ad46273b01db6b56",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 5,
    "code": "1.1.1.1.1",
    "name": "Porcentaje de programas educativos de educación media superior nuevos, actualizados y reestructurados alineados al modelo educativo, incorporando formalmente el enfoque de sostenibilidad y medio ambiente, cultura de paz, igualdad de género, la transformación digital y la internacionalización",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Oscar Delgado Sánchez, Oscar Gustavo Mendoza Barajas, Ariadna Zúñiga Torres, Liliana Yunuen Rojas Maciel",
    "activity": "Diseño curricular",
    "dedupeKey": "712d46901976f365",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 6,
    "code": "1.1.1.1.1",
    "name": "Porcentaje de programas educativos de educación media superior nuevos, actualizados y reestructurados alineados al modelo educativo, incorporando formalmente el enfoque de sostenibilidad y medio ambiente, cultura de paz, igualdad de género, la transformación digital y la internacionalización",
    "responsible": "Adriana Ruiz Rivera",
    "contributors": "Adriana Ruiz Rivera",
    "activity": "Academias",
    "dedupeKey": "d407894e1eca47a2",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 7,
    "code": "1.1.0.0.1",
    "name": "Porcentaje de cobertura en educación media superior.",
    "responsible": "Daniela Nohemi Navarro Castillo",
    "contributors": "Daniela Nohemi Navarro Castillo",
    "activity": "Proceso de admisión",
    "dedupeKey": "f83770753ca1e060",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 8,
    "code": "1.1.1.0.1",
    "name": "Porcentaje de aceptación en educación media superior.",
    "responsible": "Daniela Nohemi Navarro Castillo",
    "contributors": "Daniela Nohemi Navarro Castillo",
    "activity": "Proceso de admisión",
    "dedupeKey": "e219c6ca7abedb06",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 9,
    "code": "1.1.1.1.1",
    "name": "Porcentaje de programas educativos de educación media superior nuevos, actualizados y reestructurados alineados al modelo educativo, incorporando formalmente el enfoque de sostenibilidad y medio ambiente, cultura de paz, igualdad de género, la transformación digital y la internacionalización",
    "responsible": "Adriana Ruiz Rivera",
    "contributors": "Adriana Ruiz Rivera",
    "activity": "Desarrollo curricular",
    "dedupeKey": "e97200f3c39e7863",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 10,
    "code": "1.1.1.1.1",
    "name": "Porcentaje de programas educativos de educación media superior nuevos, actualizados y reestructurados alineados al modelo educativo, incorporando formalmente el enfoque de sostenibilidad y medio ambiente, cultura de paz, igualdad de género, la transformación digital y la internacionalización",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Oscar Delgado Sánchez, Oscar Gustavo Mendoza Barajas, Ariadna Zúñiga Torres, Liliana Yunuen Rojas Maciel",
    "activity": "Diseño curricular",
    "dedupeKey": "712d46901976f365",
    "isDuplicate": true,
    "duplicateOfSourceRow": 5,
    "dataQuality": []
  },
  {
    "sourceRow": 11,
    "code": "1.1.1.1.1",
    "name": "Porcentaje de programas educativos de educación media superior nuevos, actualizados y reestructurados alineados al modelo educativo, incorporando formalmente el enfoque de sostenibilidad y medio ambiente, cultura de paz, igualdad de género, la transformación digital y la internacionalización",
    "responsible": "Adriana Ruiz Rivera",
    "contributors": "Adriana Ruiz Rivera",
    "activity": "Academias",
    "dedupeKey": "d407894e1eca47a2",
    "isDuplicate": true,
    "duplicateOfSourceRow": 6,
    "dataQuality": []
  },
  {
    "sourceRow": 12,
    "code": "1.1.0.0.1",
    "name": "Porcentaje de cobertura en educación media superior.",
    "responsible": "Carlos Hernández Nava",
    "contributors": "Carlos Hernández Nava",
    "activity": "Indicadores educativos incorporados",
    "dedupeKey": "695516ac64952ec0",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 13,
    "code": "1.1.1.0.1",
    "name": "Porcentaje de aceptación en educación media superior.",
    "responsible": "Daniela Nohemi Navarro Castillo",
    "contributors": "Daniela Nohemi Navarro Castillo",
    "activity": "Proceso de admisión",
    "dedupeKey": "e219c6ca7abedb06",
    "isDuplicate": true,
    "duplicateOfSourceRow": 8,
    "dataQuality": []
  },
  {
    "sourceRow": 14,
    "code": "1.1.1.0.1",
    "name": "Porcentaje de aceptación en educación media superior.",
    "responsible": "Armando Hernández Ramírez",
    "contributors": "Daniela Nohemi Navarro Castillo",
    "activity": "Proceso de admisión",
    "dedupeKey": "8f9fdd8db640c235",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 15,
    "code": "1.1.1.1.1",
    "name": "Porcentaje de programas educativos de educación media superior nuevos, actualizados y reestructurados alineados al modelo educativo, incorporando formalmente el enfoque de sostenibilidad y medio ambiente, cultura de paz, igualdad de género, la transformación digital y la internacionalización",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Oscar Delgado Sánchez, Oscar Gustavo Mendoza Barajas, Ariadna Zúñiga Torres, Liliana Yunuen Rojas Maciel",
    "activity": "Diseño curricular",
    "dedupeKey": "712d46901976f365",
    "isDuplicate": true,
    "duplicateOfSourceRow": 5,
    "dataQuality": []
  },
  {
    "sourceRow": 16,
    "code": "1.1.2.1.1",
    "name": "Porcentaje de estudiantes de educación media superior atendidos en el Programa Institucional de Tutoría y en el Programa de Orientación Educativa y Vocacional.",
    "responsible": "Arturo Gordillo Chávez",
    "contributors": "Arturo Gordillo Chávez",
    "activity": "Tutelaje y orientación educativa y vocacional",
    "dedupeKey": "e87995dce5b58edb",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 17,
    "code": "1.1.2.1.3",
    "name": "Porcentaje de estudiantes de educación media superior que sus padres, madres o tutores legales participan en acciones de orientación familiar.",
    "responsible": "Arturo Gordillo Chávez",
    "contributors": "Arturo Gordillo Chávez",
    "activity": "Tutelaje y orientación educativa y vocacional",
    "dedupeKey": "7e6eea86d0ab631b",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 18,
    "code": "1.1.2.1.4",
    "name": "Porcentaje de estudiantes de educación media superior y superior atendidos en los servicios de salud integral",
    "responsible": "Carlos Hernández Nava",
    "contributors": "Carlos Hernández Nava",
    "activity": "Promoción de la salud",
    "dedupeKey": "1c7aaaf6f142b2b3",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 19,
    "code": "1.1.2.1.4",
    "name": "Porcentaje de estudiantes de educación media superior y superior atendidos en los servicios de salud integral",
    "responsible": "Arturo Gordillo Chávez",
    "contributors": "Arturo Gordillo Chávez",
    "activity": "Clínica Universitaria de Atención Psicológica",
    "dedupeKey": "224ea0f9c7ef433b",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 20,
    "code": "1.1.2.1.4",
    "name": "Porcentaje de estudiantes de educación media superior y superior atendidos en los servicios de salud integral",
    "responsible": "Ariadna Zuñiga Torres",
    "contributors": "Ariadna Zuñiga Torres",
    "activity": "Número de servicios y acciones de Desarrollo Integral dirigidos al estudiantado",
    "dedupeKey": "cd3b82d604af9dc0",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 21,
    "code": "1.1.2.2.11",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de igualdad de género",
    "responsible": "Ariadna Zuñiga Torres",
    "contributors": "Ariadna Zuñiga Torres",
    "activity": "Actividades formativas de igualdad de género",
    "dedupeKey": "43738088e40a860a",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 22,
    "code": "1.1.2.0.3",
    "name": "Tasa de abandono escolar de educación media superior.",
    "responsible": "Liliana Yunuen Rojas Maciel",
    "contributors": "Liliana Yunuen Rojas Maciel, Daniela Nohemi Navarro Castillo",
    "activity": "Indicadores educativos, Estrategias para combatir el abandono escolar",
    "dedupeKey": "dcb7b80fb7cdd03f",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 23,
    "code": "1.1.2.2.1",
    "name": "Porcentaje de estudiantes de educación media superior atendidos en acciones de reforzamiento, asesoría y nivelación académica.",
    "responsible": "Salvador Aguilar Aguilar",
    "contributors": "Salvador Aguilar Aguilar",
    "activity": "Concursos de conocimientos",
    "dedupeKey": "b158086091e10615",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 24,
    "code": "1.1.2.2.1",
    "name": "Porcentaje de estudiantes de educación media superior atendidos en acciones de reforzamiento, asesoría y nivelación académica.",
    "responsible": "Marcial Aviña Iglesias",
    "contributors": "Marcial Aviña Iglesias",
    "activity": "",
    "dedupeKey": "6901dd91666589e7",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "blank_activity"
    ]
  },
  {
    "sourceRow": 25,
    "code": "1.1.2.2.9",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones para promover cambios positivos en la convivencia escolar.",
    "responsible": "Arturo Gordillo Chávez",
    "contributors": "Arturo Gordillo Chávez",
    "activity": "Comités de paz",
    "dedupeKey": "37ddc2c518a3d351",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 26,
    "code": "1.1.2.0.1",
    "name": "Porcentaje retención escolar de educación media superior",
    "responsible": "Liliana Yunuen Rojas Maciel",
    "contributors": "Liliana Yunuen Rojas Maciel",
    "activity": "Indicadores educativos, Estudios de trayectoria",
    "dedupeKey": "7efc0ad58d6c3fe6",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 27,
    "code": "1.0.0.0.1",
    "name": "Porcentaje de eficiencia terminal por cohorte de educación media superior.",
    "responsible": "Liliana Yunuen Rojas Maciel",
    "contributors": "Liliana Yunuen Rojas Maciel",
    "activity": "Indicadores educativos, Estudios de trayectoria",
    "dedupeKey": "7a7b6477709aae26",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 28,
    "code": "1.1.2.0.3",
    "name": "Tasa de abandono escolar de educación media superior.",
    "responsible": "Liliana Yunuen Rojas Maciel",
    "contributors": "Liliana Yunuen Rojas Maciel",
    "activity": "Indicadores educativos, Estudios de trayectoria",
    "dedupeKey": "49bec5deea4bfba6",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 29,
    "code": "1.1.2.2.5",
    "name": "Número de programas educativos de media superior y superior impartidos parcial o totalmente en una lengua extranjera.",
    "responsible": "Laura Gabriela Calvario",
    "contributors": "Laura Gabriela Calvario",
    "activity": "Programa de bachillerato bilingüe",
    "dedupeKey": "26335a374bdc4751",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 30,
    "code": "1.1.2.2.8",
    "name": "Porcentaje de estudiantes de educación media superior y licenciatura certificados en el dominio de una lengua extranjera.",
    "responsible": "Laura Gabriela Calvario",
    "contributors": "Laura Gabriela Calvario",
    "activity": "Estudiantes de educación media superior certificados en el dominio de una lengua extranjera",
    "dedupeKey": "3c95af7d107f9b24",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 31,
    "code": "1.1.2.2.10",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de sostenibilidad y medio ambiente para la acción climática.",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "Acciones de sostenibilidad y medio ambiente, Brigadas de limpieza comunitaria, Acciones SIGA y CEUGEA",
    "dedupeKey": "06c5024ab882ff60",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 32,
    "code": "1.1.2.2.10",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de sostenibilidad y medio ambiente para la acción climática.",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "Acciones de sostenibilidad y medio ambiente, Brigadas de limpieza comunitaria, Acciones SIGA y CEUGEA",
    "dedupeKey": "06c5024ab882ff60",
    "isDuplicate": true,
    "duplicateOfSourceRow": 31,
    "dataQuality": []
  },
  {
    "sourceRow": 33,
    "code": "1.1.2.2.10",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de sostenibilidad y medio ambiente para la acción climática.",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "ReforestAcción, Visitas Rancho el Peregrino, Acciones SIGA y CEUGEA",
    "dedupeKey": "7c950549c838440c",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 34,
    "code": "1.1.2.2.10",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de sostenibilidad y medio ambiente para la acción climática.",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "",
    "dedupeKey": "ea42a5cdffc678cb",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "blank_activity"
    ]
  },
  {
    "sourceRow": 35,
    "code": "1.1.2.2.10",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de sostenibilidad y medio ambiente para la acción climática.",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "Registro de la participación estudiantil en proyectos CEUGEA",
    "dedupeKey": "a4c58a265c1dbb86",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 36,
    "code": "1.1.2.2.10",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de sostenibilidad y medio ambiente para la acción climática.",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "Comités de vinculación",
    "dedupeKey": "488039a845a5bb6f",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 37,
    "code": "1.0.0.0.2",
    "name": "Porcentaje de titulación por cohorte de educación media superior",
    "responsible": "Adriana Ruiz Rivera",
    "contributors": "Adriana Ruiz Rivera",
    "activity": "Titulación",
    "dedupeKey": "c66f28c27025edb5",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 38,
    "code": "1.1.2.0.1",
    "name": "Porcentaje retención escolar de educación media superior",
    "responsible": "Daniela Nohemi Navarro Castillo",
    "contributors": "Daniela Nohemi Navarro Castillo",
    "activity": "Red de Apoyo académico en planteles",
    "dedupeKey": "1d2e892f6f252c62",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 39,
    "code": "1.1.2.0.1",
    "name": "Porcentaje retención escolar de educación media superior",
    "responsible": "Armando Hernández Ramírez",
    "contributors": "Armando Hernández Ramírez",
    "activity": "Evaluación de regularización en fecha extraordinaria",
    "dedupeKey": "80e466878c38ea35",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 40,
    "code": "1.1.2.2.1",
    "name": "Porcentaje de estudiantes de educación media superior atendidos en acciones de reforzamiento, asesoría y nivelación académica.",
    "responsible": "Marcial Aviña Iglesias",
    "contributors": "Marcial Aviña Iglesias",
    "activity": "Nivelación académica",
    "dedupeKey": "ecf824865854a6d2",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 41,
    "code": "1.1.2.2.1",
    "name": "Porcentaje de estudiantes de educación media superior atendidos en acciones de reforzamiento, asesoría y nivelación académica.",
    "responsible": "Marcial Aviña Iglesias",
    "contributors": "Marcial Aviña Iglesias",
    "activity": "Exámenes indicativos",
    "dedupeKey": "f0029f59906a720d",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 42,
    "code": "1.1.2.2.1",
    "name": "Porcentaje de estudiantes de educación media superior atendidos en acciones de reforzamiento, asesoría y nivelación académica.",
    "responsible": "Marcial Aviña Iglesias",
    "contributors": "Marcial Aviña Iglesias",
    "activity": "Programa de reforzamiento académico",
    "dedupeKey": "66d2ff3524abc310",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 43,
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral.",
    "responsible": "Laura Gabriela Calvario",
    "contributors": "Laura Gabriela Calvario",
    "activity": "Actividades de formación socioemocional en planteles",
    "dedupeKey": "b9db029895b522aa",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 44,
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral.",
    "responsible": "Daniela Nohemi Navarro Castillo",
    "contributors": "Daniela Nohemi Navarro Castillo",
    "activity": "Convocatorias externas",
    "dedupeKey": "8d26eda3747b5739",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 45,
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral.",
    "responsible": "Carlos Hernández Nava",
    "contributors": "Carlos Hernández Nava",
    "activity": "Viajes de estudio",
    "dedupeKey": "09688dd98940c724",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 46,
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral.",
    "responsible": "Daniela Nohemi Navarro Castillo",
    "contributors": "Daniela Nohemi Navarro Castillo",
    "activity": "Modelo de las Naciones Unidas",
    "dedupeKey": "df32eceb4d3f0ea8",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 47,
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral.",
    "responsible": "Ariadna Zuñiga Torres",
    "contributors": "Ariadna Zuñiga Torres",
    "activity": "Programa Adopta una Prepa capitulo España de la Red Global Mx",
    "dedupeKey": "a0d06c5f5f0f7f45",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 48,
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral.",
    "responsible": "Marcial Aviña Iglesias",
    "contributors": "Marcial Aviña Iglesias",
    "activity": "Concursos de declamación y oratoria",
    "dedupeKey": "ac59ae0551393146",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 49,
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral.",
    "responsible": "Marcial Aviña Iglesias",
    "contributors": "Marcial Aviña Iglesias",
    "activity": "Cuarto Encuentro Cultural ANUIES",
    "dedupeKey": "15089deae6c29328",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 50,
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral.",
    "responsible": "Marcial Aviña Iglesias",
    "contributors": "Marcial Aviña Iglesias",
    "activity": "Nacimiento Tradicional Mexicano",
    "dedupeKey": "71eaee00285744e2",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 51,
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral.",
    "responsible": "Marcial Aviña Iglesias",
    "contributors": "Marcial Aviña Iglesias",
    "activity": "Concurso ANUIES en Corto 2026",
    "dedupeKey": "f8a9fd756750fc95",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 52,
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral.",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "Territorio Biodiverso UdeC",
    "dedupeKey": "82e7c88db7ab07df",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 53,
    "code": "1.1.2.4.1",
    "name": "Porcentaje de estudiantes de educación media superior atendidos en acciones de inclusión educativa",
    "responsible": "Ariadna Zuñiga Torres",
    "contributors": "Ariadna Zuñiga Torres",
    "activity": "Trayectorias escolares",
    "dedupeKey": "b6dd2e3628f87cd4",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 54,
    "code": "1.1.2.5.1",
    "name": "Porcentaje de docentes de educación media superior y superior que cumple con perfil docente idóneo de acuerdo con el modelo educativo institucional",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Oscar Delgado Sánchez",
    "activity": "Formación docente",
    "dedupeKey": "cfcc8fc9fe1c9db7",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 55,
    "code": "1.1.2.5.3",
    "name": "Porcentaje de PTC de educación media superior beneficiados en el programa de ESDEPED",
    "responsible": "Adriana Ruiz Rivera",
    "contributors": "Adriana Ruiz Rivera, Armando Hernández Ramírez",
    "activity": "Convocatoria de ESDEPED",
    "dedupeKey": "96707ee93ec8bfc1",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 56,
    "code": "1.1.2.5.3",
    "name": "Porcentaje de PTC de educación media superior beneficiados en el programa de ESDEPED",
    "responsible": "Adriana Ruiz Rivera",
    "contributors": "Adriana Ruiz Rivera, Armando Hernández Ramírez",
    "activity": "Convocatoria de ESDEPED",
    "dedupeKey": "96707ee93ec8bfc1",
    "isDuplicate": true,
    "duplicateOfSourceRow": 55,
    "dataQuality": []
  },
  {
    "sourceRow": 57,
    "code": "1.1.2.5.5",
    "name": "Porcentaje de docentes de educación media superior y superior que reciben capacitación en competencias pedagógicas, didácticas, digitales e informacionales, socioemocionales, inclusión, investigación, internacionalización, arte, cultura, innovación, igualdad género, sustentabilidad, sostenibilidad y medio ambiente, con enfoque interseccional y de interculturalidad",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Oscar Delgado Sánchez",
    "activity": "Formación docente, Coloquio formación docente",
    "dedupeKey": "2fc5ce329bcf4551",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 58,
    "code": "1.1.2.5.6",
    "name": "Porcentaje de personal de apoyo académico de educación media superior y superior que reciben capacitación en competencias pedagógicas, didácticas, digitales e informacionales, socioemocionales, inclusión, investigación, internacionalización, arte, cultura, innovación, igualdad de género, sustentabilidad, sostenibilidad y medio ambiente, con enfoque interseccional y de interculturalidad",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Oscar Delgado Sánchez",
    "activity": "Formación docente",
    "dedupeKey": "baa90fc3455bf053",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 59,
    "code": "1.1.2.5.7",
    "name": "Porcentaje de docentes de educación media superior y superior que recibe capacitación disciplinar pertinente en su área de desempeño",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Oscar Delgado Sánchez",
    "activity": "Formación docente",
    "dedupeKey": "cbd867c730b97f89",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 60,
    "code": "1.1.2.5.8",
    "name": "Porcentaje de personal de apoyo académico de educación media superior y superior que recibe capacitación disciplinar pertinente en su área de desempeño",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Oscar Delgado Sánchez",
    "activity": "Formación docente",
    "dedupeKey": "2f78873da9a39370",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 61,
    "code": "1.1.2.5.7",
    "name": "Porcentaje de docentes de educación media superior y superior que recibe capacitación disciplinar pertinente en su área de desempeño",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Oscar Delgado Sánchez",
    "activity": "Formación docente",
    "dedupeKey": "cbd867c730b97f89",
    "isDuplicate": true,
    "duplicateOfSourceRow": 59,
    "dataQuality": []
  },
  {
    "sourceRow": 62,
    "code": "1.1.2.5.8",
    "name": "Porcentaje de personal de apoyo académico de educación media superior y superior que recibe capacitación disciplinar pertinente en su área de desempeño",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Oscar Delgado Sánchez",
    "activity": "Formación docente",
    "dedupeKey": "2f78873da9a39370",
    "isDuplicate": true,
    "duplicateOfSourceRow": 60,
    "dataQuality": []
  },
  {
    "sourceRow": 63,
    "code": "1.1.2.5.9",
    "name": "Porcentaje de docentes de educación media superior y superior participando en movilidad académica.",
    "responsible": "Laura Gabriela Calvario",
    "contributors": "Laura Gabriela Calvario, Oscar Delgado Sánchez",
    "activity": "Movilidad académica de docentes",
    "dedupeKey": "f0506d07ddeb86cf",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 64,
    "code": "1.1.2.5.10",
    "name": "Porcentaje de docentes de educación media superior y superior certificados en el dominio de una lengua extranjera.",
    "responsible": "Laura Gabriela Calvario",
    "contributors": "Laura Gabriela Calvario",
    "activity": "Docentes certificados en el dominio de una lengua extranjera",
    "dedupeKey": "a63dae8ed090b03e",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 65,
    "code": "2.1.4.1.2",
    "name": "Número de estudiantes que colaboran en proyectos de investigación liderados por profesorado de tiempo completo",
    "responsible": "Ariadna Zuñiga Torres",
    "contributors": "Ariadna Zuñiga Torres",
    "activity": "Proyectos de investigación",
    "dedupeKey": "1a2ef085f4a68a8f",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 66,
    "code": "2.1.4.1.1",
    "name": "Número de acciones de fomento a vocaciones científicas y tecnológicas que incorporan explícitamente el enfoque interseccional y la perspectiva de género.",
    "responsible": "Ariadna Zuñiga Torres",
    "contributors": "Ariadna Zuñiga Torres",
    "activity": "Actividades de sensibilización, capacitación y/o formación en materia de prevención de la discriminación y violencia de género en colaboración con el CUPIEG, Acciones implementadas donde participe el estudiantado en áreas STEM",
    "dedupeKey": "88de475ccd64e70f",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 67,
    "code": "2.1.4.1.3",
    "name": "Porcentaje del estudiantado que participa en programas que fomentan el desarrollo de vocaciones científicas y tecnológicas",
    "responsible": "Salvador Aguilar Aguilar",
    "contributors": "Salvador Aguilar Aguilar",
    "activity": "Semana de Vinculación Académica para las Juventudes de Educación Media Superior, Expo ciencia del NMS en las áreas de ciencias experimentales",
    "dedupeKey": "7ee11271c8f3ae4c",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 68,
    "code": "3.1.1.2.2",
    "name": "Número de eventos de educación continua",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Oscar Delgado Sánchez",
    "activity": "Formación docente",
    "dedupeKey": "1ffcc0bed786ff3b",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 69,
    "code": "3.1.0.0.1",
    "name": "Número de programas y proyectos de extensión y vinculación dirigidas al sector social y productivo",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Oscar Delgado Sánchez",
    "activity": "Diseño curricular",
    "dedupeKey": "4da8df7c67a7701d",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 70,
    "code": "3.1.0.0.1",
    "name": "Número de programas y proyectos de extensión y vinculación dirigidas al sector social y productivo",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "Acciones de vinculación en sostenibilidad con el sector social y productivo",
    "dedupeKey": "e610ee8768918ba0",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 71,
    "code": "3.1.0.0.1",
    "name": "Número de programas y proyectos de extensión y vinculación dirigidas al sector social y productivo",
    "responsible": "Marcial Aviña Iglesias",
    "contributors": "Marcial Aviña Iglesias",
    "activity": "",
    "dedupeKey": "a599a3bab92f07b7",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "blank_activity"
    ]
  },
  {
    "sourceRow": 72,
    "code": "3.1.1.3.6",
    "name": "Número de participantes en actividades de sostenibilidad y medio ambiente convocadas por el SIGA.",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "Participantes de la dependencia en acciones sostenibles",
    "dedupeKey": "17c3ed1a83796052",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 73,
    "code": "3.1.1.3.6",
    "name": "Número de participantes en actividades de sostenibilidad y medio ambiente convocadas por el SIGA.",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "Eventos de formación en colaboración con CEUGEA",
    "dedupeKey": "a97221f8f43f02a7",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 74,
    "code": "3.1.1.3.6",
    "name": "Número de participantes en actividades de sostenibilidad y medio ambiente convocadas por el SIGA.",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "Actividades de \"buenas prácticas ambientales (BPA) comunidades universitarias sostenibles\"",
    "dedupeKey": "0f68624bbf2eb49e",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 75,
    "code": "3.1.1.3.6",
    "name": "Número de participantes en actividades de sostenibilidad y medio ambiente convocadas por el SIGA.",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "Materiales formativos y de divulgación sobre actividades CEUGEA",
    "dedupeKey": "cf9c6de94466f356",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 76,
    "code": "3.1.1.3.6",
    "name": "Número de participantes en actividades de sostenibilidad y medio ambiente convocadas por el SIGA.",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Oscar Gustavo Mendoza Barajas",
    "activity": "Actividades de comunicación digital sobre cultura ambiental",
    "dedupeKey": "fd117ecb85a91459",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 77,
    "code": "4.1.1.1.1",
    "name": "Número de sistemas implementados y mejorados para fortalecer la gestión de procesos institucionales.",
    "responsible": "Angel Ordoñez Ayala",
    "contributors": "Angel Ordoñez Ayala",
    "activity": "Sistemas académicos o administrativos y plataformas de comunicación actualizados",
    "dedupeKey": "5fa6e939b353a44b",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 78,
    "code": "4.1.1.0.1",
    "name": "Número de Sistemas de Información Institucionales que interoperan",
    "responsible": "Angel Ordoñez Ayala",
    "contributors": "Angel Ordoñez Ayala",
    "activity": "Sistemas de Información Institucionales Interoperables",
    "dedupeKey": "87f934f31a852402",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 79,
    "code": "4.1.0.0.1",
    "name": "Porcentaje de actualización de procesos certificados ante nomas ISO",
    "responsible": "Laura Gabriela Calvario",
    "contributors": "Laura Gabriela Calvario",
    "activity": "Procesos certificados con estándares ISO",
    "dedupeKey": "099b5446ca0f15d6",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 80,
    "code": "4.1.0.0.1",
    "name": "Porcentaje de actualización de procesos certificados ante nomas ISO",
    "responsible": "Laura Gabriela Calvario",
    "contributors": "Laura Gabriela Calvario",
    "activity": "Procesos certificados con estándares ISO",
    "dedupeKey": "099b5446ca0f15d6",
    "isDuplicate": true,
    "duplicateOfSourceRow": 79,
    "dataQuality": []
  },
  {
    "sourceRow": 81,
    "code": "4.1.1.2.1",
    "name": "Porcentaje de UO con estudio de ambiente de trabajo aplicado.",
    "responsible": "Laura Gabriela Calvario",
    "contributors": "Laura Gabriela Calvario",
    "activity": "Satisfacción del clima laboral alcanzado en la encuesta de ambiente de trabajo",
    "dedupeKey": "b8da1fc7d54667a6",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 82,
    "code": "4.0.0.0.1",
    "name": "Porcentaje de UO que impulsan el fortalecimiento de la gobernanza institucional",
    "responsible": "Martín Jesús Robles DeAnda",
    "contributors": "Martín Jesús Robles de Anda, Ma. Guadalupe del Rocío Herrera Chacón, Armando Hernández Ramírez",
    "activity": "Acciones de fortalecimiento a la gobernanza institucional",
    "dedupeKey": "397ddeee41df5f24",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 83,
    "code": "4.0.0.0.1",
    "name": "Porcentaje de UO que impulsan el fortalecimiento de la gobernanza institucional",
    "responsible": "Ma. Guadalupe del Rocío Herrera Chacón",
    "contributors": "Martín Jesús Robles de Anda, Ma. Guadalupe del Rocío Herrera Chacón, Armando Hernández Ramírez",
    "activity": "Acciones de fortalecimiento a la gobernanza institucional",
    "dedupeKey": "720b8c22cf57a8ff",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 84,
    "code": "4.0.0.0.1",
    "name": "Porcentaje de UO que impulsan el fortalecimiento de la gobernanza institucional",
    "responsible": "Ma. Guadalupe del Rocío Herrera Chacón",
    "contributors": "Ma. Guadalupe del Rocío Herrera Chacón",
    "activity": "Acciones de fortalecimiento a la gobernanza institucional",
    "dedupeKey": "b958388e186c20bc",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 85,
    "code": "4.1.1.3.2",
    "name": "Porcentaje de efectividad del Sistema Universitario de Archivos para la gestión documental",
    "responsible": "Ma. Guadalupe del Rocío Herrera Chacón",
    "contributors": "Ma. Guadalupe del Rocío Herrera Chacón",
    "activity": "Administración del SUA",
    "dedupeKey": "0198122f4897d60e",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 86,
    "code": "4.1.1.3.1",
    "name": "Porcentaje de cumplimiento de la gestión documental y administración de archivos",
    "responsible": "Claudia Raquel Piña Andrade",
    "contributors": "Claudia Raquel Piña Andrade, Ma. Guadalupe del Rocío Herrera Chacón",
    "activity": "Administración del SUA",
    "dedupeKey": "d3390dd5f390f491",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 87,
    "code": "4.1.1.3.2",
    "name": "Porcentaje de efectividad del Sistema Universitario de Archivos para la gestión documental",
    "responsible": "Claudia Raquel Piña Andrade",
    "contributors": "Claudia Raquel Piña Andrade, Ma. Guadalupe del Rocío Herrera Chacón",
    "activity": "Administración del SUA",
    "dedupeKey": "3bc37c7487258bd2",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 88,
    "code": "4.1.2.1.3",
    "name": "Porcentaje de dependencias universitarias con infraestructura rehabilitada",
    "responsible": "Oscar Pedraza Farías",
    "contributors": "Ma. Guadalupe del Rocío Herrera Chacón, Oscar Pedraza Farías, Carlos Hernández Nava, Jorge García Pérez, Jorge Silva Torres",
    "activity": "Supervisión escolar a planteles e incorporados",
    "dedupeKey": "8c65ff752c8d41c5",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 89,
    "code": "4.1.2.1.6",
    "name": "Porcentaje de dependencias universitarias que reciben equipamiento",
    "responsible": "Oscar Pedraza Farías",
    "contributors": "Ma. Guadalupe del Rocío Herrera Chacón, Oscar Pedraza Farías, Carlos Hernández Nava, Jorge García Pérez, Jorge Silva Torres",
    "activity": "Supervisión escolar a planteles e incorporados",
    "dedupeKey": "4eb4a73189fdf560",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 90,
    "code": "4.1.2.2.1",
    "name": "Porcentaje de UO que realizan acciones de actualización, mantenimiento preventivo y/o correctivo a la infraestructura tecnológica",
    "responsible": "Angel Ordoñez Ayala",
    "contributors": "Angel Ordoñez Ayala",
    "activity": "Acciones de mantenimiento preventivo a la infraestructura tecnológica",
    "dedupeKey": "bf10bdadd9d1a2a5",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 91,
    "code": "4.1.3.0.1",
    "name": "Porcentaje de documentos normativos creados o actualizados que regulan el quehacer universitario",
    "responsible": "Armando Hernández Ramírez",
    "contributors": "Armando Hernández Ramírez, Marcial Aviña Iglesias, Óscar Delgado Sánchez",
    "activity": "Reglamentos, lineamientos, manuales o cualquier documento normativo en proceso de creación o actualizado",
    "dedupeKey": "53e36423cb479a38",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 92,
    "code": "4.1.3.2.4",
    "name": "Porcentaje de cobertura institucional de gestión del riesgo y atención de emergencias",
    "responsible": "Salvador Aguilar Aguilar",
    "contributors": "Salvador Aguilar Aguilar",
    "activity": "Programa Interno de Protección Civil",
    "dedupeKey": "7a2fa9ce7f3aa080",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 93,
    "code": "4.1.3.2.4",
    "name": "Porcentaje de cobertura institucional de gestión del riesgo y atención de emergencias",
    "responsible": "Dulce Sarahi García Mójica",
    "contributors": "Dulce Sarahi García Mójica, Salvador Aguilar Aguilar",
    "activity": "Programa Interno de Protección Civil",
    "dedupeKey": "cd597eeaa6e02109",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 94,
    "code": "4.1.3.2.4",
    "name": "Porcentaje de cobertura institucional de gestión del riesgo y atención de emergencias",
    "responsible": "Salvador Aguilar Aguilar",
    "contributors": "Salvador Aguilar Aguilar",
    "activity": "Programa Interno de Protección Civil",
    "dedupeKey": "7a2fa9ce7f3aa080",
    "isDuplicate": true,
    "duplicateOfSourceRow": 92,
    "dataQuality": []
  },
  {
    "sourceRow": 95,
    "code": "4.1.4.3.3",
    "name": "Porcentaje de personal universitario capacitado para el fortalecimiento de su competencia laboral.",
    "responsible": "Ma. Guadalupe del Rocío Herrera Chacón",
    "contributors": "Ma. Guadalupe del Rocío Herrera Chacón",
    "activity": "Personal capacitado",
    "dedupeKey": "124743d8774f7447",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 96,
    "code": "4.1.5.3.3",
    "name": "Número de acciones generadas para el cumplimiento del Programa Anual de Comunicación Social (PACS)",
    "responsible": "Angel Ordoñez Ayala",
    "contributors": "Angel Ordoñez Ayala, Daniela Nohemi Navarro Castillo, Liliana Yunuen Rojas Maciel, Marcial Aviña Iglesias",
    "activity": "Campañas de comunicación para la promoción de la oferta educativa, Programa radiofónico Nada a medias, Convocatorias",
    "dedupeKey": "3738535036845f92",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 97,
    "code": "4.1.5.3.3",
    "name": "Número de acciones generadas para el cumplimiento del Programa Anual de Comunicación Social (PACS)",
    "responsible": "Angel Ordoñez Ayala",
    "contributors": "Angel Ordoñez Ayala, Daniela Nohemi Navarro Castillo, Liliana Yunuen Rojas Maciel, Marcial Aviña Iglesias",
    "activity": "Manuales de prácticas y cuadernos de trabajo",
    "dedupeKey": "cdb4d4bb411f426a",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 98,
    "code": "4.1.5.0.1",
    "name": "Porcentaje de UO que ejecutan eficientemente su Programa Operativo Anual.",
    "responsible": "Armando Hernández Ramírez",
    "contributors": "Armando Hernández Ramírez, Ma. Guadalupe del Rocío Herrera Chacón",
    "activity": "Programa operativo anual",
    "dedupeKey": "ecf238df4cd174a5",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 99,
    "code": "4.1.5.0.1",
    "name": "Porcentaje de UO que ejecutan eficientemente su Programa Operativo Anual.",
    "responsible": "Armando Hernández Ramírez",
    "contributors": "Armando Hernández Ramírez, Ma. Guadalupe del Rocío Herrera Chacón",
    "activity": "Programa operativo anual",
    "dedupeKey": "ecf238df4cd174a5",
    "isDuplicate": true,
    "duplicateOfSourceRow": 98,
    "dataQuality": []
  },
  {
    "sourceRow": 100,
    "code": "4.1.6.1.1",
    "name": "Tasa de variación de recursos financieros generados por el quehacer institucional.",
    "responsible": "Ma. Guadalupe del Rocío Herrera Chacón",
    "contributors": "Ma. Guadalupe del Rocío Herrera Chacón",
    "activity": "Generación de recursos",
    "dedupeKey": "3d1811546129602a",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": []
  },
  {
    "sourceRow": 101,
    "code": "1.1.1.3.2",
    "name": "La tabla anterior incide en las siguientes líneas de acción del informe de labores de la DGEMS y planteles de NMS: Número de personal de apoyo académico de NMS y NS que reciben ca",
    "responsible": "Pendiente de asignar",
    "contributors": "Planteles",
    "activity": "Formación_docente.xlsx",
    "dedupeKey": "a8ece0d92de58e16",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "workbook_only_indicator"
    ]
  },
  {
    "sourceRow": 102,
    "code": "1.1.1.3.3",
    "name": "La tabla anterior incide en las siguientes líneas de acción del informe de labores de la DGEMS y planteles de NMS: 1.1.1.3.2 Número de personal de apoyo académico de NMS y NS que r",
    "responsible": "Pendiente de asignar",
    "contributors": "Planteles",
    "activity": "Formación_docente.xlsx",
    "dedupeKey": "4f0fbc05782bea00",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "workbook_only_indicator"
    ]
  },
  {
    "sourceRow": 103,
    "code": "1.1.1.5.1",
    "name": "La tabla anterior incide en las siguientes líneas de acción del informe de labores de la DGEMS y planteles de NMS: 1.1.1.3.2 Número de personal de apoyo académico de NMS y NS que r",
    "responsible": "Pendiente de asignar",
    "contributors": "Planteles",
    "activity": "Formación_docente.xlsx",
    "dedupeKey": "75cffa4f46eeb4fe",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "workbook_only_indicator"
    ]
  },
  {
    "sourceRow": 104,
    "code": "1.1.1.5.2",
    "name": "La tabla anterior incide en la siguiente línea de acción del informe de labores de la DGEMS y planteles de NMS: Número de personal de apoyo académico de NMS y NS que recibe capaci",
    "responsible": "Pendiente de asignar",
    "contributors": "Planteles",
    "activity": "Formación_apoyo académico.xlsx",
    "dedupeKey": "976af2ab99f3a025",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "workbook_only_indicator"
    ]
  },
  {
    "sourceRow": 105,
    "code": "1.1.2.1.8",
    "name": "Porcentaje de titulación por cohorte del NMS",
    "responsible": "Pendiente de asignar",
    "contributors": "Planteles",
    "activity": "INDICADOR DE TITULACION 2025.xlsx",
    "dedupeKey": "9ea3441ebc9ed980",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "workbook_only_indicator"
    ]
  },
  {
    "sourceRow": 106,
    "code": "1.1.3.0.3",
    "name": "Porcentaje de estudiantes de NMS participantes en las actividades de desarrollo y formación integral",
    "responsible": "Pendiente de asignar",
    "contributors": "Planteles",
    "activity": "JORNADA POR LA PAZ Y CONTRA LAS ADICCIONES FEB-AGO25.xlsx",
    "dedupeKey": "a36722d0322ae214",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "workbook_only_indicator"
    ]
  },
  {
    "sourceRow": 107,
    "code": "1.1.4.4.4",
    "name": "Número de estudiantes de NMS y NS participando en acciones de internacionalización",
    "responsible": "Pendiente de asignar",
    "contributors": "Planteles",
    "activity": "Formato_Indicador de internacionalización.xlsx",
    "dedupeKey": "b9405a3b39c8515d",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "workbook_only_indicator"
    ]
  }
];
