// Generated by tools/import-official-data.py from indicadores-20260622T210134Z-3-001.zip.
// Source binaries and row-level private data are intentionally not committed.

export type OfficialCatalogRow = {
  sourceRow: number;
  code: string;
  name: string;
  responsible: string;
  contributors: string;
  activity: string;
  dedupeKey: string;
  isDuplicate: boolean;
  duplicateOfSourceRow: number | null;
  dataQuality: string[];
};

export const officialCatalogStats = {
  "sourceRows": 28,
  "uniqueRows": 28,
  "duplicateRows": 0,
  "uniqueIndicators": 28,
  "uniqueResponsibles": 10,
  "uniqueContributors": 1,
  "uniqueActivities": 28,
  "blankActivities": 0,
  "workbookOnlyIndicators": 0
} as const;

export const officialIndicatorPlantelScopes: Record<string, number[]> = {
  "1.0.0.0.2": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    37
  ],
  "1.0.0.0.2-FMT-7639E719": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    37
  ],
  "1.1.1.1.1": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    37
  ],
  "1.1.2.0.3": [
    3
  ],
  "1.1.2.0.3-FMT-EDABD54D": [
    3
  ],
  "1.1.2.5.3": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    37
  ],
  "2.1.4.1.2": [
    17
  ]
};

export const officialCatalogRows: OfficialCatalogRow[] = [
  {
    "sourceRow": 2,
    "code": "1.0.0.0.2",
    "name": "Porcentaje de titulación por cohorte del NMS",
    "responsible": "Adriana Ruiz Rivera",
    "contributors": "Planteles",
    "activity": "1.0.0.0.2 Titulación por cohorte.xlsx",
    "dedupeKey": "feaff05497009c42",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 3,
    "code": "1.0.0.0.2-FMT-7639E719",
    "name": "Porcentaje de titulación por cohorte del NMS",
    "responsible": "Adriana Ruiz Rivera",
    "contributors": "Planteles",
    "activity": "Titulación por cohorte.xlsx",
    "dedupeKey": "046d043f354a9df9",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 4,
    "code": "1.1.1.1.1",
    "name": "Porcentaje de programas educativos de educación media superior nuevos, actualizados y reestructurados alineados al modelo educativo, incorporando formalmente el enfoque de sostenib",
    "responsible": "Adriana Ruiz Rivera",
    "contributors": "Planteles",
    "activity": "Formato con OPCIONES de llenado de academias por plantel.xlsx",
    "dedupeKey": "a50781535799b488",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 5,
    "code": "1.1.1.1.1-FMT-489662BE",
    "name": "Porcentaje de programas educativos de educación media superior nuevos, actualizados y reestructurados alineados al modelo educativo, incorporando formalmente el enfoque de sostenib",
    "responsible": "Adriana Ruiz Rivera",
    "contributors": "Planteles",
    "activity": "1.1.1.1.1 Formato conformación de academias por plantel.xlsx",
    "dedupeKey": "d104d9c5b4f16e03",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 6,
    "code": "1.1.2.0.1",
    "name": "Porcentaje retención escolar de educación media superior",
    "responsible": "Liliana Yunuen Rojas Maciel",
    "contributors": "Planteles",
    "activity": "Indicador 1.1.2.0.1..xlsx",
    "dedupeKey": "23f0ba9177c4c507",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 7,
    "code": "1.1.2.0.1-FMT-4EB45B2E",
    "name": "PORCENTAJE DE RETENCIÓN ESCOLAR DE EMS",
    "responsible": "Daniela Nohemi Navarro Castillo",
    "contributors": "Planteles",
    "activity": "1.1.2.0.1. porcentaje de retención escolar de EMS.xlsx",
    "dedupeKey": "e275d69a4983c573",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 8,
    "code": "1.1.2.0.3",
    "name": "TASA DE ABANDONO ESCOLAR DE EDUCACIÓN MEDIA SUPERIOR",
    "responsible": "Daniela Nohemi Navarro Castillo",
    "contributors": "Planteles",
    "activity": "1.1.2.0.3.Estrategias para combatir el abandono escolar.xlsx",
    "dedupeKey": "241bd2e3eff2f244",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 9,
    "code": "1.1.2.0.3-FMT-EDABD54D",
    "name": "Tasa de abadono escolar de educación media superior",
    "responsible": "Liliana Yunuen Rojas Maciel",
    "contributors": "Planteles",
    "activity": "Indicador 1.1.2.0.3..xlsx",
    "dedupeKey": "5bd61afce2162415",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 10,
    "code": "1.1.2.1.4",
    "name": "Porcentaje de estudiantes de educación media superior y superior atendidos en los servicios de salud integral",
    "responsible": "Carlos Hernández Nava",
    "contributors": "Planteles",
    "activity": "PROMOCIÓN DE LA SALUD",
    "dedupeKey": "c77d73de408927b9",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 11,
    "code": "1.1.2.2.10",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de sostenibilidad y medio ambiente para la acción climática",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Planteles",
    "activity": "1.1.2.2.10.xlsx",
    "dedupeKey": "0964b03c8fae2015",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 12,
    "code": "1.1.2.2.11",
    "name": "Porcentaje de estudiantes de educación media superior y superior que participan en acciones de igualdad de género",
    "responsible": "Ariadna Zúñiga Torres",
    "contributors": "Planteles",
    "activity": "1.1.2.2.11 Seguimiento capacitación en materia de género planteles.xlsx",
    "dedupeKey": "ababc470d5ae1b26",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 13,
    "code": "1.1.2.3.1",
    "name": "Porcentaje de estudiantes de NMS y NS participantes en las actividades de desarrollo y formación integral",
    "responsible": "Ariadna Zúñiga Torres",
    "contributors": "Planteles",
    "activity": "1.1.2.3.1 Programa Adopta una Prepa .xlsx",
    "dedupeKey": "69aad894d8088a79",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 14,
    "code": "1.1.2.3.1-FMT-2A7229AD",
    "name": "PORCENTAJE DE ESTUDIANTES DE MEDIA SUPERIOR QUE PARTICIPAN EN ACTIVIDADES DE FORMACIÓN INTEGRAL",
    "responsible": "Daniela Nohemi Navarro Castillo",
    "contributors": "Planteles",
    "activity": "1.1.2.3.1.Convocatorias externas .xlsx",
    "dedupeKey": "041e5531b647a06b",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 15,
    "code": "1.1.2.3.1-FMT-6434504C",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral",
    "responsible": "Carlos Hernández Nava",
    "contributors": "Planteles",
    "activity": "VIAJES DE ESTUDIO",
    "dedupeKey": "ecdacb921010908e",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 16,
    "code": "1.1.2.3.1-FMT-AB95A3B8",
    "name": "Porcentaje de estudiantes de media superior que participan en actividades de formación integral",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Planteles",
    "activity": "1.1.2.3.1.xlsx",
    "dedupeKey": "5501890dc37adf25",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 17,
    "code": "1.1.2.3.1-FMT-FBF5B718",
    "name": "PORCENTAJE DE ESTUDIANTES DE MEDIA SUPERIOR QUE PARTICIPAN EN ACTIVIDADES DE FORMACIÓN INTEGRAL",
    "responsible": "Daniela Nohemi Navarro Castillo",
    "contributors": "Planteles",
    "activity": "1.1.2.3.1. Modelo de las Naciones Unidas.xlsx",
    "dedupeKey": "1863e63fde864918",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 18,
    "code": "1.1.2.5.10",
    "name": "Porcentaje de docentes de educación media superior y superior certificados en el dominio de una Lengua Extranjera",
    "responsible": "Laura Gabriela Calvario",
    "contributors": "Planteles",
    "activity": "1.1.2.5.10 - Porcentaje de docentes de educación media superior y superior certificados en el dominio de una Lengua Extranjera.xlsx",
    "dedupeKey": "f7213ebaca0c60fb",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 19,
    "code": "1.1.2.5.3",
    "name": "Porcentaje de PTC de educación media superior beneficiados en el programa de ESDEPED",
    "responsible": "Adriana Ruiz Rivera",
    "contributors": "Planteles",
    "activity": "Opción de llenado Seguimiento de PTC.xlsx",
    "dedupeKey": "77b316d2ce80d604",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 20,
    "code": "1.1.2.5.3-FMT-6D26FF23",
    "name": "Porcentaje de PTC de educación media superior beneficiados en el programa de ESDEPED",
    "responsible": "Adriana Ruiz Rivera",
    "contributors": "Planteles",
    "activity": "1.1.2.5.3 Seguimiento de PTC.xlsx",
    "dedupeKey": "09fffdb2e7baf2a9",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "shared_official_code_split_by_source",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 21,
    "code": "2.1.4.1.2",
    "name": "Número de estudiantes que colaboran en proyectos de investigación liderados por profesorado de tiempo completo",
    "responsible": "Ariadna Zúñiga Torres",
    "contributors": "Planteles",
    "activity": "2.1.4.1.2 Seguimiento a proyectos de investigación en planteles.xlsx",
    "dedupeKey": "159ededf3336b707",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 22,
    "code": "3.1.0.0.1",
    "name": "Número de programas y proyectos de extensión y vinculación dirigidas al sector social y productivo",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Planteles",
    "activity": "3.1.0.0.1.xlsx",
    "dedupeKey": "c6be483157d085b5",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 23,
    "code": "3.1.1.3.6",
    "name": "Número de participantes en actividades de sostenibilidad y medio ambiente convocadas por el SIGA",
    "responsible": "Oscar Gustavo Mendoza Barajas",
    "contributors": "Planteles",
    "activity": "3.1.1.3.6.xlsx",
    "dedupeKey": "5f9569e2e5a45ab7",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 24,
    "code": "4.1.1.0.1",
    "name": "Número de Sistemas de Información Institucionales que interoperan",
    "responsible": "Angel Ordoñez",
    "contributors": "Planteles",
    "activity": "4.1.1.0.1. Numero de Sistemas de Informacion Institucionales que interoperan.xlsx",
    "dedupeKey": "04db0ba7b3ec2e39",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 25,
    "code": "4.1.1.1.1",
    "name": "Número de sistemas implementados y mejorados para fortalecer la gestión de procesos institucionales",
    "responsible": "Angel Ordoñez",
    "contributors": "Planteles",
    "activity": "4.1.1.1.1. - Número de sistemas implementados y mejorados para fortalecer la gestión de procesos institucionales..xlsx",
    "dedupeKey": "7ed01891822d834b",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "official_code_detected",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 26,
    "code": "FMT-01-43FE55CA-formacion-docente-2026",
    "name": "Formación_docente_2026",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Planteles",
    "activity": "Formación_docente_2026.xlsx",
    "dedupeKey": "1f33374d67ff3180",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "pending_indicator_code",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 27,
    "code": "FMT-01-D30B3A90-formacion-apoyo-academic",
    "name": "Formación_apoyo académico_2026",
    "responsible": "Oscar Delgado Sánchez",
    "contributors": "Planteles",
    "activity": "Formación_apoyo académico_2026.xlsx",
    "dedupeKey": "6069d6c7262f6a88",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "pending_indicator_code",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 28,
    "code": "FMT-01-E81E8473-41221-porcentaje-de-uo-q",
    "name": "41221 - Porcentaje de UO que realizan acciones de actualización, mantenimiento preventivo o correctivo de la insfraestructura tecnologica",
    "responsible": "Angel Ordoñez",
    "contributors": "Planteles",
    "activity": "41221 - Porcentaje de UO que realizan acciones de actualización, mantenimiento preventivo o correctivo de la insfraestructura tecnologica.xlsx",
    "dedupeKey": "4a4d08643b7a2fef",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "pending_indicator_code",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  },
  {
    "sourceRow": 29,
    "code": "FMT-01-F2A88F7E-nivelacion-academica-ago",
    "name": "NIVELACION ACADEMICA_ agosto 2025_ENERO2026 (1)",
    "responsible": "Marcial Aviña Iglesias",
    "contributors": "Planteles",
    "activity": "NIVELACION ACADEMICA_ agosto 2025_ENERO2026 (1).xlsx",
    "dedupeKey": "ad2819175087d24c",
    "isDuplicate": false,
    "duplicateOfSourceRow": null,
    "dataQuality": [
      "pending_indicator_code",
      "private_fields_blank",
      "source_workbook_template",
      "source_zip_indicator"
    ]
  }
];
