// Generated by tools/import-official-data.py from drive-download-20260428T232937Z-3-001.zip.
// Source binaries and personal identifiers are intentionally not committed.

export type OfficialEvidenceGroup = {
  category: string;
  fileCount: number;
  totalBytes: number;
  byExtension: Record<string, number>;
  sampleFileTypes: string[];
};

export type OfficialWorkbookSheetSummary = {
  name: string;
  nonEmptyRows: number;
  columnsObserved: number;
  sampleHeaders: string[];
  headerRows: string[][];
  numericCells: number;
  textCells: number;
  formulaCells: number;
};

export type OfficialWorkbookSummary = {
  id: string;
  sourceLabel: string;
  sourcePathHash: string;
  category: string;
  sizeBytes: number;
  detectedIndicatorCodes: string[];
  detectedPlanteles: string[];
  formulaCells: number;
  sheets: OfficialWorkbookSheetSummary[];
  privacy: string;
};

export type OfficialTemplateCandidate = {
  indicatorCode: string;
  sourcePath: string;
  planteles: string[];
  classification: string;
  confidence: string;
  headerRows: string[][];
};

export type OfficialDataSummary = {
  sourcePackage: string;
  plantel: string;
  generatedAt: string;
  topLevelFiles: number;
  nestedFiles: number;
  nestedTotalBytes: number;
  workbookCount: number;
  worksheetCount: number;
  worksheetNonEmptyRows: number;
  privacy: string;
};

export const officialDataSummary: OfficialDataSummary = {
  "sourcePackage": "drive-download-20260428T232937Z-3-001.zip",
  "plantel": "Bachillerato 16",
  "generatedAt": "2026-06-17",
  "topLevelFiles": 3,
  "nestedFiles": 981,
  "nestedTotalBytes": 1102495087,
  "workbookCount": 39,
  "worksheetCount": 53,
  "worksheetNonEmptyRows": 1313,
  "privacy": "Row-level personal data and evidence files remain backend-private; source binaries are not committed."
};

export const officialEvidenceGroups: OfficialEvidenceGroup[] = [
  {
    "category": "1. CAPACITACIÓN EN LÍNEA CENEVAL 2025",
    "fileCount": 1,
    "totalBytes": 3888829,
    "byExtension": {
      ".docx": 1
    },
    "sampleFileTypes": [
      ".docx"
    ]
  },
  {
    "category": "10 ma. Semana de Física y Matemáticas ...jpeg",
    "fileCount": 1,
    "totalBytes": 106331,
    "byExtension": {
      ".jpeg": 1
    },
    "sampleFileTypes": [
      ".jpeg"
    ]
  },
  {
    "category": "10 ma. Semana de Física y Matemáticas..jpeg",
    "fileCount": 1,
    "totalBytes": 60389,
    "byExtension": {
      ".jpeg": 1
    },
    "sampleFileTypes": [
      ".jpeg"
    ]
  },
  {
    "category": "10 ma. Semana de Física y Matemáticas.jpeg",
    "fileCount": 1,
    "totalBytes": 73678,
    "byExtension": {
      ".jpeg": 1
    },
    "sampleFileTypes": [
      ".jpeg"
    ]
  },
  {
    "category": "2. APLICACIÓN DE EXANI-I 2025",
    "fileCount": 25,
    "totalBytes": 20599946,
    "byExtension": {
      ".docx": 1,
      ".jfif": 10,
      ".jpeg": 1,
      ".pdf": 13
    },
    "sampleFileTypes": [
      ".docx",
      ".jfif",
      ".jpeg",
      ".pdf"
    ]
  },
  {
    "category": "2026_Personal",
    "fileCount": 1,
    "totalBytes": 75173,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "4. AUDITORÍAS INTERNAS 2025",
    "fileCount": 12,
    "totalBytes": 940568905,
    "byExtension": {
      ".pdf": 12
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Academia de programa técnico AP13-Campo disciplinar..xlsx",
    "fileCount": 1,
    "totalBytes": 13293,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Academia de programa técnico AQ15-Campo disciplinar..xlsx",
    "fileCount": 1,
    "totalBytes": 13869,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Academias BG24_Campo disciplinar_v4.0.xlsx",
    "fileCount": 1,
    "totalBytes": 54555,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Acciones de internacionalización e interculturalidad",
    "fileCount": 2,
    "totalBytes": 80996,
    "byExtension": {
      ".xlsx": 2
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "BACH 16 TERMINARON.xlsx",
    "fileCount": 1,
    "totalBytes": 10098,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Bachilleratos con áreas técnicas e.pptx",
    "fileCount": 1,
    "totalBytes": 44488,
    "byExtension": {
      ".pptx": 1
    },
    "sampleFileTypes": [
      ".pptx"
    ]
  },
  {
    "category": "CAMPO DISCIPLINAR BG24.pdf",
    "fileCount": 1,
    "totalBytes": 99191,
    "byExtension": {
      ".pdf": 1
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Campos Disciplinarios (Técnico Analista Químico).docx",
    "fileCount": 1,
    "totalBytes": 18761,
    "byExtension": {
      ".docx": 1
    },
    "sampleFileTypes": [
      ".docx"
    ]
  },
  {
    "category": "Campos Disciplinarios AP 13 (Analista programador).docx",
    "fileCount": 1,
    "totalBytes": 18687,
    "byExtension": {
      ".docx": 1
    },
    "sampleFileTypes": [
      ".docx"
    ]
  },
  {
    "category": "CONCENTRADO_ABANDONO ESCOLAR _SEP 2025.xlsx",
    "fileCount": 1,
    "totalBytes": 175712,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Concurso de conocimientos 2025.jpeg",
    "fileCount": 1,
    "totalBytes": 287809,
    "byExtension": {
      ".jpeg": 1
    },
    "sampleFileTypes": [
      ".jpeg"
    ]
  },
  {
    "category": "Concurso de Programación para Mujeres.jpeg",
    "fileCount": 1,
    "totalBytes": 84618,
    "byExtension": {
      ".jpeg": 1
    },
    "sampleFileTypes": [
      ".jpeg"
    ]
  },
  {
    "category": "Concursos Académicos (ciencias, matemáticas, robótica, entre otras).",
    "fileCount": 2,
    "totalBytes": 301159,
    "byExtension": {
      ".docx": 1,
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".docx",
      ".xlsx"
    ]
  },
  {
    "category": "CONSTANCIAS B16",
    "fileCount": 4,
    "totalBytes": 1196345,
    "byExtension": {
      ".pdf": 4
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Convocatoria SEMS",
    "fileCount": 1,
    "totalBytes": 10037,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "DATOS  PLANTELES Y BUZÓN UCOL.xlsx",
    "fileCount": 1,
    "totalBytes": 9390,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "De Pedro Palomares Andrea  ANALISTA QUÍMICO.pdf",
    "fileCount": 1,
    "totalBytes": 609802,
    "byExtension": {
      ".pdf": 1
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "DESARROLLO Y FORMACION INTEGRAL -PARTICIPANTES EN ACTIVIDADES DE DESARROLLO Y FORMACIÓN INTEGRAL.xlsx",
    "fileCount": 1,
    "totalBytes": 11723,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Espacio común EMS",
    "fileCount": 1,
    "totalBytes": 19404,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Estrategia en el aula, prevención de adicciones",
    "fileCount": 17,
    "totalBytes": 3487894,
    "byExtension": {
      ".jfif": 13,
      ".jpg": 3,
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".jfif",
      ".jpg",
      ".xlsx"
    ]
  },
  {
    "category": "Estrategias para combatir el abandono escolar.xlsx",
    "fileCount": 1,
    "totalBytes": 9682,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "EVALUACIONES",
    "fileCount": 2,
    "totalBytes": 972741,
    "byExtension": {
      ".pdf": 2
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Evidencias",
    "fileCount": 3,
    "totalBytes": 692087,
    "byExtension": {
      ".jpeg": 3
    },
    "sampleFileTypes": [
      ".jpeg"
    ]
  },
  {
    "category": "Exámenes aprobados para titulación ",
    "fileCount": 5,
    "totalBytes": 42688826,
    "byExtension": {
      ".pdf": 4,
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".pdf",
      ".xlsx"
    ]
  },
  {
    "category": "FAC CIVIL",
    "fileCount": 1,
    "totalBytes": 262329,
    "byExtension": {
      ".pdf": 1
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "FCQ",
    "fileCount": 9,
    "totalBytes": 2360857,
    "byExtension": {
      ".pdf": 9
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Feb_Ago_2026",
    "fileCount": 2,
    "totalBytes": 1263666,
    "byExtension": {
      ".pdf": 2
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "FIME",
    "fileCount": 1,
    "totalBytes": 262313,
    "byExtension": {
      ".pdf": 1
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Formación_apoyo académico.xlsx",
    "fileCount": 1,
    "totalBytes": 22509,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Formación_docente.xlsx",
    "fileCount": 1,
    "totalBytes": 22090,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Formato conformación de academias por plantel.xlsx",
    "fileCount": 1,
    "totalBytes": 33506,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Formato de cronograma de academia de plantel.xlsx",
    "fileCount": 1,
    "totalBytes": 10548,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "formato media superior.xlsx",
    "fileCount": 1,
    "totalBytes": 18610,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "García de los Santos Ulises Yael ANALISTA QUÍMICO.pdf",
    "fileCount": 1,
    "totalBytes": 1242510,
    "byExtension": {
      ".pdf": 1
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Homero Rafael Orendain Torres",
    "fileCount": 2,
    "totalBytes": 1434477,
    "byExtension": {
      ".pdf": 2
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "HUGO CÉSAR PONCE SUÁREZ.pdf",
    "fileCount": 1,
    "totalBytes": 273023,
    "byExtension": {
      ".pdf": 1
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "HUGO CÉSAR PONCE SUÁREZ1.pdf",
    "fileCount": 1,
    "totalBytes": 272680,
    "byExtension": {
      ".pdf": 1
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Idiomas.xlsx",
    "fileCount": 1,
    "totalBytes": 9095,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "INDICADOR DE TITULACION 2025.xlsx",
    "fileCount": 1,
    "totalBytes": 53705,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "La ciencia en los bachilleratos universitarios",
    "fileCount": 2,
    "totalBytes": 61639,
    "byExtension": {
      ".docx": 1,
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".docx",
      ".xlsx"
    ]
  },
  {
    "category": "Loro Matemático 2025..jpeg",
    "fileCount": 1,
    "totalBytes": 91099,
    "byExtension": {
      ".jpeg": 1
    },
    "sampleFileTypes": [
      ".jpeg"
    ]
  },
  {
    "category": "Loro Matemático 2025.jpeg",
    "fileCount": 1,
    "totalBytes": 107615,
    "byExtension": {
      ".jpeg": 1
    },
    "sampleFileTypes": [
      ".jpeg"
    ]
  },
  {
    "category": "Martínez Montaño Axel Yael ANALISTA QUÍMICO.pdf",
    "fileCount": 1,
    "totalBytes": 609315,
    "byExtension": {
      ".pdf": 1
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Memorias de Servicio Social Constitucional ",
    "fileCount": 11,
    "totalBytes": 14479581,
    "byExtension": {
      ".pdf": 11
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "MUNCOL",
    "fileCount": 2,
    "totalBytes": 1007973,
    "byExtension": {
      ".pdf": 1,
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".pdf",
      ".xlsx"
    ]
  },
  {
    "category": "NIVELACION ACADEMICA_DICIEMBRE 2024- ENERO 2025.xlsx",
    "fileCount": 1,
    "totalBytes": 91554,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "NIVELACION ACADEMICA_junio- agosto 2025.xlsx",
    "fileCount": 1,
    "totalBytes": 91306,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "PERSONAL PLANTEL_2025.xlsx",
    "fileCount": 1,
    "totalBytes": 123252,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Programa de Alfabetización MONAE",
    "fileCount": 1,
    "totalBytes": 10482,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Prácticas de Laboratorios",
    "fileCount": 6,
    "totalBytes": 470639,
    "byExtension": {
      ".pdf": 1,
      ".xlsx": 5
    },
    "sampleFileTypes": [
      ".pdf",
      ".xlsx"
    ]
  },
  {
    "category": "Reactivos de Laboratorios",
    "fileCount": 8,
    "totalBytes": 19735587,
    "byExtension": {
      ".pdf": 8
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Red de apoyo académico.xlsx",
    "fileCount": 1,
    "totalBytes": 11213,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "RED DE APOYO.pdf",
    "fileCount": 1,
    "totalBytes": 2507273,
    "byExtension": {
      ".pdf": 1
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Registro interesados manuales inglés.xlsx",
    "fileCount": 1,
    "totalBytes": 193530,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "RESULTADOS EXANI-I 2024",
    "fileCount": 418,
    "totalBytes": 18279384,
    "byExtension": {
      ".pdf": 418
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "RESULTADOS EXANI-I 2025",
    "fileCount": 394,
    "totalBytes": 16457251,
    "byExtension": {
      ".pdf": 394
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Seguimiento a proyectos de investigación en planteles.xlsx",
    "fileCount": 1,
    "totalBytes": 11709,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "Seguimiento capacitación en materia de género planteles.xlsx",
    "fileCount": 1,
    "totalBytes": 11063,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  },
  {
    "category": "SEM AGOSTO 2025 - ENERO 2026",
    "fileCount": 2,
    "totalBytes": 1196626,
    "byExtension": {
      ".pdf": 2
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Sem feb-jul25",
    "fileCount": 2,
    "totalBytes": 1275733,
    "byExtension": {
      ".pdf": 2
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "sextos semestre",
    "fileCount": 3,
    "totalBytes": 1677566,
    "byExtension": {
      ".pdf": 3
    },
    "sampleFileTypes": [
      ".pdf"
    ]
  },
  {
    "category": "Tercer Concurso de Programación.jpeg",
    "fileCount": 1,
    "totalBytes": 159684,
    "byExtension": {
      ".jpeg": 1
    },
    "sampleFileTypes": [
      ".jpeg"
    ]
  },
  {
    "category": "VIAJES DE ESTUDIO-EDUCACIÓN PERTINENTE Y DE CALIDAD.xlsx",
    "fileCount": 1,
    "totalBytes": 7677,
    "byExtension": {
      ".xlsx": 1
    },
    "sampleFileTypes": [
      ".xlsx"
    ]
  }
];

export const officialTemplateCandidates: OfficialTemplateCandidate[] = [
  {
    "indicatorCode": "1.1.1.5.1",
    "sourcePath": "Bachillerato 16/Formación Docente y Apoyo Académico/Formación_docente.xlsx",
    "planteles": [
      "Bachillerato 16"
    ],
    "classification": "official_table",
    "confidence": "detected-code",
    "headerRows": [
      [
        "Nombre del evento",
        "Modalidad",
        "Competencias desarrolladas",
        "Población docente NMS"
      ]
    ]
  },
  {
    "indicatorCode": "1.1.1.3.2",
    "sourcePath": "Bachillerato 16/Formación Docente y Apoyo Académico/Formación_docente.xlsx",
    "planteles": [
      "Bachillerato 16"
    ],
    "classification": "official_table",
    "confidence": "detected-code",
    "headerRows": [
      [
        "Nombre del evento",
        "Modalidad",
        "Competencias desarrolladas",
        "Población docente NMS"
      ]
    ]
  },
  {
    "indicatorCode": "1.1.1.3.3",
    "sourcePath": "Bachillerato 16/Formación Docente y Apoyo Académico/Formación_docente.xlsx",
    "planteles": [
      "Bachillerato 16"
    ],
    "classification": "official_table",
    "confidence": "detected-code",
    "headerRows": [
      [
        "Nombre del evento",
        "Modalidad",
        "Competencias desarrolladas",
        "Población docente NMS"
      ]
    ]
  },
  {
    "indicatorCode": "1.1.3.0.3",
    "sourcePath": "Bachillerato 16/Programas Interinstitucionales/Estrategia en el aula, prevención de adicciones/JORNADA POR LA PAZ Y CONTRA LAS ADICCIONES FEB-AGO25.xlsx",
    "planteles": [
      "Bachillerato 16"
    ],
    "classification": "official_table",
    "confidence": "detected-code",
    "headerRows": [
      [
        "PLANTEL",
        "NOMBRE DE LA ACTIVIDAD REALIZADA",
        "CANTIDAD DE PARTICIPANTES"
      ]
    ]
  },
  {
    "indicatorCode": "1.1.3.0.3",
    "sourcePath": "Bachillerato 16/Programas Interinstitucionales/MUNCOL/MUNCOL.xlsx",
    "planteles": [
      "Bachillerato 16"
    ],
    "classification": "official_table",
    "confidence": "detected-code",
    "headerRows": [
      [
        "PLANTEL",
        "NOMBRE DEL ALUMNADO PARTICIPANTE",
        "NOMBRE DEL PROFESORADO ACOMPAÑANTE",
        "CANTIDAD DE ALUMNOS PARTICIPANTES"
      ],
      [
        "HOMBRES",
        "MUJERES"
      ]
    ]
  },
  {
    "indicatorCode": "1.1.3.0.3",
    "sourcePath": "Bachillerato 16/Programas Interinstitucionales/Programa de Alfabetización MONAE/Proyecto SEMS Alfabetización y Educación Validación de alumnos.xlsx",
    "planteles": [
      "Bachillerato 16"
    ],
    "classification": "official_table",
    "confidence": "detected-code",
    "headerRows": [
      [
        "PLANTEL",
        "NOMBRE DEL ALUMNO"
      ]
    ]
  },
  {
    "indicatorCode": "1.1.1.5.2",
    "sourcePath": "Bachillerato 16/Formación Docente y Apoyo Académico/Formación_apoyo académico.xlsx",
    "planteles": [
      "Bachillerato 16"
    ],
    "classification": "official_table",
    "confidence": "detected-code",
    "headerRows": [
      [
        "Nombre del evento",
        "Modalidad",
        "Competencias desarrolladas"
      ]
    ]
  },
  {
    "indicatorCode": "1.1.3.0.3",
    "sourcePath": "Bachillerato 16/Viajes de Estudio/VIAJES DE ESTUDIO-EDUCACIÓN PERTINENTE Y DE CALIDAD.xlsx",
    "planteles": [
      "Bachillerato 16"
    ],
    "classification": "official_table",
    "confidence": "detected-code",
    "headerRows": [
      [
        "Docentes",
        "Nombre del lugar visitado:",
        "Descripción del impacto académico"
      ],
      [
        "Mujer",
        "Hombre",
        "Mujer",
        "Hombre"
      ]
    ]
  },
  {
    "indicatorCode": "1.1.3.0.3",
    "sourcePath": "Bachillerato 16/Programas Interinstitucionales/Convocatoria SEMS/Convocatorias SEMS.xlsx",
    "planteles": [
      "Bachillerato 16"
    ],
    "classification": "official_table",
    "confidence": "detected-code",
    "headerRows": [
      [
        "PLANTEL",
        "NOMBRE DE LA CONVOCATORIA REALIZADA",
        "CANTIDAD DE PARTICIPANTES",
        "CANTIDAD DE ALUMNOS PARTICIPANTES"
      ],
      [
        "DOCENTES",
        "HOMBRES",
        "MUJERES"
      ]
    ]
  },
  {
    "indicatorCode": "1.1.3.0.3",
    "sourcePath": "Bachillerato 16/Actividades de Desarrollo y Formación Integral/DESARROLLO Y FORMACION INTEGRAL -PARTICIPANTES EN ACTIVIDADES DE DESARROLLO Y FORMACIÓN INTEGRAL.xlsx",
    "planteles": [
      "Bachillerato 16"
    ],
    "classification": "matrix_gender_totals",
    "confidence": "detected-code",
    "headerRows": [
      [
        "Nombre de la Actividad",
        "Total de actividades",
        "Matrícula total"
      ],
      [
        "Actividades de desarrollo",
        "Actividades de formación integral",
        "Mujer",
        "Hombre",
        "Total"
      ],
      [
        "Mujer",
        "Hombre",
        "Total"
      ]
    ]
  },
  {
    "indicatorCode": "1.1.4.4.4",
    "sourcePath": "Bachillerato 16/Internacionalización e Interculturalidad/Acciones de internacionalización e interculturalidad/Formato_Indicador de internacionalización.xlsx",
    "planteles": [
      "Bachillerato 16"
    ],
    "classification": "matrix_gender_totals",
    "confidence": "detected-code",
    "headerRows": [
      [
        "Nombre del evento",
        "Nombre de facilitador(a) o ponente",
        "Población docente asistente",
        "Total global"
      ],
      [
        "No. Mujeres",
        "No. Hombres",
        "SubTotal",
        "No. Mujeres",
        "No. Hombres",
        "SubTotal",
        "No. Mujeres",
        "No. Hombres",
        "SubTotal"
      ]
    ]
  },
  {
    "indicatorCode": "1.1.2.1.8",
    "sourcePath": "Bachillerato 16/Titulación/INDICADOR DE TITULACION 2025.xlsx",
    "planteles": [
      "Bachillerato 16"
    ],
    "classification": "matrix_gender_totals",
    "confidence": "detected-code",
    "headerRows": [
      [
        "Plantel",
        "Programa Educativo",
        "Matrícula de primer ingreso de la misma cohorte (agosto 2021) de Opciones Técnicas"
      ],
      [
        "Mujeres",
        "Hombres",
        "Total",
        "Mujeres",
        "Hombres",
        "Total"
      ]
    ]
  }
];

export const officialWorkbookSummaries: OfficialWorkbookSummary[] = [
  {
    "id": "73cbde41e8ec6d30",
    "sourceLabel": "BACH 16 TERMINARON.xlsx",
    "sourcePathHash": "73cbde41e8ec6d3004af8a213cfdd269f9cc74afe5fb1be833e6f9f32faad218",
    "category": "BACH 16 TERMINARON.xlsx",
    "sizeBytes": 10098,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 12,
        "columnsObserved": 4,
        "sampleHeaders": [
          "NOMBRE",
          "CORREO"
        ],
        "headerRows": [
          [
            "NOMBRE",
            "CORREO"
          ]
        ],
        "numericCells": 11,
        "textCells": 29,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "12f38bb94949936f",
    "sourceLabel": "formato media superior.xlsx",
    "sourcePathHash": "12f38bb94949936fb34d7784e3b8325338d34a062b6e42788a8693bea09253f4",
    "category": "formato media superior.xlsx",
    "sizeBytes": 18610,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 23,
        "columnsObserved": 10,
        "sampleHeaders": [
          "PLANTEL",
          "UBICACIÓN EN EL PLANTEL"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "UBICACIÓN EN EL PLANTEL"
          ]
        ],
        "numericCells": 19,
        "textCells": 81,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "1d310056946a0419",
    "sourceLabel": "Seguimiento capacitación en materia de género planteles.xlsx",
    "sourcePathHash": "1d310056946a0419ad0bfa2f65b061fbaecdcce8e164a1bc9313ed7a60b3c454",
    "category": "Seguimiento capacitación en materia de género planteles.xlsx",
    "sizeBytes": 11063,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 5,
        "columnsObserved": 6,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE DE LA CAPACITACIÓN",
          "NÚMERO DE ALUMNOS PARTICIPANTES"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE DE LA CAPACITACIÓN",
            "NÚMERO DE ALUMNOS PARTICIPANTES"
          ]
        ],
        "numericCells": 4,
        "textCells": 12,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "6232392292322fb1",
    "sourceLabel": "Formación_docente.xlsx",
    "sourcePathHash": "6232392292322fb1ed738aff63b2565b3b7ea1d266fdda91158161c0507943a9",
    "category": "Formación_docente.xlsx",
    "sizeBytes": 22090,
    "detectedIndicatorCodes": [
      "1.1.1.3.2",
      "1.1.1.3.3",
      "1.1.1.5.1"
    ],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "DOCENTES",
        "nonEmptyRows": 18,
        "columnsObserved": 20,
        "sampleHeaders": [
          "Nombre del evento",
          "Modalidad",
          "Competencias desarrolladas",
          "Población docente NMS"
        ],
        "headerRows": [
          [
            "Nombre del evento",
            "Modalidad",
            "Competencias desarrolladas",
            "Población docente NMS"
          ]
        ],
        "numericCells": 0,
        "textCells": 40,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "9ce2f11616a7728a",
    "sourceLabel": "DATOS  PLANTELES Y BUZÓN UCOL.xlsx",
    "sourcePathHash": "9ce2f11616a7728a52cab3c1bb1e0e29f9b8ff3a8856ed486fe9f0d8027880d2",
    "category": "DATOS  PLANTELES Y BUZÓN UCOL.xlsx",
    "sizeBytes": 9390,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 2,
        "columnsObserved": 17,
        "sampleHeaders": [
          "PLANTEL",
          "CORREO ELECTRÓNICO",
          "NOMBRE DEL/LA DIRECTOR/A",
          "NOMBRE DE RESPONSABLE DE BUZÓN UCOL",
          "NO. DE TRABAJADOR DE RESPONSABLE DE BUZÓN UCOL",
          "CORREO DE RESPONSABLE DE BUZÓN UCOL"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "CORREO ELECTRÓNICO",
            "NOMBRE DEL/LA DIRECTOR/A",
            "NOMBRE DE RESPONSABLE DE BUZÓN UCOL",
            "NO. DE TRABAJADOR DE RESPONSABLE DE BUZÓN UCOL",
            "CORREO DE RESPONSABLE DE BUZÓN UCOL"
          ]
        ],
        "numericCells": 6,
        "textCells": 28,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "00c1ac54b9ef462b",
    "sourceLabel": "JORNADA POR LA PAZ Y CONTRA LAS ADICCIONES FEB-AGO25.xlsx",
    "sourcePathHash": "00c1ac54b9ef462b7b336e670ad24a9c23e4d03c9c33be31c047d21fd5545e49",
    "category": "Estrategia en el aula, prevención de adicciones",
    "sizeBytes": 9930,
    "detectedIndicatorCodes": [
      "1.1.3.0.3"
    ],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 6,
        "columnsObserved": 9,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE DE LA ACTIVIDAD REALIZADA",
          "CANTIDAD DE PARTICIPANTES"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE DE LA ACTIVIDAD REALIZADA",
            "CANTIDAD DE PARTICIPANTES"
          ]
        ],
        "numericCells": 0,
        "textCells": 14,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "d2b34193306476c0",
    "sourceLabel": "Enlaces Unidades de atención y redes de apoyo.xlsx",
    "sourcePathHash": "d2b34193306476c0443a814682158b0e1b5138ff8ddbfced65282ace0490c69c",
    "category": "Espacio común EMS",
    "sizeBytes": 19404,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 1",
      "Bachillerato 10",
      "Bachillerato 11",
      "Bachillerato 12",
      "Bachillerato 13",
      "Bachillerato 14",
      "Bachillerato 15",
      "Bachillerato 16",
      "Bachillerato 17",
      "Bachillerato 18",
      "Bachillerato 19",
      "Bachillerato 2",
      "Bachillerato 20",
      "Bachillerato 21",
      "Bachillerato 22",
      "Bachillerato 23",
      "Bachillerato 24",
      "Bachillerato 25",
      "Bachillerato 26",
      "Bachillerato 27",
      "Bachillerato 28",
      "Bachillerato 29",
      "Bachillerato 3",
      "Bachillerato 30",
      "Bachillerato 31",
      "Bachillerato 32",
      "Bachillerato 33",
      "Bachillerato 34",
      "Bachillerato 35",
      "Bachillerato 4",
      "Bachillerato 5",
      "Bachillerato 6",
      "Bachillerato 7",
      "Bachillerato 8",
      "Bachillerato 9"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 43,
        "columnsObserved": 17,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE COMPLETO",
          "CORREO ELECTRÓNICO"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE COMPLETO",
            "CORREO ELECTRÓNICO"
          ],
          [
            "Bachillerato 7",
            "becario /actividades académicas"
          ]
        ],
        "numericCells": 31,
        "textCells": 163,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "7e91e4dbbc44dc77",
    "sourceLabel": "MUNCOL.xlsx",
    "sourcePathHash": "7e91e4dbbc44dc77acd02c470b2686ee8afdc39e64523555abaf82a4c5c0a407",
    "category": "MUNCOL",
    "sizeBytes": 10312,
    "detectedIndicatorCodes": [
      "1.1.3.0.3"
    ],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 11,
        "columnsObserved": 8,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE DEL ALUMNADO PARTICIPANTE",
          "NOMBRE DEL PROFESORADO ACOMPAÑANTE",
          "CANTIDAD DE ALUMNOS PARTICIPANTES"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE DEL ALUMNADO PARTICIPANTE",
            "NOMBRE DEL PROFESORADO ACOMPAÑANTE",
            "CANTIDAD DE ALUMNOS PARTICIPANTES"
          ],
          [
            "HOMBRES",
            "MUJERES"
          ]
        ],
        "numericCells": 8,
        "textCells": 23,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "74e3fb426355e3fd",
    "sourceLabel": "Proyecto SEMS Alfabetización y Educación Validación de alumnos.xlsx",
    "sourcePathHash": "74e3fb426355e3fdc52c9f66ee567d32d38f74968d23fa14be7975b9f43e583b",
    "category": "Programa de Alfabetización MONAE",
    "sizeBytes": 10482,
    "detectedIndicatorCodes": [
      "1.1.3.0.3"
    ],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 10,
        "columnsObserved": 11,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE DEL ALUMNO"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE DEL ALUMNO"
          ]
        ],
        "numericCells": 0,
        "textCells": 21,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "0c3e7cb6ba32ee3d",
    "sourceLabel": "Formación_apoyo académico.xlsx",
    "sourcePathHash": "0c3e7cb6ba32ee3d0cf0200d48cc4b57025a3f86fd51f8bd700946835496debc",
    "category": "Formación_apoyo académico.xlsx",
    "sizeBytes": 22509,
    "detectedIndicatorCodes": [
      "1.1.1.5.2"
    ],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "PERSONAL DE APOYO",
        "nonEmptyRows": 18,
        "columnsObserved": 20,
        "sampleHeaders": [
          "Nombre del evento",
          "Modalidad",
          "Competencias desarrolladas"
        ],
        "headerRows": [
          [
            "Nombre del evento",
            "Modalidad",
            "Competencias desarrolladas"
          ]
        ],
        "numericCells": 0,
        "textCells": 40,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "e8efb8c02314dec0",
    "sourceLabel": "Seguimiento a proyectos de investigación en planteles.xlsx",
    "sourcePathHash": "e8efb8c02314dec0d4f0d0e53fddd8e0cbbf7ee96075c6af3fe64edd7ac77d05",
    "category": "Seguimiento a proyectos de investigación en planteles.xlsx",
    "sizeBytes": 11709,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 4,
        "columnsObserved": 12,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE DE PROYECTOS DE INVESTIGACIÓN",
          "NÚMERO DE ALUMNOS PARTICIPANTES"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE DE PROYECTOS DE INVESTIGACIÓN",
            "NÚMERO DE ALUMNOS PARTICIPANTES"
          ]
        ],
        "numericCells": 0,
        "textCells": 7,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "6b6822674173f7e5",
    "sourceLabel": "VIAJES DE ESTUDIO-EDUCACIÓN PERTINENTE Y DE CALIDAD.xlsx",
    "sourcePathHash": "6b6822674173f7e56896146b86805a61779d64267fca74ef9105738681504c91",
    "category": "VIAJES DE ESTUDIO-EDUCACIÓN PERTINENTE Y DE CALIDAD.xlsx",
    "sizeBytes": 7677,
    "detectedIndicatorCodes": [
      "1.1.3.0.3"
    ],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Table 1",
        "nonEmptyRows": 7,
        "columnsObserved": 6,
        "sampleHeaders": [
          "Docentes",
          "Nombre del lugar visitado:",
          "Descripción del impacto académico"
        ],
        "headerRows": [
          [
            "Docentes",
            "Nombre del lugar visitado:",
            "Descripción del impacto académico"
          ],
          [
            "Mujer",
            "Hombre",
            "Mujer",
            "Hombre"
          ]
        ],
        "numericCells": 0,
        "textCells": 16,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "55725d793fe46d49",
    "sourceLabel": "PERSONAL PLANTEL_2025.xlsx",
    "sourcePathHash": "55725d793fe46d4926c23e741c44affdea97dac68144f1f0cdcdd86f86f6c527",
    "category": "PERSONAL PLANTEL_2025.xlsx",
    "sizeBytes": 123252,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 1",
      "Bachillerato 10",
      "Bachillerato 11",
      "Bachillerato 12",
      "Bachillerato 13",
      "Bachillerato 14",
      "Bachillerato 15",
      "Bachillerato 16",
      "Bachillerato 17",
      "Bachillerato 18",
      "Bachillerato 19",
      "Bachillerato 2",
      "Bachillerato 20",
      "Bachillerato 21",
      "Bachillerato 22",
      "Bachillerato 23",
      "Bachillerato 24",
      "Bachillerato 25",
      "Bachillerato 26",
      "Bachillerato 27",
      "Bachillerato 28",
      "Bachillerato 29",
      "Bachillerato 3",
      "Bachillerato 30",
      "Bachillerato 31",
      "Bachillerato 32",
      "Bachillerato 33",
      "Bachillerato 34",
      "Bachillerato 35",
      "Bachillerato 4",
      "Bachillerato 5",
      "Bachillerato 6",
      "Bachillerato 7",
      "Bachillerato 8",
      "Bachillerato 9"
    ],
    "formulaCells": 4,
    "sheets": [
      {
        "name": "AGOSTO 2025",
        "nonEmptyRows": 24,
        "columnsObserved": 15,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE",
          "ACTIVIDAD QUE DESEMPEÑA EN PLANTEL",
          "LICENCIATURA (Anotar el nombre de la licenciatura)",
          "MAESTRÍA (Anotar el nombre de la Maestría)",
          "DOCTORADO (Anotar el nombre del Doctorado)",
          "PLANTEL"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE",
            "ACTIVIDAD QUE DESEMPEÑA EN PLANTEL",
            "LICENCIATURA (Anotar el nombre de la licenciatura)",
            "MAESTRÍA (Anotar el nombre de la Maestría)",
            "DOCTORADO (Anotar el nombre del Doctorado)",
            "PLANTEL"
          ]
        ],
        "numericCells": 17,
        "textCells": 121,
        "formulaCells": 0
      },
      {
        "name": "PERSONAL DE APOYO ACADÉMICO",
        "nonEmptyRows": 24,
        "columnsObserved": 19,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE",
          "ACTIVIDAD QUE DESEMPEÑA EN PLANTEL",
          "LICENCIATURA (Anotar el nombre de la licenciatura)",
          "MAESTRÍA (Anotar el nombre de la Maestría)",
          "DOCTORADO (Anotar el nombre del Doctorado)",
          "PLANTEL",
          "PROGRAMA EDUCATIVO"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE",
            "ACTIVIDAD QUE DESEMPEÑA EN PLANTEL",
            "LICENCIATURA (Anotar el nombre de la licenciatura)",
            "MAESTRÍA (Anotar el nombre de la Maestría)",
            "DOCTORADO (Anotar el nombre del Doctorado)",
            "PLANTEL",
            "PROGRAMA EDUCATIVO"
          ]
        ],
        "numericCells": 17,
        "textCells": 126,
        "formulaCells": 0
      },
      {
        "name": "PERSONAL DOCENTE FEB-AGO 24",
        "nonEmptyRows": 69,
        "columnsObserved": 20,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE DEL DOCENTE",
          "LICENCIATURA (Anotar el nombre de la Licenciatura)",
          "MAESTRÍA (Anotar el nombre de la Maestría)",
          "DOCTORADO (Anotar el nombre del Doctorado)",
          "CANTIDAD DE HORAS POR ASIGNATURA",
          "SEMESTRE EN QUE SE IMPARTE"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE DEL DOCENTE",
            "LICENCIATURA (Anotar el nombre de la Licenciatura)",
            "MAESTRÍA (Anotar el nombre de la Maestría)",
            "DOCTORADO (Anotar el nombre del Doctorado)",
            "CANTIDAD DE HORAS POR ASIGNATURA",
            "SEMESTRE EN QUE SE IMPARTE"
          ],
          [
            "BACHILLERATO GENERAL",
            "BACHILLERATO GENERAL"
          ],
          [
            "BACHILLERATO GENERAL",
            "TEC. ANALISTA PROGRAMADOR"
          ],
          [
            "BACHILLERATO GENERAL",
            "BACH. GRAL MODALIDAD MIXTA"
          ],
          [
            "TALLER DE LECTURA Y REDACCION II",
            "TEC. ANALISTA PROGRAMADOR"
          ],
          [
            "TALLER DE LECTURA Y REDACCION II",
            "BACHILLERATO GENERAL"
          ]
        ],
        "numericCells": 74,
        "textCells": 287,
        "formulaCells": 0
      },
      {
        "name": "PERSONAL DOCENTE AGO-23_ENE-24",
        "nonEmptyRows": 77,
        "columnsObserved": 20,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE DEL DOCENTE",
          "LICENCIATURA (Anotar el nombre de la licenciatura)",
          "MAESTRÍA (Anotar el nombre de la Maestría)",
          "DOCTORADO (Anotar el nombre del Doctorado)",
          "CANTIDAD DE HORAS POR ASIGNATURA",
          "SEMESTRE EN QUE SE IMPARTE",
          "PROGRAMA EDUCATIVO"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE DEL DOCENTE",
            "LICENCIATURA (Anotar el nombre de la licenciatura)",
            "MAESTRÍA (Anotar el nombre de la Maestría)",
            "DOCTORADO (Anotar el nombre del Doctorado)",
            "CANTIDAD DE HORAS POR ASIGNATURA",
            "SEMESTRE EN QUE SE IMPARTE",
            "PROGRAMA EDUCATIVO"
          ],
          [
            "BACHILLERATO GENERAL",
            "TEC. ANALISTA PROGRAMADOR"
          ],
          [
            "BACHILLERATO GENERAL",
            "BACH. GRAL MODALIDAD MIXTA"
          ],
          [
            "TALLER DE LECTURA Y REDACCIÓN I",
            "BACHILLERATO GENERAL"
          ],
          [
            "TALLER DE LECTURA Y REDACCIÓN I",
            "TEC. ANALISTA PROGRAMADOR"
          ]
        ],
        "numericCells": 90,
        "textCells": 330,
        "formulaCells": 0
      },
      {
        "name": "infrestructura_fisica plantel",
        "nonEmptyRows": 42,
        "columnsObserved": 22,
        "sampleHeaders": [
          "Plantel",
          "Programas Educativo",
          "Grupos",
          "Sala de docentes",
          "BACHILLERATO 1"
        ],
        "headerRows": [
          [
            "Plantel",
            "Programas Educativo",
            "Grupos",
            "Sala de docentes",
            "BACHILLERATO 1"
          ],
          [
            "Total",
            "BACHILLERATO 2"
          ],
          [
            "BACHILLERATO 16",
            "Bachillerato General",
            "Bachillerato General",
            "BACHILLERATO 3"
          ],
          [
            "Analista Programador",
            "Analista Programador",
            "BACHILLERATO 5"
          ],
          [
            "BG Modalidad mixta (Semiescolarizado)",
            "BACHILLERATO 7"
          ]
        ],
        "numericCells": 50,
        "textCells": 80,
        "formulaCells": 4
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "26a4e4bbf088bf4e",
    "sourceLabel": "Convocatorias SEMS.xlsx",
    "sourcePathHash": "26a4e4bbf088bf4e56da8b4646ef6621da7aee7585aa290456bc1c967040f65d",
    "category": "Convocatoria SEMS",
    "sizeBytes": 10037,
    "detectedIndicatorCodes": [
      "1.1.3.0.3"
    ],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 6,
        "columnsObserved": 11,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE DE LA CONVOCATORIA REALIZADA",
          "CANTIDAD DE PARTICIPANTES",
          "CANTIDAD DE ALUMNOS PARTICIPANTES"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE DE LA CONVOCATORIA REALIZADA",
            "CANTIDAD DE PARTICIPANTES",
            "CANTIDAD DE ALUMNOS PARTICIPANTES"
          ],
          [
            "DOCENTES",
            "HOMBRES",
            "MUJERES"
          ]
        ],
        "numericCells": 0,
        "textCells": 15,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "6eba7ce9c353e101",
    "sourceLabel": "DESARROLLO Y FORMACION INTEGRAL -PARTICIPANTES EN ACTIVIDADES DE DESARROLLO Y FORMACIÓN INTEGRAL.xlsx",
    "sourcePathHash": "6eba7ce9c353e101d6f2c0e14aba293e5832fc0267449ad584812c5dd88608ef",
    "category": "DESARROLLO Y FORMACION INTEGRAL -PARTICIPANTES EN ACTIVIDADES DE DESARROLLO Y FORMACIÓN INTEGRAL.xlsx",
    "sizeBytes": 11723,
    "detectedIndicatorCodes": [
      "1.1.3.0.3"
    ],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Table 1",
        "nonEmptyRows": 6,
        "columnsObserved": 12,
        "sampleHeaders": [
          "Nombre de la Actividad",
          "Total de actividades",
          "Matrícula total"
        ],
        "headerRows": [
          [
            "Nombre de la Actividad",
            "Total de actividades",
            "Matrícula total"
          ],
          [
            "Actividades de desarrollo",
            "Actividades de formación integral",
            "Mujer",
            "Hombre",
            "Total"
          ],
          [
            "Mujer",
            "Hombre",
            "Total"
          ]
        ],
        "numericCells": 0,
        "textCells": 21,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "85ff7f0aa2b4f1fc",
    "sourceLabel": "Estrategias para combatir el abandono escolar.xlsx",
    "sourcePathHash": "85ff7f0aa2b4f1fca932b4bcecfa13a460e51dc4ea6370677b5aba8a025991b8",
    "category": "Estrategias para combatir el abandono escolar.xlsx",
    "sizeBytes": 9682,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Estrategias para combatir el ab",
        "nonEmptyRows": 8,
        "columnsObserved": 5,
        "sampleHeaders": [
          "PLANTEL",
          "CANTIDAD DE ALUMNOS"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "CANTIDAD DE ALUMNOS"
          ],
          [
            "MUJERES",
            "HOMBRES",
            "TOTAL"
          ]
        ],
        "numericCells": 12,
        "textCells": 13,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "0a31f882a7e4b0fc",
    "sourceLabel": "Bachillerato 16 FEBRERO - JULIO 2026.xlsx",
    "sourcePathHash": "0a31f882a7e4b0fc547fed78811e80dbff3b9f3054e84111635bb5a66ea3bdca",
    "category": "Prácticas de Laboratorios",
    "sizeBytes": 35672,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 7,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 58,
        "columnsObserved": 30,
        "sampleHeaders": [
          "PLANTEL",
          "TOTAL GRUPOS"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "TOTAL GRUPOS"
          ]
        ],
        "numericCells": 175,
        "textCells": 519,
        "formulaCells": 7
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "c7b22bc5c5aca5d8",
    "sourceLabel": "Cronograma del para la promoción del aprendizaje intercultural, internacional y-o globa.xlsx",
    "sourcePathHash": "c7b22bc5c5aca5d869fe20c86e77afb5bf9e78150c457ea82f18095fd2453f8d",
    "category": "Acciones de internacionalización e interculturalidad",
    "sizeBytes": 59099,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "FEBRERO – JULIO 2024",
        "nonEmptyRows": 11,
        "columnsObserved": 6,
        "sampleHeaders": [
          "Plantel:",
          "Bachillerato 16"
        ],
        "headerRows": [
          [
            "Plantel:",
            "Bachillerato 16"
          ],
          [
            "Nombre de la actividad",
            "Descripción",
            "Modalidad"
          ]
        ],
        "numericCells": 2,
        "textCells": 23,
        "formulaCells": 0
      },
      {
        "name": "AGOSTO 2024 – ENERO 2025",
        "nonEmptyRows": 14,
        "columnsObserved": 6,
        "sampleHeaders": [
          "Plantel:",
          "Bachillerato 16"
        ],
        "headerRows": [
          [
            "Plantel:",
            "Bachillerato 16"
          ],
          [
            "Nombre de la actividad",
            "Descripción",
            "Modalidad"
          ],
          [
            "Actividades Complementarias",
            "Programación de actividades para el estudiantado, en las cuales le permitan adquirir herramientas que las pueda implementar en su día a día."
          ]
        ],
        "numericCells": 1,
        "textCells": 46,
        "formulaCells": 0
      },
      {
        "name": "FEBRERO – JULIO 2025",
        "nonEmptyRows": 13,
        "columnsObserved": 6,
        "sampleHeaders": [
          "Plantel:",
          "Bachillerato 16"
        ],
        "headerRows": [
          [
            "Plantel:",
            "Bachillerato 16"
          ],
          [
            "Nombre de la actividad",
            "Descripción",
            "Modalidad"
          ]
        ],
        "numericCells": 2,
        "textCells": 40,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "a574f0629c9a9b76",
    "sourceLabel": "Formato_Indicador de internacionalización.xlsx",
    "sourcePathHash": "a574f0629c9a9b76d1b57924ce9552e1d8ac2da81d610f1761aea1a3191633e4",
    "category": "Acciones de internacionalización e interculturalidad",
    "sizeBytes": 21897,
    "detectedIndicatorCodes": [
      "1.1.4.4.4"
    ],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 50,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 18,
        "columnsObserved": 13,
        "sampleHeaders": [
          "Nombre del evento",
          "Nombre de facilitador(a) o ponente",
          "Población docente asistente",
          "Total global"
        ],
        "headerRows": [
          [
            "Nombre del evento",
            "Nombre de facilitador(a) o ponente",
            "Población docente asistente",
            "Total global"
          ],
          [
            "No. Mujeres",
            "No. Hombres",
            "SubTotal",
            "No. Mujeres",
            "No. Hombres",
            "SubTotal",
            "No. Mujeres",
            "No. Hombres",
            "SubTotal"
          ]
        ],
        "numericCells": 70,
        "textCells": 21,
        "formulaCells": 50
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "2b17f9c0e2713252",
    "sourceLabel": "INDICADOR DE TITULACION 2025.xlsx",
    "sourcePathHash": "2b17f9c0e271325211cc47637cc9454455cd064c8cd7aa74b55561fb20a7c2b1",
    "category": "INDICADOR DE TITULACION 2025.xlsx",
    "sizeBytes": 53705,
    "detectedIndicatorCodes": [
      "1.1.2.1.8"
    ],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 15,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 13,
        "columnsObserved": 10,
        "sampleHeaders": [
          "Plantel",
          "Programa Educativo",
          "Matrícula de primer ingreso de la misma cohorte (agosto 2021) de Opciones Técnicas"
        ],
        "headerRows": [
          [
            "Plantel",
            "Programa Educativo",
            "Matrícula de primer ingreso de la misma cohorte (agosto 2021) de Opciones Técnicas"
          ],
          [
            "Mujeres",
            "Hombres",
            "Total",
            "Mujeres",
            "Hombres",
            "Total"
          ]
        ],
        "numericCells": 12,
        "textCells": 22,
        "formulaCells": 15
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "55ef8c78c5188620",
    "sourceLabel": "LA CIENCIA EN LOS BACHILLERATOS UNIVERSITARIOS.xlsx",
    "sourcePathHash": "55ef8c78c5188620d3c506e720d9a493f761b3dd1b125f87f8bc9bf13411cccc",
    "category": "La ciencia en los bachilleratos universitarios",
    "sizeBytes": 24609,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 5,
        "columnsObserved": 10,
        "sampleHeaders": [
          "BACHILLERATO",
          "NOMBRE DEL EVENTO"
        ],
        "headerRows": [
          [
            "BACHILLERATO",
            "NOMBRE DEL EVENTO"
          ],
          [
            "MUJERES",
            "HOMBRES",
            "TOTAL",
            "MUJERES",
            "HOMBRES",
            "TOTAL"
          ]
        ],
        "numericCells": 0,
        "textCells": 15,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "9129d9b3b186f6e2",
    "sourceLabel": "CONCURSOS ACADEMICOS.xlsx",
    "sourcePathHash": "9129d9b3b186f6e286c3c4bf05ca4e8e0cc0d9b94cc1a326ee6c078d0184334e",
    "category": "Concursos Académicos (ciencias, matemáticas, robótica, entre otras).",
    "sizeBytes": 26104,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 11,
        "columnsObserved": 17,
        "sampleHeaders": [
          "BACHILLERATO",
          "NOMBRE DEL EVENTO"
        ],
        "headerRows": [
          [
            "BACHILLERATO",
            "NOMBRE DEL EVENTO"
          ],
          [
            "MUJERES",
            "HOMBRES",
            "TOTAL",
            "MUJERES",
            "HOMBRES",
            "TOTAL"
          ]
        ],
        "numericCells": 0,
        "textCells": 22,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "628f230d09688315",
    "sourceLabel": "NIVELACION ACADEMICA_junio- agosto 2025.xlsx",
    "sourcePathHash": "628f230d09688315ca74ea75545728653603b2f0a966ea6fb3dfcd2fd08fea8b",
    "category": "NIVELACION ACADEMICA_junio- agosto 2025.xlsx",
    "sizeBytes": 91306,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 36,
    "sheets": [
      {
        "name": "ORDINARIO",
        "nonEmptyRows": 15,
        "columnsObserved": 19,
        "sampleHeaders": [
          "PLANTEL",
          "MATRICULA",
          "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
          "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
          "CANTIDAD ESTUDIANTES QUE ASISTIERON"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "MATRICULA",
            "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
            "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
            "CANTIDAD ESTUDIANTES QUE ASISTIERON"
          ],
          [
            "PLANTEL",
            "MATRICULA",
            "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
            "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
            "CANTIDAD ESTUDIANTES QUE ASISTIERON"
          ]
        ],
        "numericCells": 50,
        "textCells": 47,
        "formulaCells": 12
      },
      {
        "name": "EXTRAORDINARIO",
        "nonEmptyRows": 15,
        "columnsObserved": 19,
        "sampleHeaders": [
          "PLANTEL",
          "MATRICULA",
          "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
          "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
          "CANTIDAD ESTUDIANTES QUE ASISTIERON"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "MATRICULA",
            "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
            "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
            "CANTIDAD ESTUDIANTES QUE ASISTIERON"
          ],
          [
            "PLANTEL",
            "MATRICULA",
            "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
            "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
            "CANTIDAD ESTUDIANTES QUE ASISTIERON"
          ]
        ],
        "numericCells": 50,
        "textCells": 47,
        "formulaCells": 12
      },
      {
        "name": "REGULARIZACIÓN",
        "nonEmptyRows": 15,
        "columnsObserved": 19,
        "sampleHeaders": [
          "PLANTEL",
          "MATRICULA",
          "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
          "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
          "CANTIDAD ESTUDIANTES QUE ASISTIERON"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "MATRICULA",
            "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
            "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
            "CANTIDAD ESTUDIANTES QUE ASISTIERON"
          ],
          [
            "PLANTEL",
            "MATRICULA",
            "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
            "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
            "CANTIDAD ESTUDIANTES QUE ASISTIERON"
          ]
        ],
        "numericCells": 50,
        "textCells": 47,
        "formulaCells": 12
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "cc792a5f37cbbdd5",
    "sourceLabel": "CONCENTRADO_ABANDONO ESCOLAR _SEP 2025.xlsx",
    "sourcePathHash": "cc792a5f37cbbdd534065efcc40c068d8cf5193ec560c4b71442bb93ed3d5f6a",
    "category": "CONCENTRADO_ABANDONO ESCOLAR _SEP 2025.xlsx",
    "sizeBytes": 175712,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 76,
    "sheets": [
      {
        "name": "REPORTE ENERO 2025",
        "nonEmptyRows": 14,
        "columnsObserved": 30,
        "sampleHeaders": [
          "PLANTEL",
          "PROGRAMA EDUCATIVO",
          "NO. DE ESTUDIANTES POR TIPO DE BAJA ACADÉMICA (Separación del programa en el que el estudiante se encuentre inscrito. Art. 37)"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "PROGRAMA EDUCATIVO",
            "NO. DE ESTUDIANTES POR TIPO DE BAJA ACADÉMICA (Separación del programa en el que el estudiante se encuentre inscrito. Art. 37)"
          ],
          [
            "SUSPENSIÓN DEFINITIVA DEL PLANTEL O INSTITUCIÓN",
            "SUBTOTAL"
          ]
        ],
        "numericCells": 9,
        "textCells": 57,
        "formulaCells": 38
      },
      {
        "name": "REPORTE JULIO- AGOSTO 2025",
        "nonEmptyRows": 14,
        "columnsObserved": 30,
        "sampleHeaders": [
          "PLANTEL",
          "PROGRAMA EDUCATIVO",
          "NO. DE ESTUDIANTES POR TIPO DE BAJA ACADÉMICA (Separación del programa en el que el estudiante se encuentre inscrito. Art. 37)"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "PROGRAMA EDUCATIVO",
            "NO. DE ESTUDIANTES POR TIPO DE BAJA ACADÉMICA (Separación del programa en el que el estudiante se encuentre inscrito. Art. 37)"
          ],
          [
            "SUSPENSIÓN DEFINITIVA DEL PLANTEL O INSTITUCIÓN",
            "SUBTOTAL"
          ]
        ],
        "numericCells": 66,
        "textCells": 57,
        "formulaCells": 38
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "ce2296aba817351d",
    "sourceLabel": "Red de apoyo académico.xlsx",
    "sourcePathHash": "ce2296aba817351dc4c477e7275246a4087af8815f3977d780b3ac05171559c1",
    "category": "Red de apoyo académico.xlsx",
    "sizeBytes": 11213,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 11,
        "columnsObserved": 7,
        "sampleHeaders": [
          "Nombre de la actividad",
          "Responsable",
          "Cantidad de participantes",
          "Periodo de realización"
        ],
        "headerRows": [
          [
            "Nombre de la actividad",
            "Responsable",
            "Cantidad de participantes",
            "Periodo de realización"
          ]
        ],
        "numericCells": 10,
        "textCells": 28,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "19f01a78e63b03ff",
    "sourceLabel": "NIVELACION ACADEMICA_DICIEMBRE 2024- ENERO 2025.xlsx",
    "sourcePathHash": "19f01a78e63b03ffd22b2c6bc5e28462fa904ce2c916b4116813ed08e13bc50e",
    "category": "NIVELACION ACADEMICA_DICIEMBRE 2024- ENERO 2025.xlsx",
    "sizeBytes": 91554,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 45,
    "sheets": [
      {
        "name": "ORDINARIO",
        "nonEmptyRows": 16,
        "columnsObserved": 19,
        "sampleHeaders": [
          "PLANTEL",
          "MATRICULA",
          "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
          "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
          "CANTIDAD ESTUDIANTES QUE ASISTIERON"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "MATRICULA",
            "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
            "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
            "CANTIDAD ESTUDIANTES QUE ASISTIERON"
          ],
          [
            "PLANTEL",
            "MATRICULA",
            "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
            "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
            "CANTIDAD ESTUDIANTES QUE ASISTIERON"
          ]
        ],
        "numericCells": 47,
        "textCells": 48,
        "formulaCells": 15
      },
      {
        "name": "EXTRAORDINARIO",
        "nonEmptyRows": 15,
        "columnsObserved": 19,
        "sampleHeaders": [
          "PLANTEL",
          "MATRICULA",
          "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
          "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
          "CANTIDAD ESTUDIANTES QUE ASISTIERON"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "MATRICULA",
            "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
            "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
            "CANTIDAD ESTUDIANTES QUE ASISTIERON"
          ],
          [
            "PLANTEL",
            "MATRICULA",
            "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
            "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
            "CANTIDAD ESTUDIANTES QUE ASISTIERON"
          ]
        ],
        "numericCells": 47,
        "textCells": 47,
        "formulaCells": 15
      },
      {
        "name": "REGULARIZACIÓN",
        "nonEmptyRows": 15,
        "columnsObserved": 19,
        "sampleHeaders": [
          "PLANTEL",
          "MATRICULA",
          "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
          "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
          "CANTIDAD ESTUDIANTES QUE ASISTIERON"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "MATRICULA",
            "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
            "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
            "CANTIDAD ESTUDIANTES QUE ASISTIERON"
          ],
          [
            "PLANTEL",
            "MATRICULA",
            "No. ESTUDIANTES EN ORDINARIO POR GRUPO (Se contabilizará por estudiante, independenientemente la cantidad de materias que vaya a presentar)",
            "No. ASIGNATURAS CON ALUMNOS EN ORDINARIO",
            "CANTIDAD ESTUDIANTES QUE ASISTIERON"
          ]
        ],
        "numericCells": 47,
        "textCells": 47,
        "formulaCells": 15
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "0ce86d236429d8dc",
    "sourceLabel": "Alumnos que realizaron examen de conocImientos para titulación.xlsx",
    "sourcePathHash": "0ce86d236429d8dc8dcf524266095b8e91fa1961e1d81636f70866017fdc004a",
    "category": "Exámenes aprobados para titulación ",
    "sizeBytes": 14930,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 92,
        "columnsObserved": 7,
        "sampleHeaders": [
          "NOMBRE",
          "GRUPO"
        ],
        "headerRows": [
          [
            "NOMBRE",
            "GRUPO"
          ]
        ],
        "numericCells": 169,
        "textCells": 282,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "1e107d9fd544c3f0",
    "sourceLabel": "PERSONAL _PLANTEL_2026.xlsx",
    "sourcePathHash": "1e107d9fd544c3f0002d1819b6c11599632d7244761d8426744b4e4d347b2583",
    "category": "2026_Personal",
    "sizeBytes": 75173,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "PERSONAL DE APOYO ACADÉMICO",
        "nonEmptyRows": 26,
        "columnsObserved": 19,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE",
          "ACTIVIDAD QUE DESEMPEÑA EN PLANTEL",
          "LICENCIATURA (Anotar el nombre de la licenciatura)",
          "MAESTRÍA (Anotar el nombre de la Maestría)",
          "DOCTORADO (Anotar el nombre del Doctorado)",
          "PLANTEL",
          "PROGRAMA EDUCATIVO"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE",
            "ACTIVIDAD QUE DESEMPEÑA EN PLANTEL",
            "LICENCIATURA (Anotar el nombre de la licenciatura)",
            "MAESTRÍA (Anotar el nombre de la Maestría)",
            "DOCTORADO (Anotar el nombre del Doctorado)",
            "PLANTEL",
            "PROGRAMA EDUCATIVO"
          ]
        ],
        "numericCells": 18,
        "textCells": 129,
        "formulaCells": 0
      },
      {
        "name": "PERSONAL DOCENTE_2026",
        "nonEmptyRows": 42,
        "columnsObserved": 17,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE DEL DOCENTE",
          "LICENCIATURA (Anotar el nombre de la Licenciatura)",
          "MAESTRÍA (Anotar el nombre de la Maestría)",
          "DOCTORADO (Anotar el nombre del Doctorado)",
          "PRIMER SEMESTRE ASIGNATURAS (LLENAR UNA ASIGNATURA EN CADA FILA)",
          "SEGUNDO SEMESTRE ASIGNATURAS (LLENAR UNA ASIGNATURA EN CADA FILA)",
          "TERCER SEMESTRE ASIGNATURAS (LLENAR UNA ASIGNATURA EN CADA FILA)",
          "CUARTO SEMESTRE ASIGNATURAS (LLENAR UNA ASIGNATURA EN CADA FILA)",
          "SEXTO SEMESTRE (LLENAR UNA ASIGNATURA EN CADA FILA)"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE DEL DOCENTE",
            "LICENCIATURA (Anotar el nombre de la Licenciatura)",
            "MAESTRÍA (Anotar el nombre de la Maestría)",
            "DOCTORADO (Anotar el nombre del Doctorado)",
            "PRIMER SEMESTRE ASIGNATURAS (LLENAR UNA ASIGNATURA EN CADA FILA)",
            "SEGUNDO SEMESTRE ASIGNATURAS (LLENAR UNA ASIGNATURA EN CADA FILA)",
            "TERCER SEMESTRE ASIGNATURAS (LLENAR UNA ASIGNATURA EN CADA FILA)",
            "CUARTO SEMESTRE ASIGNATURAS (LLENAR UNA ASIGNATURA EN CADA FILA)",
            "SEXTO SEMESTRE (LLENAR UNA ASIGNATURA EN CADA FILA)"
          ]
        ],
        "numericCells": 34,
        "textCells": 62,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "f40aa65606125bdc",
    "sourceLabel": "4) Bachillerato 16 AGOSTO 2025 -ENERO 2026.xlsx",
    "sourcePathHash": "f40aa65606125bdc77fe4dadd215a4fbe4b5bda0d367faa4b7d9bd88b48ac033",
    "category": "Prácticas de Laboratorios",
    "sizeBytes": 34861,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 7,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 50,
        "columnsObserved": 30,
        "sampleHeaders": [
          "PLANTEL",
          "TOTAL GRUPOS"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "TOTAL GRUPOS"
          ]
        ],
        "numericCells": 333,
        "textCells": 827,
        "formulaCells": 7
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "33e7a5795b042171",
    "sourceLabel": "1) Bachillerato 16 FEBRERO- AGOSTO 2024.xlsx",
    "sourcePathHash": "33e7a5795b042171368bdb633f2c361211009fa33811c6a689ad4a25d5241ebc",
    "category": "Prácticas de Laboratorios",
    "sizeBytes": 34858,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 7,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 58,
        "columnsObserved": 30,
        "sampleHeaders": [
          "PLANTEL",
          "TOTAL GRUPOS"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "TOTAL GRUPOS"
          ]
        ],
        "numericCells": 396,
        "textCells": 961,
        "formulaCells": 7
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "697e06cf6a6be1c1",
    "sourceLabel": "Academia de programa técnico AQ15-Campo disciplinar..xlsx",
    "sourcePathHash": "697e06cf6a6be1c1271bb5ea945bc7bf7d26f40c85d869480db43f8cac9cb123",
    "category": "Academia de programa técnico AQ15-Campo disciplinar..xlsx",
    "sizeBytes": 13869,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 57,
        "columnsObserved": 5,
        "sampleHeaders": [
          "Nombre del docente",
          "Correo electrónico institucional"
        ],
        "headerRows": [
          [
            "Nombre del docente",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ]
        ],
        "numericCells": 64,
        "textCells": 161,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "bd626f5d28a91826",
    "sourceLabel": "Academia de programa técnico AP13-Campo disciplinar..xlsx",
    "sourcePathHash": "bd626f5d28a91826986ae9f8c561007850a495074ed89445cf7624e4f16723d7",
    "category": "Academia de programa técnico AP13-Campo disciplinar..xlsx",
    "sizeBytes": 13293,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 49,
        "columnsObserved": 5,
        "sampleHeaders": [
          "Nombre del docente",
          "Correo electrónico institucional"
        ],
        "headerRows": [
          [
            "Nombre del docente",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ]
        ],
        "numericCells": 47,
        "textCells": 136,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "6bb983c1e5dd64eb",
    "sourceLabel": "3) Bachillerato 16 FEBRERO - JULIO 2025.xlsx",
    "sourcePathHash": "6bb983c1e5dd64eb6778dd762a7396b54bae42033c6c4d99cdb2b7eac3828330",
    "category": "Prácticas de Laboratorios",
    "sizeBytes": 34842,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 7,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 58,
        "columnsObserved": 30,
        "sampleHeaders": [
          "PLANTEL",
          "TOTAL GRUPOS"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "TOTAL GRUPOS"
          ]
        ],
        "numericCells": 396,
        "textCells": 961,
        "formulaCells": 7
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "e3fe144db2d2799a",
    "sourceLabel": "Academias BG24_Campo disciplinar_v4.0.xlsx",
    "sourcePathHash": "e3fe144db2d2799afa4138e073d1493bdd712e53c06851ca785be1ae56befb8b",
    "category": "Academias BG24_Campo disciplinar_v4.0.xlsx",
    "sizeBytes": 54555,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 38,
        "columnsObserved": 5,
        "sampleHeaders": [
          "Nombre del docente",
          "Correo electrónico institucional"
        ],
        "headerRows": [
          [
            "Nombre del docente",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ],
          [
            "Nombre",
            "Correo electrónico institucional"
          ]
        ],
        "numericCells": 26,
        "textCells": 104,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "d98834ed57b28d61",
    "sourceLabel": "Formato de cronograma de academia de plantel.xlsx",
    "sourcePathHash": "d98834ed57b28d61e5ab86d90b72e41399cc856897aac3bfcde2e03eb2d4832b",
    "category": "Formato de cronograma de academia de plantel.xlsx",
    "sizeBytes": 10548,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "5, 3 y 1 semestre",
        "nonEmptyRows": 42,
        "columnsObserved": 7,
        "sampleHeaders": [],
        "headerRows": [],
        "numericCells": 9,
        "textCells": 81,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "b53f23a15735d9f1",
    "sourceLabel": "2) Bachillerato 16 AGOSTO 2024 -ENERO 2025.xlsx",
    "sourcePathHash": "b53f23a15735d9f1de0f0122c3f6ac41181b459527c8bd54186d753835dcc302",
    "category": "Prácticas de Laboratorios",
    "sizeBytes": 33166,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 7,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 51,
        "columnsObserved": 30,
        "sampleHeaders": [
          "PLANTEL",
          "TOTAL GRUPOS"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "TOTAL GRUPOS"
          ]
        ],
        "numericCells": 333,
        "textCells": 828,
        "formulaCells": 7
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "ac7360174ecb82bc",
    "sourceLabel": "Idiomas.xlsx",
    "sourcePathHash": "ac7360174ecb82bc0b4e0a57a8bf468b1e21869a7961182d894a1b7f81c7077f",
    "category": "Idiomas.xlsx",
    "sizeBytes": 9095,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Hoja1",
        "nonEmptyRows": 6,
        "columnsObserved": 5,
        "sampleHeaders": [
          "Nombre",
          "Correo electrónico institucional"
        ],
        "headerRows": [
          [
            "Nombre",
            "Correo electrónico institucional"
          ]
        ],
        "numericCells": 8,
        "textCells": 18,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "76b62473a2fb7984",
    "sourceLabel": "Formato conformación de academias por plantel.xlsx",
    "sourcePathHash": "76b62473a2fb7984084c0ff7ac8bdb559d0e16a7914b8827898da48393bdfead",
    "category": "Formato conformación de academias por plantel.xlsx",
    "sizeBytes": 33506,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "INFORME SEMESTRAL AGOSTO",
        "nonEmptyRows": 25,
        "columnsObserved": 12,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE DEL PROGRAMA",
          "No. DE ACADEMIAS POR PLANTEL",
          "ACTIVIDADES DE TRABAJO REALIZADAS",
          "DOCENTES QUE PARTICIPARON EN LAS ACADEMIAS",
          "TOTAL"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE DEL PROGRAMA",
            "No. DE ACADEMIAS POR PLANTEL",
            "ACTIVIDADES DE TRABAJO REALIZADAS",
            "DOCENTES QUE PARTICIPARON EN LAS ACADEMIAS",
            "TOTAL"
          ]
        ],
        "numericCells": 18,
        "textCells": 41,
        "formulaCells": 0
      },
      {
        "name": "INFORME SEMESTRAL FEBRERO",
        "nonEmptyRows": 26,
        "columnsObserved": 12,
        "sampleHeaders": [
          "PLANTEL",
          "NOMBRE DEL PROGRAMA",
          "No. DE ACADEMIAS POR PLANTEL",
          "ACTIVIDADES DE TRABAJO REALIZADAS",
          "DOCENTES QUE PARTICIPARON EN LAS ACADEMIAS",
          "TOTAL"
        ],
        "headerRows": [
          [
            "PLANTEL",
            "NOMBRE DEL PROGRAMA",
            "No. DE ACADEMIAS POR PLANTEL",
            "ACTIVIDADES DE TRABAJO REALIZADAS",
            "DOCENTES QUE PARTICIPARON EN LAS ACADEMIAS",
            "TOTAL"
          ]
        ],
        "numericCells": 17,
        "textCells": 51,
        "formulaCells": 0
      },
      {
        "name": "0",
        "nonEmptyRows": 0,
        "columnsObserved": 0,
        "sampleHeaders": [],
        "headerRows": [],
        "numericCells": 0,
        "textCells": 0,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  },
  {
    "id": "cf8ae174cdb1a9b1",
    "sourceLabel": "Registro interesados manuales inglés.xlsx",
    "sourcePathHash": "cf8ae174cdb1a9b1152fa7af9c13df6afd7eaaf9e2d2794aea7d61076c445906",
    "category": "Registro interesados manuales inglés.xlsx",
    "sizeBytes": 193530,
    "detectedIndicatorCodes": [],
    "detectedPlanteles": [
      "Bachillerato 16"
    ],
    "formulaCells": 0,
    "sheets": [
      {
        "name": "Registro Manuales",
        "nonEmptyRows": 5,
        "columnsObserved": 8,
        "sampleHeaders": [
          "Plantel donde labora",
          "Nombre",
          "Correo"
        ],
        "headerRows": [
          [
            "Plantel donde labora",
            "Nombre",
            "Correo"
          ]
        ],
        "numericCells": 3,
        "textCells": 26,
        "formulaCells": 0
      }
    ],
    "privacy": "Row-level personal data remains in private storage only."
  }
];
