-- SCRUM-41 / SCRUM-44
-- Initial SIGI-POA schema for PostgreSQL.
-- This migration intentionally stores only evidence metadata. Real files must
-- live in private object/file storage outside Git.

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  description TEXT,
  permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT roles_code_not_blank CHECK (length(trim(code)) > 0),
  CONSTRAINT roles_name_not_blank CHECK (length(trim(name)) > 0)
);

CREATE TABLE IF NOT EXISTS planteles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(180) NOT NULL,
  municipality VARCHAR(120),
  region VARCHAR(120),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT planteles_code_not_blank CHECK (length(trim(code)) > 0),
  CONSTRAINT planteles_name_not_blank CHECK (length(trim(name)) > 0)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id BIGINT NOT NULL REFERENCES roles(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  plantel_id BIGINT REFERENCES planteles(id) ON UPDATE CASCADE ON DELETE SET NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  full_name VARCHAR(180) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT users_email_not_blank CHECK (length(trim(email)) > 0),
  CONSTRAINT users_full_name_not_blank CHECK (length(trim(full_name)) > 0)
);

CREATE TABLE IF NOT EXISTS operational_years (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year SMALLINT NOT NULL UNIQUE,
  label VARCHAR(80) NOT NULL,
  starts_at DATE NOT NULL,
  ends_at DATE NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT operational_years_valid_range CHECK (starts_at <= ends_at),
  CONSTRAINT operational_years_valid_year CHECK (year BETWEEN 2000 AND 2100)
);

CREATE TABLE IF NOT EXISTS indicators (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operational_year_id BIGINT NOT NULL REFERENCES operational_years(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  code VARCHAR(60) NOT NULL,
  name VARCHAR(240) NOT NULL,
  description TEXT,
  measurement_unit VARCHAR(80),
  target_value NUMERIC(14, 4),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT indicators_code_not_blank CHECK (length(trim(code)) > 0),
  CONSTRAINT indicators_name_not_blank CHECK (length(trim(name)) > 0),
  CONSTRAINT indicators_year_code_unique UNIQUE (operational_year_id, code)
);

CREATE TABLE IF NOT EXISTS activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  indicator_id BIGINT NOT NULL REFERENCES indicators(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  code VARCHAR(60),
  name VARCHAR(240) NOT NULL,
  description TEXT,
  evidence_required BOOLEAN NOT NULL DEFAULT FALSE,
  form_schema JSONB NOT NULL DEFAULT '{}'::jsonb,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT activities_name_not_blank CHECK (length(trim(name)) > 0),
  CONSTRAINT activities_indicator_code_unique UNIQUE (indicator_id, code)
);

CREATE TABLE IF NOT EXISTS periods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operational_year_id BIGINT NOT NULL REFERENCES operational_years(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  code VARCHAR(60) NOT NULL,
  name VARCHAR(120) NOT NULL,
  period_type VARCHAR(40) NOT NULL,
  starts_at DATE NOT NULL,
  ends_at DATE NOT NULL,
  capture_opens_at TIMESTAMPTZ,
  capture_closes_at TIMESTAMPTZ,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT periods_valid_range CHECK (starts_at <= ends_at),
  CONSTRAINT periods_capture_valid_range CHECK (
    capture_opens_at IS NULL OR capture_closes_at IS NULL OR capture_opens_at <= capture_closes_at
  ),
  CONSTRAINT periods_type_allowed CHECK (period_type IN ('quincenal', 'mensual', 'bimestral', 'semestral', 'anual', 'otro')),
  CONSTRAINT periods_year_code_unique UNIQUE (operational_year_id, code)
);

CREATE TABLE IF NOT EXISTS assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  plantel_id BIGINT REFERENCES planteles(id) ON UPDATE CASCADE ON DELETE CASCADE,
  indicator_id BIGINT REFERENCES indicators(id) ON UPDATE CASCADE ON DELETE CASCADE,
  activity_id BIGINT REFERENCES activities(id) ON UPDATE CASCADE ON DELETE CASCADE,
  responsibility VARCHAR(40) NOT NULL DEFAULT 'primary',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by_user_id BIGINT REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT assignments_responsibility_allowed CHECK (responsibility IN ('primary', 'secondary', 'contributor')),
  CONSTRAINT assignments_exactly_one_scope CHECK (
    ((plantel_id IS NOT NULL)::integer + (indicator_id IS NOT NULL)::integer + (activity_id IS NOT NULL)::integer) = 1
  ),
  CONSTRAINT assignments_unique_scope UNIQUE (user_id, plantel_id, indicator_id, activity_id, responsibility)
);

CREATE TABLE IF NOT EXISTS submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operational_year_id BIGINT NOT NULL REFERENCES operational_years(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  period_id BIGINT NOT NULL REFERENCES periods(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  plantel_id BIGINT NOT NULL REFERENCES planteles(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  indicator_id BIGINT NOT NULL REFERENCES indicators(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  activity_id BIGINT NOT NULL REFERENCES activities(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  status VARCHAR(40) NOT NULL DEFAULT 'draft',
  progress_percent NUMERIC(5, 2) NOT NULL DEFAULT 0,
  captured_values JSONB NOT NULL DEFAULT '{}'::jsonb,
  submitted_by_user_id BIGINT REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  submitted_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT submissions_status_allowed CHECK (status IN ('draft', 'submitted', 'in_review', 'correction', 'approved', 'closed')),
  CONSTRAINT submissions_progress_range CHECK (progress_percent >= 0 AND progress_percent <= 100),
  CONSTRAINT submissions_unique_period_activity UNIQUE (operational_year_id, period_id, plantel_id, activity_id)
);

CREATE TABLE IF NOT EXISTS submission_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id BIGINT NOT NULL REFERENCES submissions(id) ON UPDATE CASCADE ON DELETE CASCADE,
  version_number INTEGER NOT NULL,
  status VARCHAR(40) NOT NULL,
  captured_values JSONB NOT NULL,
  change_reason TEXT,
  created_by_user_id BIGINT REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT submission_versions_version_positive CHECK (version_number > 0),
  CONSTRAINT submission_versions_unique_version UNIQUE (submission_id, version_number)
);

CREATE TABLE IF NOT EXISTS evidence_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id BIGINT NOT NULL REFERENCES submissions(id) ON UPDATE CASCADE ON DELETE CASCADE,
  uploaded_by_user_id BIGINT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  replaced_by_evidence_file_id BIGINT REFERENCES evidence_files(id) ON UPDATE CASCADE ON DELETE SET NULL,
  original_file_name VARCHAR(255) NOT NULL,
  storage_provider VARCHAR(80) NOT NULL DEFAULT 'local_private_storage',
  storage_key VARCHAR(512) NOT NULL,
  public_url TEXT,
  mime_type VARCHAR(160) NOT NULL,
  byte_size BIGINT NOT NULL,
  checksum_sha256 CHAR(64),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  version_number INTEGER NOT NULL DEFAULT 1,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT evidence_files_original_name_not_blank CHECK (length(trim(original_file_name)) > 0),
  CONSTRAINT evidence_files_storage_key_not_blank CHECK (length(trim(storage_key)) > 0),
  CONSTRAINT evidence_files_byte_size_positive CHECK (byte_size > 0),
  CONSTRAINT evidence_files_version_positive CHECK (version_number > 0),
  CONSTRAINT evidence_files_checksum_format CHECK (checksum_sha256 IS NULL OR checksum_sha256 ~ '^[0-9a-f]{64}$')
);

CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id BIGINT NOT NULL REFERENCES submissions(id) ON UPDATE CASCADE ON DELETE CASCADE,
  reviewer_user_id BIGINT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  decision VARCHAR(40) NOT NULL,
  observations TEXT,
  reviewed_values JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT reviews_decision_allowed CHECK (decision IN ('approved', 'correction_requested', 'rejected', 'closed')),
  CONSTRAINT reviews_observation_required_for_correction CHECK (
    decision <> 'correction_requested' OR length(trim(coalesce(observations, ''))) > 0
  )
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  event_type VARCHAR(80) NOT NULL,
  entity_type VARCHAR(80) NOT NULL,
  entity_id BIGINT,
  field_name VARCHAR(120),
  previous_value JSONB,
  new_value JSONB,
  change_set JSONB NOT NULL DEFAULT '{}'::jsonb,
  version_number INTEGER,
  request_context JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT audit_logs_event_type_not_blank CHECK (length(trim(event_type)) > 0),
  CONSTRAINT audit_logs_entity_type_not_blank CHECK (length(trim(entity_type)) > 0),
  CONSTRAINT audit_logs_version_positive CHECK (version_number IS NULL OR version_number > 0)
);

CREATE INDEX IF NOT EXISTS idx_users_role_id ON users(role_id);
CREATE INDEX IF NOT EXISTS idx_users_plantel_id ON users(plantel_id);
CREATE INDEX IF NOT EXISTS idx_activities_indicator_id ON activities(indicator_id);
CREATE INDEX IF NOT EXISTS idx_periods_operational_year_id ON periods(operational_year_id);
CREATE INDEX IF NOT EXISTS idx_assignments_user_id ON assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_assignments_plantel_id ON assignments(plantel_id) WHERE plantel_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_assignments_indicator_id ON assignments(indicator_id) WHERE indicator_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_assignments_activity_id ON assignments(activity_id) WHERE activity_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_submissions_scope ON submissions(operational_year_id, period_id, plantel_id, indicator_id, activity_id);
CREATE INDEX IF NOT EXISTS idx_submissions_status ON submissions(status);
CREATE INDEX IF NOT EXISTS idx_submission_versions_submission_id ON submission_versions(submission_id);
CREATE INDEX IF NOT EXISTS idx_evidence_files_submission_id ON evidence_files(submission_id);
CREATE INDEX IF NOT EXISTS idx_evidence_files_uploaded_by ON evidence_files(uploaded_by_user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_submission_id ON reviews(submission_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewer_user_id ON reviews(reviewer_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_user_id ON audit_logs(actor_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_event_created ON audit_logs(event_type, created_at DESC);

INSERT INTO roles (code, name, description, permissions)
VALUES
  ('admin', 'Administrador DGEMS', 'Administra catalogos, usuarios, permisos, reportes y auditoria.', '["*"]'::jsonb),
  ('responsable', 'Responsable de indicador', 'Revisa capturas y evidencias de indicadores asignados.', '["indicators:read","review:approve","review:correct","evidence:download","reports:read"]'::jsonb),
  ('plantel', 'Plantel', 'Captura avances y administra evidencias de su plantel.', '["indicators:read","submission:write","evidence:upload","evidence:download"]'::jsonb)
ON CONFLICT (code) DO UPDATE
SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  permissions = EXCLUDED.permissions,
  updated_at = CURRENT_TIMESTAMP;
