-- SCRUM-42 / SCRUM-43 / SCRUM-44
-- Import idempotency guards, submission state machine and stronger audit metadata.

ALTER TABLE assignments DROP CONSTRAINT IF EXISTS assignments_unique_scope;

CREATE UNIQUE INDEX IF NOT EXISTS assignments_unique_user_plantel_responsibility
  ON assignments (user_id, plantel_id, responsibility)
  WHERE plantel_id IS NOT NULL AND active = TRUE AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS assignments_unique_user_indicator_responsibility
  ON assignments (user_id, indicator_id, responsibility)
  WHERE indicator_id IS NOT NULL AND active = TRUE AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS assignments_unique_user_activity_responsibility
  ON assignments (user_id, activity_id, responsibility)
  WHERE activity_id IS NOT NULL AND active = TRUE AND deleted_at IS NULL;

ALTER TABLE submissions
  ADD COLUMN IF NOT EXISTS current_version_number INTEGER NOT NULL DEFAULT 1;

ALTER TABLE submission_versions
  ADD COLUMN IF NOT EXISTS is_current BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS submission_versions_one_current
  ON submission_versions (submission_id)
  WHERE is_current = TRUE AND active = TRUE AND deleted_at IS NULL;

ALTER TABLE reviews
  ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE audit_logs
  ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE evidence_files
  DROP COLUMN IF EXISTS public_url;

CREATE TABLE IF NOT EXISTS submission_status_transitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_status VARCHAR(40) NOT NULL,
  to_status VARCHAR(40) NOT NULL,
  actor_role VARCHAR(40) NOT NULL,
  requires_observation BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT submission_status_transitions_allowed_from CHECK (from_status IN ('draft', 'submitted', 'in_review', 'correction', 'approved', 'closed')),
  CONSTRAINT submission_status_transitions_allowed_to CHECK (to_status IN ('draft', 'submitted', 'in_review', 'correction', 'approved', 'closed')),
  CONSTRAINT submission_status_transitions_actor_allowed CHECK (actor_role IN ('admin', 'responsable', 'plantel')),
  CONSTRAINT submission_status_transitions_unique UNIQUE (from_status, to_status, actor_role)
);

INSERT INTO submission_status_transitions (from_status, to_status, actor_role, requires_observation)
VALUES
  ('draft', 'submitted', 'plantel', FALSE),
  ('draft', 'submitted', 'admin', FALSE),
  ('submitted', 'in_review', 'responsable', FALSE),
  ('submitted', 'in_review', 'admin', FALSE),
  ('in_review', 'correction', 'responsable', TRUE),
  ('in_review', 'correction', 'admin', TRUE),
  ('correction', 'draft', 'plantel', FALSE),
  ('correction', 'submitted', 'plantel', FALSE),
  ('in_review', 'approved', 'responsable', FALSE),
  ('in_review', 'approved', 'admin', FALSE),
  ('approved', 'closed', 'admin', FALSE)
ON CONFLICT (from_status, to_status, actor_role) DO UPDATE
SET
  requires_observation = EXCLUDED.requires_observation,
  active = TRUE;

CREATE TABLE IF NOT EXISTS import_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_name VARCHAR(180) NOT NULL,
  source_checksum_sha256 CHAR(64) NOT NULL,
  operational_year SMALLINT NOT NULL,
  indicator_count INTEGER NOT NULL,
  activity_count INTEGER NOT NULL,
  responsible_count INTEGER NOT NULL,
  contributor_count INTEGER NOT NULL,
  summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT import_runs_counts_positive CHECK (
    indicator_count > 0 AND activity_count > 0 AND responsible_count > 0 AND contributor_count > 0
  ),
  CONSTRAINT import_runs_checksum_format CHECK (source_checksum_sha256 ~ '^[0-9a-f]{64}$'),
  CONSTRAINT import_runs_source_unique UNIQUE (source_name, source_checksum_sha256)
);

CREATE INDEX IF NOT EXISTS idx_import_runs_created_at ON import_runs(created_at DESC);
